-- Mission Seed for Lombardia Part 2a (VA, LC, PV)
-- Generated by Antigravity

-- 7. VARESE (VA) - Tax & Authority Phishing (Agenzia delle Entrate)

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '930E95CC-087B-471F-B2BE-7A066F683EF6', 'VA', 'Rimborso Fiscale',
    'Una mail dall''Agenzia delle Entrate promette soldi. Apri?',
    E'# "Hai diritto a un rimborso"\n\nIl sogno di tutti: il fisco che ti ridà i soldi.\nLe mail sembrano identiche a quelle vere, ma ti chiedono di cliccare su un link per inserire i dati della carta di credito.\n\nL''Agenzia delle Entrate **non chiede mai dati bancari via mail**.',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('930E95CC-087B-471F-B2BE-7A066F683EF6', 'Se ricevi una mail di "Rimborso da accettare entro 24h", è vera?', 'multiple_choice', '["Sì", "No. L''urgenza è un classico segnale di phishing", "Forse", "Dipende"]', 1, 'La burocrazia vera è lenta, non ti mette fretta.'),
('930E95CC-087B-471F-B2BE-7A066F683EF6', 'Dove dovresti controllare se hai davvero diritto a un rimborso?', 'multiple_choice', '["Cliccando sul link nella mail", "Accedendo al sito ufficiale (AgenziaEntrate.gov.it) tramite SPID", "Andando al bar", "Chiedendo su Facebook"]', 1, 'Il Cassetto Fiscale è l''unica fonte di verità.'),
('930E95CC-087B-471F-B2BE-7A066F683EF6', 'L''indirizzo "agenzia.entrate@rimborsi-gov.info" è legittimo?', 'multiple_choice', '["Sì", "No. Il dominio ufficiale è .gov.it, non .info o altri", "Sembra di sì", "Boh"]', 1, 'Controlla sempre l''estensione del dominio.'),
('930E95CC-087B-471F-B2BE-7A066F683EF6', 'Perché ti chiedono la carta di credito per DARTI soldi?', 'multiple_choice', '["Per verificare l''identità", "È una truffa. Per ricevere soldi serve l''IBAN, non il numero della carta (che serve per PAGARE)", "Per le tasse", "Per amicizia"]', 1, 'Se chiedono il CVV (codice dietro la carta) per un accredito, scappa.'),
('930E95CC-087B-471F-B2BE-7A066F683EF6', 'Cosa fare con la mail falsa?', 'multiple_choice', '["Rispondere insultando", "Segnalarla come spam/phishing e cancellarla", "Inoltrarla agli amici", "Stamparla"]', 1, 'Non interagire mai.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '73D2B298-89B9-4B37-BFA3-AB724F806067', 'VA', 'La PEC Malevola',
    'La PEC ha valore legale, ma può contenere virus?',
    E'# PEC non significa Sicuro\n\nLa Posta Elettronica Certificata garantisce l''identità del mittente e la data, ma **non garantisce che l''allegato sia sicuro**.\n\nMolte campagne di malware (es. sLoad) si diffondono via PEC rubate ad avvocati o commercialisti.',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('73D2B298-89B9-4B37-BFA3-AB724F806067', 'Una PEC può contenere un virus?', 'multiple_choice', '["No, è certificata dallo Stato", "Sì, assolutamente. La certificazione riguarda la trasmissione, non il contenuto", "Solo se è gialla", "Mai"]', 1, 'È un mito pericoloso credere che PEC = Sicurezza Totale.'),
('73D2B298-89B9-4B37-BFA3-AB724F806067', 'Perché gli hacker usano la PEC?', 'multiple_choice', '["Costa meno", "Perché la vittima si fida di più (Bias di Autorità) e la apre subito", "È più veloce", "È obbligatoria"]', 1, 'Se vedi una busta verde/legale, ti spaventi e apri.'),
('73D2B298-89B9-4B37-BFA3-AB724F806067', 'Come si infettano le caselle PEC dei professionisti?', 'multiple_choice', '["Magia", "Password deboli o phishing precedente", "Dal vento", "Dalla carta"]', 1, 'Spesso non hanno la 2FA attiva sulle PEC.'),
('73D2B298-89B9-4B37-BFA3-AB724F806067', 'Cosa contiene di solito la PEC infetta?', 'multiple_choice', '["Una foto di gattini", "Una finta fattura XML o un ZIP con dentro uno script malevolo (JS/VBS)", "Una poesia", "Nulla"]', 1, 'Fingono di inviare fatture elettroniche.'),
('73D2B298-89B9-4B37-BFA3-AB724F806067', 'Se ricevi una PEC inattesa da uno sconosciuto?', 'multiple_choice', '["Apro subito", "Non apro gli allegati e verifico l''oggetto/mittente", "La stampo", "Rispondo"]', 1, 'La prudenza vince sempre.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '32B21E4D-A2FC-4B49-824B-DCBBE326A960', 'VA', 'Verifica Ufficiale',
    'Come distinguere il vero dal falso sui portali PA.',
    E'# SPID è il tuo scudo\n\nLe comunicazioni vere della PA arrivano dentro i portali (INPS, Agenzia Entrate) a cui accedi con SPID/CIE.\n\nLe mail sono solo **notifiche** ("C''è un nuovo documento per te"), non contengono mai il documento o il link diretto al pagamento.',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('32B21E4D-A2FC-4B49-824B-DCBBE326A960', 'Una mail INPS con link "Clicca qui per aggiornare i dati" è affidabile?', 'multiple_choice', '["Sì", "No. L''INPS non manda link cliccabili per aggiornare dati, devi andare tu sul portale", "Sempre", "Di solito sì"]', 1, 'Nessun ente serio ti manda link diretti di login via mail.'),
('32B21E4D-A2FC-4B49-824B-DCBBE326A960', 'Cos''è PagoPA?', 'multiple_choice', '["Un''app di giochi", "Il sistema unico per i pagamenti verso la PA", "Un social network", "Una banca"]', 1, 'Se ti chiedono di pagare su un IBAN estero invece che tramite PagoPA, è una truffa.'),
('32B21E4D-A2FC-4B49-824B-DCBBE326A960', 'Se perdi le credenziali SPID?', 'multiple_choice', '["Ne fai un altro", "Devi bloccarle/revocarle immediatamente tramite il tuo Identity Provider (es. Poste, Aruba)", "Aspetti", "Piangi"]', 1, 'SPID è la tua identità digitale: chi ce l''ha, sei tu.'),
('32B21E4D-A2FC-4B49-824B-DCBBE326A960', 'Perché dovresti attivare le notifiche dell''App IO?', 'multiple_choice', '["Per giocare", "È il canale ufficiale e sicuro per ricevere avvisi dalla PA", "Consuma batteria", "È noioso"]', 1, 'È molto più sicura delle mail perché è integrata nel sistema.'),
('32B21E4D-A2FC-4B49-824B-DCBBE326A960', 'Cosa fare se sospetti un furto d''identità fiscale?', 'multiple_choice', '["Niente", "Verificare il Cassetto Fiscale per vedere se qualcuno ha usato i tuoi dati per frodi", "Scappare", "Cambiare nome"]', 1, 'Il controllo periodico è una buona abitudine.');


-- 8. LECCO (LC) - Online Shopping High-Ticket

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '31DF9011-FAD7-4C61-9F79-B9919818C256', 'LC', 'L''Affare del Secolo',
    'Un''auto usata a metà prezzo. "Devo venderla subito perché parto".',
    E'# La fretta cattiva consigliera\n\nTrovi un''auto o un orologio di lusso a un prezzo stracciato.\nIl venditore ha una storia triste o urgente: "Divorzio", "Trasferimento all''estero".\n\nChiede un piccolo acconto per "fermare" l''oggetto. Se paghi, sparisce.',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('31DF9011-FAD7-4C61-9F79-B9919818C256', 'Perché i prezzi stracciati sono sospetti?', 'multiple_choice', '["Il venditore è generoso", "Nessuno regala soldi. Se costa la metà, c''è un motivo (truffa o merce rubata)", "È il Black Friday", "È un errore"]', 1, 'Il mercato ha prezzi standard. Le deviazioni eccessive sono Red Flags.'),
('31DF9011-FAD7-4C61-9F79-B9919818C256', 'Mai inviare documenti d''identità al venditore?', 'multiple_choice', '["Vero. Li useranno per falsificare l''identità", "Falso, serve per fidarsi", "Solo se è simpatico", "Solo la foto"]', 0, 'Mandare la foto della carta d''identità è pericolosissimo.'),
('31DF9011-FAD7-4C61-9F79-B9919818C256', 'Se chiedono di pagare ricaricando una carta prepagata?', 'multiple_choice', '["Ok", "Mai. Non è tracciabile e non hai tutele", "Va bene se è poco", "Solo se insistono"]', 1, 'Equivale a dare contanti a uno sconosciuto per strada.'),
('31DF9011-FAD7-4C61-9F79-B9919818C256', 'Cosa fare prima di comprare un''auto online?', 'multiple_choice', '["Pagare", "Vederla di persona e controllare targa/telaio", "Sognarla", "Fidarsi delle foto"]', 1, 'Le foto si rubano. L''auto fisica no.'),
('31DF9011-FAD7-4C61-9F79-B9919818C256', 'Le recensioni del venditore sono affidabili?', 'multiple_choice', '["Sempre", "Non sempre. Possono essere false o comprate", "Mai", "Solo se sono 5 stelle"]', 1, 'Guarda se ha recensioni vecchie o solo recenti.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '1893FFAE-37F6-49AC-AECB-CAB015799D65', 'LC', 'La Triangolazione',
    'Compri un oggetto, ti arriva davvero, ma sei parte di una truffa.',
    E'# Truffa della Triangolazione\n\n1.  Compri una PS5 da un sito truffaldino a 300€.\n2.  Il sito truffaldino ordina una PS5 vera su Amazon (coi soldi di una carta rubata) e la spedisce a te.\n3.  Tu sei felice, ma tra un mese la Polizia bussa alla tua porta per ricettazione.',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('1893FFAE-37F6-49AC-AECB-CAB015799D65', 'Cos''è la truffa della triangolazione?', 'multiple_choice', '["Geometria", "Il truffatore usa i tuoi soldi "puliti" e una carta rubata per comprare la merce che ti spedisce", "Un disegno", "Tre persone"]', 1, 'Tu diventi il punto finale di riciclaggio.'),
('1893FFAE-37F6-49AC-AECB-CAB015799D65', 'Come accorgersene?', 'multiple_choice', '["Dall''odore", "Se il pacco arriva da Amazon/negozio noto ma tu hai comprato da ''ElettronicaGino.com''", "Non si può", "Dalla scatola"]', 1, 'Se il mittente sulla scatola non corrisponde al sito dove hai comprato.'),
('1893FFAE-37F6-49AC-AECB-CAB015799D65', 'Sei colpevole?', 'multiple_choice', '["No, mai", "Potresti essere indagato per incauto acquisto se il prezzo era palesemente troppo basso", "Sì, sempre", "Forse"]', 1, 'La legge non ammette ignoranza se l''affare era "sospetto".'),
('1893FFAE-37F6-49AC-AECB-CAB015799D65', 'Cosa fare se succede?', 'multiple_choice', '["Tienilo", "Denunciare l''accaduto e conservare tutte le prove d''acquisto", "Venderlo", "Buttarlo"]', 1, 'La trasparenza con le autorità è fondamentale.'),
('1893FFAE-37F6-49AC-AECB-CAB015799D65', 'Perché lo fanno?', 'multiple_choice', '["Per bontà", "Per trasformare soldi rubati (carte clonate) in soldi puliti (il tuo pagamento)", "Per sport", "Per Amazon"]', 1, 'È riciclaggio di denaro.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'D4CAC3CA-13F8-4A4A-BA5A-4C4F73655185', 'LC', 'Escrow Falso',
    'Ti propongono un "sito di garanzia" per il pagamento. È loro.',
    E'# Escrow Scam\n\nPer rassicurarti, il truffatore propone: "Usiamo un servizio di Escrow (garante). Tu paghi loro, loro tengono i soldi finché non ricevi la merce".\n\nTi mandano il link di un sito che sembra serio (es. "SafePayEurope").\nIn realtà **il sito è finto ed è gestito da loro**.',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('D4CAC3CA-13F8-4A4A-BA5A-4C4F73655185', 'Cos''è un servizio Escrow (vero)?', 'multiple_choice', '["Una truffa", "Una terza parte neutrale che custodisce i fondi durante una transazione", "Una banca", "Un avvocato"]', 1, 'Servizi come PayPal o Chrono24 offrono questa protezione.'),
('D4CAC3CA-13F8-4A4A-BA5A-4C4F73655185', 'Come riconoscere un Escrow falso?', 'multiple_choice', '["È brutto", "Link inviato dal venditore, dominio registrato da poco (Whois), nessuna recensione online", "È verde", "È lento"]', 1, 'Mai usare un link fornito dalla controparte. Cerca il servizio su Google.'),
('D4CAC3CA-13F8-4A4A-BA5A-4C4F73655185', 'Se il sito ha un lucchetto HTTPS è sicuro?', 'multiple_choice', '["Sì", "No. Anche i siti truffa hanno HTTPS (certificati gratuiti)", "Sempre", "Mai"]', 1, 'HTTPS significa solo "connessione criptata", non "sito onesto".'),
('D4CAC3CA-13F8-4A4A-BA5A-4C4F73655185', 'Perché funziona?', 'multiple_choice', '["Perché la gente è stupida", "Perché simula sicurezza professionale e abbassa le difese della vittima", "Per caso", "Per soldi"]', 1, 'Sfrutta il desiderio di sicurezza della vittima contro di lei.'),
('D4CAC3CA-13F8-4A4A-BA5A-4C4F73655185', 'Qual è un vero servizio di protezione?', 'multiple_choice', '["Bonifico istantaneo", "PayPal Beni e Servizi (NON ''Amici e Familiari'')", "Ricarica telefonica", "Contanti"]', 1, 'Amici e Familiari non ha protezione acquisti.');


-- 9. PAVIA (PV) - Student & Job Scams

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '73B93CF1-DAE4-45AB-8723-BBE3061703C3', 'PV', 'Lavoro dei Sogni',
    'Guadagna 3000€ al mese lavorando 1 ora da casa. Troppo bello?',
    E'# Job Scams\n\nGli studenti e i disoccupati sono bersagli fragili.\nOfferte di lavoro che promettono guadagni facili con zero competenze.\n\nSpesso chiedono:\n1.  Soldi per "Kit di inizio" o "Corsi".\n2.  Dati bancari per "accreditare lo stipendio" (furto dati).',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('73B93CF1-DAE4-45AB-8723-BBE3061703C3', 'Un datore di lavoro ti chiede soldi per iniziare. È normale?', 'multiple_choice', '["Sì, per le spese", "No. Mai pagari per lavorare. È una truffa", "Dipende", "Solo se pochi"]', 1, 'Il flusso di denaro nel lavoro va dal datore al dipendente, mai il contrario.'),
('73B93CF1-DAE4-45AB-8723-BBE3061703C3', 'Quali canali usano?', 'multiple_choice', '["LinkedIn (a volte), ma soprattutto Telegram, WhatsApp e TikTok", "Solo giornali", "Solo TV", "Piccioni"]', 0, 'I social sono pieni di annunci fake.'),
('73B93CF1-DAE4-45AB-8723-BBE3061703C3', 'Se l''offerta è scritta in italiano sgrammaticato?', 'multiple_choice', '["Sono stranieri", "Red Flag (Segnale d''allarme)", "È un dialetto", "Va bene"]', 1, 'Le aziende serie curano la comunicazione.'),
('73B93CF1-DAE4-45AB-8723-BBE3061703C3', 'A cosa mirano davvero?', 'multiple_choice', '["A darti lavoro", "A rubare i tuoi dati personali (Documenti) per furti d''identità o farti riciclare denaro", "Ad aiutarti", "A fare amicizia"]', 1, 'Il "lavoro" è solo un''esca.'),
('73B93CF1-DAE4-45AB-8723-BBE3061703C3', 'Cosa fare prima di accettare?', 'multiple_choice', '["Firmare", "Cercare il nome dell''azienda online + ''truffa'' o ''opinioni''", "Andare al lavoro", "Comprare il kit"]', 1, 'La Reputazione online è la prima verifica.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '59676610-992F-401B-8D5D-7B4D9CAAE333', 'PV', 'Il Money Mule',
    'Ti pagano per ricevere bonifici e girarli altrove. Sei un criminale.',
    E'# Muli di Denaro\n\nIl lavoro consiste nel ricevere soldi sul TUO conto e girarli via Western Union/Bitcoin trattenendo una commissione del 10%.\n\nSembra facile? **Stai riciclando denaro sporco**.\nPer la legge sei complice, non vittima.',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('59676610-992F-401B-8D5D-7B4D9CAAE333', 'Chi è un Money Mule?', 'multiple_choice', '["Un animale", "Una persona che trasferisce denaro di origine illecita per conto di altri", "Un banchiere", "Un ricco"]', 1, 'Spesso reclutati inconsapevolmente con offerte di lavoro fake ("Financial Manager").'),
('59676610-992F-401B-8D5D-7B4D9CAAE333', 'Cosa rischi legalmente?', 'multiple_choice', '["Niente se non sapevo", "Incriminazione per riciclaggio di denaro", "Una multa", "Un premio"]', 1, 'L''ignoranza non scusa il crimine di riciclaggio.'),
('59676610-992F-401B-8D5D-7B4D9CAAE333', 'Perché i criminali usano i muli?', 'multiple_choice', '["Sono pigri", "Per interrompere la tracciabilità del denaro e non usare i propri conti", "Per beneficenza", "Per divertimento"]', 1, 'Il mulo è quello che si assume il rischio (e viene arrestato).'),
('59676610-992F-401B-8D5D-7B4D9CAAE333', 'Se ti accorgi di essere coinvolto?', 'multiple_choice', '["Continui", "Smetti subito e contatti la polizia/banca", "Scappi", "Tieni i soldi"]', 1, 'Collaborare è l''unica via d''uscita.'),
('59676610-992F-401B-8D5D-7B4D9CAAE333', 'Come viene chiamato questo ruolo negli annunci?', 'multiple_choice', '["Riciclatore", "Agente di trasferimento fondi, Payment Processor, Responsabile amministrativo locale", "Ladro", "Mulo"]', 1, 'Usano titoli altisonanti per sembrare legittimi.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'F8A8784D-4E36-419D-AC1D-E4B6F205C7E0', 'PV', 'Il Colloquio Fake',
    'Interviste su Skype/Zoom che sembrano vere. Il furto è nei dettagli.',
    E'# Skype Interview Scam\n\nFai un colloquio video.\nTi chiedono di condividere lo schermo o installare un software per il "test tecnico".\n\nIn realtà ti stanno facendo installare un **Trojan** o rubando le sessioni browser.',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('F8A8784D-4E36-419D-AC1D-E4B6F205C7E0', 'È sicuro installare software inviati dal recruiter?', 'multiple_choice', '["Sì", "No. Mai installare nulla inviato via chat/mail. Usa solo tool ufficiali scaricati dai siti ufficiali", "Sempre", "Se insistono"]', 1, 'È un vettore comune per infezioni aziendali.'),
('F8A8784D-4E36-419D-AC1D-E4B6F205C7E0', 'Se ti chiedono di accedere al tuo Home Banking durante il colloquio "per verifica"?', 'multiple_choice', '["Accedo", "Follia. Chiudo la chiamata", "Chiedo perché", "Lo faccio"]', 1, 'Nessun datore di lavoro ha motivo di vedere il tuo conto.'),
('F8A8784D-4E36-419D-AC1D-E4B6F205C7E0', 'Cos''è il "PDF Exploit"?', 'multiple_choice', '["Un libro", "Un file PDF (es. Job Description) che contiene codice malevolo", "Un lavoro", "Una tassa"]', 1, 'Anche i documenti apparentemente innocui possono essere armi.'),
('F8A8784D-4E36-419D-AC1D-E4B6F205C7E0', 'Come verificare se l''azienda esiste?', 'multiple_choice', '["Fidarsi", "Cercare su LinkedIn i dipendenti, il sito web, la partita IVA", "Chiedere alla mamma", "Guardare il logo"]', 1, 'Le aziende fantasma non hanno una "storia" digitale coerente.'),
('F8A8784D-4E36-419D-AC1D-E4B6F205C7E0', 'Se usano mail generiche (gmail/yahoo)?', 'multiple_choice', '["È normale", "Poco professionale e sospetto per grandi aziende", "Va bene", "È meglio"]', 1, 'HR di grandi aziende usano domini aziendali.');
