-- Mission Seed for Trentino Alto Adige (TN, BZ)
-- Generated by Antigravity
-- Theme: IoT, Smart Home & Wearable Security

-- 1. TRENTO (TN) - Smart Home & Domotica

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '8F4A3B2C-1D5E-4F6A-9B8C-7E6D5F4A3B2C', 'TN', 'Il Maggiordomo',
    'Hey Google, mi ascolti sempre? La privacy degli assistenti vocali.',
    E'# Assistenti Vocali\n\nDispositivi come Alexa e Google Home sono sempre in ascolto della "wake word" (parola di attivazione).\n\nA volte si attivano per errore e registrano conversazioni private che vengono inviate ai server per "migliorare il servizio".\n\nOgni tanto, entra nelle impostazioni e **cancella la cronologia delle registrazioni**.',
    'semplice', '5 min', 100, 'level_1', 'Trentino Alto Adige', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('8F4A3B2C-1D5E-4F6A-9B8C-7E6D5F4A3B2C', 'Quando un assistente vocale registra?', 'multiple_choice', '["Sempre, 24/7", "Solo dopo aver sentito la parola di attivazione (es. ''Hey Google'')", "Mai", "Solo di notte"]', 1, 'Ma ricorda: a volte capiscono male e registrano per sbaglio!'),
('8F4A3B2C-1D5E-4F6A-9B8C-7E6D5F4A3B2C', 'Dove finiscono le registrazioni vocali?', 'multiple_choice', '["Nel cestino", "Sui server dell''azienda (Cloud) per essere analizzate", "Sulla memoria del dispositivo locale", "Vengono cancellate subito"]', 1, 'Spesso vengono riascoltate da dipendenti umani o IA per migliorare il riconoscimento.'),
('8F4A3B2C-1D5E-4F6A-9B8C-7E6D5F4A3B2C', 'Cosa dovresti fare regolarmente con la cronologia vocale?', 'multiple_choice', '["Riascoltarla per ridere", "Cancellarla dalle impostazioni della privacy dell''account", "Condividerla su Facebook", "Stampare i testi"]', 1, 'Meno dati personali lasci sui server altrui, meglio è.'),
('8F4A3B2C-1D5E-4F6A-9B8C-7E6D5F4A3B2C', 'Come capire se il dispositivo sta ascoltando?', 'multiple_choice', '["Emette fumo", "Dovrebbe accendersi una luce LED o un''icona sullo schermo", "Vibra forte", "Diventa caldo"]', 1, 'Controlla sempre se il LED si accende da solo senza motivo.'),
('8F4A3B2C-1D5E-4F6A-9B8C-7E6D5F4A3B2C', 'Esiste un tasto "Mute" fisico sugli smart speaker?', 'multiple_choice', '["No, devi staccare la spina", "Sì, di solito disattiva elettricamente i microfoni", "È finto", "Solo sui modelli costosi"]', 1, 'Usalo quando vuoi privacy totale in casa.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '1A2B3C4D-5E6F-7A8B-9C0D-1E2F3A4B5C6D', 'TN', 'Occhi Indiscreti',
    'Chi guarda attraverso la tua telecamera di sicurezza?',
    E'# IP Cameras & Shodan\n\nInstalli una telecamera per sentirti sicuro, ma se non cambi la password di default, chiunque può entrarci.\n\nEsistono motori di ricerca (come Shodan) che scansionano internet alla ricerca di telecamere con password **admin / admin**.\nNon diventare un Grande Fratello per hacker.',
    'medio', '10 min', 200, 'level_2', 'Trentino Alto Adige', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('1A2B3C4D-5E6F-7A8B-9C0D-1E2F3A4B5C6D', 'Qual è l''errore più grave installando una IP Camera?', 'multiple_choice', '["Metterla storta", "Lasciare la password di default (admin/admin o 1234)", "Dimenticare di pulire l''obiettivo", "Puntarla verso il sole"]', 1, 'È la prima cosa che provano i bot automatici.'),
('1A2B3C4D-5E6F-7A8B-9C0D-1E2F3A4B5C6D', 'Cos''è Shodan?', 'multiple_choice', '["Un videogioco", "Un motore di ricerca per dispositivi connessi a Internet (IoT)", "Una marca di telecamere", "Un antivirus"]', 1, 'Permette di trovare migliaia di telecamere non protette in tutto il mondo.'),
('1A2B3C4D-5E6F-7A8B-9C0D-1E2F3A4B5C6D', 'Come proteggere il Baby Monitor?', 'multiple_choice', '["Coprilo con una coperta", "Aggiorna il firmware e imposta una password forte WPA2/WPA3", "Non usarlo", "Parla a bassa voce"]', 1, 'I baby monitor sono spesso i dispositivi meno sicuri della casa.'),
('1A2B3C4D-5E6F-7A8B-9C0D-1E2F3A4B5C6D', 'Cosa indica il bollino "CE" sulla scatola?', 'multiple_choice', '["Certifica la sicurezza informatica", "Conformità Europea (standard di sicurezza fisica/elettrica), non garantisce nulla sul software", "Cina Export", "Comunità Esterna"]', 1, 'Non fidarti ciecamente dei marchi economici solo per il bollino CE.'),
('1A2B3C4D-5E6F-7A8B-9C0D-1E2F3A4B5C6D', 'Se la telecamera inizia a ruotare da sola?', 'multiple_choice', '["È posseduta", "Potrebbe essere stata compromessa da remoto, staccala subito!", "Sta facendo stretching", "È normale manutenzione"]', 1, 'Sintomo classico di intrusione remota.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '9B8C7D6E-5F4A-3B2C-1D0E-9F8E7D6C5B4A', 'TN', 'La Rete Ospiti',
    'Perché il frigo smart non deve parlare con il tuo PC.',
    E'# Network Segregation\n\nI dispositivi IoT (lampadine, frigo, TV) sono spesso poco sicuri e non vengono aggiornati.\nSe un hacker entra nella lampadina, può saltare sul tuo PC e rubare i dati bancari?\n\nSì, se sono sulla stessa rete.\nSoluzione: Usa la **Rete Ospiti (Guest Network)** del router per tutti i dispositivi smart.',
    'difficile', '15 min', 500, 'level_3', 'Trentino Alto Adige', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('9B8C7D6E-5F4A-3B2C-1D0E-9F8E7D6C5B4A', 'Cos''è il "Lateral Movement"?', 'multiple_choice', '["Muoversi di lato ballando", "Quando un attaccante passa da un dispositivo compromesso (es. termostato) a un altro più importante nella stessa rete", "Spostare il router", "Un errore del WiFi"]', 1, 'È la tecnica standard per attaccare le reti domestiche e aziendali.'),
('9B8C7D6E-5F4A-3B2C-1D0E-9F8E7D6C5B4A', 'A cosa serve la "Guest Network" del router?', 'multiple_choice', '["Per gli ospiti umani", "Crea una rete WiFi separata che dà accesso a Internet ma isola i dispositivi dalla rete principale", "È più veloce", "È gratis"]', 1, 'Isolamento è la parola chiave.'),
('9B8C7D6E-5F4A-3B2C-1D0E-9F8E7D6C5B4A', 'Quante reti WiFi dovresti avere idealmente a casa?', 'multiple_choice', '["Una", "Almeno due: una Principale (PC, Smartphone, Banking) e una IoT/Ospiti (TV, Lampadine, Alexa)", "Cento", "Nessuna, meglio il cavo"]', 1, 'Segmentare riduce il rischio.'),
('9B8C7D6E-5F4A-3B2C-1D0E-9F8E7D6C5B4A', 'Se il produttore della lampadina smette di rilasciare aggiornamenti?', 'multiple_choice', '["La lampadina esplode", "Diventa vulnerabile per sempre. Se isolata nella Guest Network, il rischio è contenuto", "Non funziona più", "Cambia colore"]', 1, 'L''IoT ha una vita supportata molto breve, la sicurezza decade presto.'),
('9B8C7D6E-5F4A-3B2C-1D0E-9F8E7D6C5B4A', 'WPA2 o WPA3?', 'multiple_choice', '["WEP", "WPA3 è il nuovo standard più sicuro, usalo se i dispositivi lo supportano", "Uguale", "Nessuna password"]', 1, 'WEP è obsoleto da decenni, WPA2 è ok, WPA3 è il top.');


-- 2. BOLZANO (BZ) - Wearables & Mobile Security

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '5A4B3C2D-1E0F-9A8B-7C6D-5E4F3A2B1C0D', 'BZ', 'Tracce in Montagna',
    'Dimmi dove corri e ti dirò chi sei (e dove abiti).',
    E'# Fitness Tracker Privacy\n\nApp come Strava o Garmin registrano i tuoi percorsi GPS.\nSe rendi il profilo pubblico, chiunque può vedere dove inizi e finisci la corsa (casa tua!).\n\nAttiva le "Privacy Zones" per nascondere l''inizio/fine dei tracciati vicino a casa o al lavoro.',
    'semplice', '5 min', 100, 'level_1', 'Trentino Alto Adige', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('5A4B3C2D-1E0F-9A8B-7C6D-5E4F3A2B1C0D', 'Cosa sono le "Heatmaps" delle app di fitness?', 'multiple_choice', '["Mappe del meteo", "Mappe che mostrano i percorsi più frequentati dagli utenti, rivelando involontariamente basi militari o case private", "Mappe termiche del corpo", "Mappe dei ristoranti"]', 1, 'Hanno svelato posizioni di basi segrete in passato.'),
('5A4B3C2D-1E0F-9A8B-7C6D-5E4F3A2B1C0D', 'Come proteggere la tua posizione di casa?', 'multiple_choice', '["Correre velocissimo", "Impostare una ''Privacy Zone'' o raggio di oscuramento attorno al proprio indirizzo nell''app", "Non correre", "Mentire sul nome"]', 1, 'Così il tracciato appare solo quando sei lontano da casa.'),
('5A4B3C2D-1E0F-9A8B-7C6D-5E4F3A2B1C0D', 'È sicuro condividere le mappe delle corse sui social?', 'multiple_choice', '["Sì, per vantarsi", "No, stai dicendo ai ladri ''non sono in casa ora'' e stai mostrando le tue abitudini orarie", "Dipende dai km", "Solo se vinci"]', 1, 'Attenzione a creare pattern prevedibili.'),
('5A4B3C2D-1E0F-9A8B-7C6D-5E4F3A2B1C0D', 'I dati biometrici (battito cardiaco) sono sensibili?', 'multiple_choice', '["No", "Sì, sono dati sanitari molto personali che le aziende potrebbero vendere alle assicurazioni", "Solo se sei malato", "Poco importanti"]', 1, 'I dati sanitari valgono molto sul mercato.'),
('5A4B3C2D-1E0F-9A8B-7C6D-5E4F3A2B1C0D', 'Se vendi il tuo vecchio Smartwatch?', 'multiple_choice', '["Vendilo così com''è", "Fai un Factory Reset (ripristino dati di fabbrica) per cancellare tutti i tuoi dati e account", "Lavalo", "Regalalo"]', 1, 'Contiene email, messaggi e dati GPS.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '7C6D5E4F-3A2B-1C0D-9E8F-7A6B5C4D3E2F', 'BZ', 'Bluetooth Trekking',
    'Lasciare il Bluetooth acceso è come lasciare la porta accostata.',
    E'# Bluetooth Vulnerabilities\n\nIl Bluetooth è comodo ma vulnerabile.\nSe lo lasci sempre attivo e "visibile", gli hacker possono tentare il **Bluebugging** (prendere controllo del telefono) o inviarti file malevoli.\n\nSpegni il Bluetooth quando non lo usi, o almeno rendilo "non visibile".',
    'medio', '10 min', 200, 'level_2', 'Trentino Alto Adige', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('7C6D5E4F-3A2B-1C0D-9E8F-7A6B5C4D3E2F', 'Cos''è il Bluebugging?', 'multiple_choice', '["Un insetto blu", "Una tecnica per accedere al telefono via Bluetooth e ascoltare chiamate o leggere messaggi", "Un colore", "Un ballo"]', 1, 'Richiede che il BT sia acceso e il dispositivo vulnerabile/accoppiato.'),
('7C6D5E4F-3A2B-1C0D-9E8F-7A6B5C4D3E2F', 'Cosa fare se ti arriva una richiesta di accoppiamento sconosciuta?', 'multiple_choice', '["Accettare per curiosità", "Rifiutare immediatamente e spegnere il Bluetooth", "Chiedere chi è", "Non fare nulla"]', 1, 'Potrebbe essere un tentativo di intrusione.'),
('7C6D5E4F-3A2B-1C0D-9E8F-7A6B5C4D3E2F', 'È sicuro usare il Bluetooth in luoghi affollati (es. metro)?', 'multiple_choice', '["Sì, sempre", "Aumenta il rischio perché l''attaccante deve essere nel raggio di 10 metri", "Solo con le cuffie", "No"]', 1, 'La vicinanza fisica è necessaria per gli attacchi Bluetooth.'),
('7C6D5E4F-3A2B-1C0D-9E8F-7A6B5C4D3E2F', 'Cos''è AirDrop (Apple) in termini di sicurezza?', 'multiple_choice', '["Un paracadute", "Usa Bluetooth/WiFi. Se impostato su ''Tutti'', chiunque può inviarti foto indesiderate (Cyberflashing)", "Una caramella", "Un aereo"]', 1, 'Impostalo sempre su "Solo Contatti" o "Ricezione non attiva".'),
('7C6D5E4F-3A2B-1C0D-9E8F-7A6B5C4D3E2F', 'Il Bluetooth consuma batteria?', 'multiple_choice', '["Tantissimo", "Poco (BLE), ma spegnerlo aumenta sicurezza e durata batteria", "Nulla", "Ricarica il telefono"]', 1, 'Doppio vantaggio: sicurezza e autonomia.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '3E2F1A0B-9C8D-7E6F-5A4B-3C2D1E0F9A8B', 'BZ', 'Juice Jacking',
    'Quella colonnina di ricarica gratuita ha fame dei tuoi dati.',
    E'# Juice Jacking\n\nIl cavo USB trasmette sia elettricità che **dati**.\nLe colonnine pubbliche (aeroporti, stazioni) potrebbero essere manomesse per copiare i dati dal tuo telefono mentre lo carichi.\n\nUsa il tuo caricatore da muro, un powerbank personale, o un cavo "Solo Carica" (Data Blocker).',
    'difficile', '15 min', 500, 'level_3', 'Trentino Alto Adige', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('3E2F1A0B-9C8D-7E6F-5A4B-3C2D1E0F9A8B', 'Cos''è un "USB Data Blocker" (o preservativo USB)?', 'multiple_choice', '["Un antivirus", "Un adattatore che disabilita i pin dei dati nel cavo USB, facendo passare solo la corrente", "Un tappo", "Un cavo rotto"]', 1, 'Costa pochi euro e ti salva i dati.'),
('3E2F1A0B-9C8D-7E6F-5A4B-3C2D1E0F9A8B', 'Cosa succede se colleghi il telefono a una porta USB sconosciuta?', 'multiple_choice', '["Si ricarica più veloce", "Potrebbe aprirsi un prompt ''Vuoi dare accesso ai dati?'' (da rifiutare) o partire un attacco silenzioso", "Niente", "Esplode"]', 1, 'Non fidarti mai di porte USB che non controlli.'),
('3E2F1A0B-9C8D-7E6F-5A4B-3C2D1E0F9A8B', 'Qual è l''alternativa più sicura alla colonnina USB?', 'multiple_choice', '["Non ricaricare", "Usare la propria presa di corrente (il cubotto) nella presa elettrica normale (220V)", "Chiedere a uno sconosciuto", "Usare un pc altrui"]', 1, 'La presa di corrente non trasmette dati, solo elettroni!'),
('3E2F1A0B-9C8D-7E6F-5A4B-3C2D1E0F9A8B', 'Il "Debug USB" su Android aumenta il rischio?', 'multiple_choice', '["Sì, se attivo facilita l''accesso profondo al sistema tramite cavo", "No", "Solo per gli sviluppatori", "Migliora la grafica"]', 1, 'Tienilo disattivato se non sei uno sviluppatore che sta lavorando.'),
('3E2F1A0B-9C8D-7E6F-5A4B-3C2D1E0F9A8B', 'Questa minaccia vale anche per i laptop?', 'multiple_choice', '["No, solo telefoni", "Sì, qualsiasi dispositivo con porta dati può essere attaccato", "Solo Windows", "Solo Mac"]', 1, 'Qualsiasi dispositivo che accetta dati via cavo è potenzialmente a rischio.');
