-- Mission Seed for Veneto Part 3 (RO, BL)
-- Generated by Antigravity
-- Theme: Social Engineering & Human Hacking

-- 6. ROVIGO (RO) - Deepfakes & AI Threats ("Realtà Sintetica")

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    -- OLD INVALID: 123ABCDE-F4G5-4293-0123-456789012DEF (G is bad)
    '123ABCDE-F4A5-4293-0123-456789012DEF', 'RO', 'Volti Inesistenti',
    'Riesci a distinguere una persona vera da una generata dall''IA?',
    E'# Riconoscere i Deepfake Visivi\n\nL''IA generativa (GAN) crea volti fotorealistici.\nMa spesso lascia tracce:\n\n*   Orecchie diverse o malformate.\n*   Sfondo confuso o incoerente.\n*   Capelli che sfumano nel nulla.\n*   Denti troppo perfetti o troppi.\n\nGuarda i dettagli, non l''insieme.',
    'semplice', '5 min', 100, 'level_1', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('123ABCDE-F4A5-4293-0123-456789012DEF', 'Cos''è un Deepfake?', 'multiple_choice', '["Un lago profondo", "Un contenuto multimediale (video/audio/foto) manipolato o generato dall''IA per sembrare reale", "Un errore", "Una maschera"]', 1, 'Deep Learning + Fake.'),
('123ABCDE-F4A5-4293-0123-456789012DEF', 'Quale dettaglio tradisce spesso un volto generato da IA?', 'multiple_choice', '["Il colore degli occhi", "Asimmetrie negli occhiali, orecchie strane, o sfondi onirici/sfocati in modo innaturale", "Il naso", "La bocca"]', 1, 'L''IA fatica con la coerenza geometrica degli accessori.'),
('123ABCDE-F4A5-4293-0123-456789012DEF', 'A cosa servono i profili con volti generati da IA?', 'multiple_choice', '["Per bellezza", "Per creare account falsi (bot) credibili sui social per disinformazione o truffe", "Per i film", "Per gioco"]', 1, 'Siti come "ThisPersonDoesNotExist" sono usati massicciamente dai bot.'),
('123ABCDE-F4A5-4293-0123-456789012DEF', 'Il Deepfake è sempre illegale?', 'multiple_choice', '["Sì", "No, è una tecnologia (usata anche al cinema). Diventa illegale se usata per diffamazione, frode o revenge porn", "Solo in Italia", "Mai"]', 1, 'La tecnologia è neutra, l''uso no.'),
('123ABCDE-F4A5-4293-0123-456789012DEF', 'Possiamo fidarci ciecamente delle foto online?', 'multiple_choice', '["Sì, se sono HD", "No. L''era del \"se lo vedo ci credo\" è finita. Serve verifica della fonte", "Solo se a colori", "Sempre"]', 1, 'Dobbiamo reimparare a guardare.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    -- OLD INVALID: 234BCDEF-G5H6-4304-1234-567890123EFG (G, H are bad)
    '234BCDEF-A5B6-4304-1234-567890123EF0', 'RO', 'Voice Cloning',
    '"Ciao nonna, ho avuto un incidente, servono soldi subito."',
    E'# Audio Deepfakes\n\nBastano **3 secondi** di audio della tua voce (presi da un video su Instagram/TikTok) per clonarla perfettamente con l''IA.\n\nI truffatori chiamano i parenti fingendosi te in lacrime.\n"Ho perso il telefono, questo è un numero provvisorio, mandami un bonifico urgente."',
    'medio', '10 min', 200, 'level_2', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('234BCDEF-A5B6-4304-1234-567890123EF0', 'Quanto audio serve per clonare una voce oggi?', 'multiple_choice', '["Ore di registrazione", "Pochi secondi di audio pulito (facilmente reperibile dai social)", "Un mese", "Non si può"]', 1, 'La tecnologia VALL-E e simili hanno abbassato drasticamente la soglia.'),
('234BCDEF-A5B6-4304-1234-567890123EF0', 'Come difendersi dalla truffa del "finto nipote/figlio"?', 'multiple_choice', '["Non rispondere al telefono", "Stabilire una "Parola d''Ordine" segreta in famiglia da chiedere se la situazione è sospetta", "Urlare", "Cambiare numero"]', 1, 'Se l''interlocutore non sa la parola segreta, è un''IA (o un truffatore).'),
('234BCDEF-A5B6-4304-1234-567890123EF0', 'L''IA può replicare anche l''accento e le pause?', 'multiple_choice', '["No, parla come un robot", "Sì, replica intonazione, respiro e accento in modo spaventosamente realistico", "Solo in inglese", "A volte"]', 1, 'È indistinguibile al telefono, specialmente se la linea è disturbata.'),
('234BCDEF-A5B6-4304-1234-567890123EF0', 'Chi sono i bersagli preferiti?', 'multiple_choice', '["Hacker", "Anziani o genitori preoccupati, sfruttando l''emotività", "Bambini", "Robot"]', 1, 'Si sfrutta l''istinto di protezione familiare.'),
('234BCDEF-A5B6-4304-1234-567890123EF0', 'Se ricevi un messaggio vocale sospetto su WhatsApp?', 'multiple_choice', '["Mi fido", "Provo a richiamare il numero originale della persona per verificare", "Lo inoltro", "Rispondo"]', 1, 'Verifica sempre sul canale sicuro.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    -- OLD INVALID: 345CDEFG-H6I7-4415-2345-678901234FGH (G, H, I, J.. are bad)
    '345CDEFA-16B7-4415-2345-678901234F1A', 'RO', 'Video Call Fake',
    'La persona in videochiamata è davvero chi dice di essere?',
    E'# Real-time Deepfake\n\nNon è fantascienza. Gli hacker possono sovrapporre un volto falso al proprio in tempo reale durante una videochiamata (Zoom, Teams).\n\nÈ successo a una multinazionale a Hong Kong: un dipendente ha fatto un bonifico di 25 milioni perché "il CFO in videochiamata" glielo ha ordinato. Erano tutti deepfake.',
    'difficile', '15 min', 500, 'level_3', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('345CDEFA-16B7-4415-2345-678901234F1A', 'È possibile fare deepfake in diretta video?', 'multiple_choice', '["No, serve troppo tempo per il rendering", "Sì, con PC potenti la sostituzione del volto avviene in tempo reale con latenza minima", "Solo nei film", "Solo su TikTok"]', 1, 'La potenza di calcolo moderna lo rende accessibile.'),
('345CDEFA-16B7-4415-2345-678901234F1A', 'Come smascherare un video deepfake in diretta?', 'multiple_choice', '["Chiedere di girare la testa di profilo o passare una mano davanti al volto", "Guardare i vestiti", "Chiedere l''ora", "Salutare"]', 1, 'Il deepfake spesso "sgancia" (glitch) quando il volto è di profilo o occluso da un oggetto.'),
('345CDEFA-16B7-4415-2345-678901234F1A', 'Cosa insegna il caso del CFO di Hong Kong?', 'multiple_choice', '["Che i bonifici sono lenti", "Che nemmeno \"vederlo in faccia\" è più una prova d''identità sufficiente per transazioni critiche", "Che bisogna usare Zoom", "Niente"]', 1, 'Le procedure di sicurezza devono evolvere oltre la verifica visiva.'),
('345CDEFA-16B7-4415-2345-678901234F1A', 'Le difese biometriche (FaceID) possono essere ingannate?', 'multiple_choice', '["Mai", "Sì, con tecniche avanzate, ma è difficile grazie ai sensori di profondità (Lidar/IR)", "Sempre", "Facilmente"]', 1, 'Per questo il FaceID usa sensori 3D e non solo la fotocamera.'),
('345CDEFA-16B7-4415-2345-678901234F1A', 'Il concetto di "Zero Trust" si applica qui?', 'multiple_choice', '["No", "Sì: \"Never Trust, Always Verify\". Non fidarti mai dell''identità percepita senza verifica crittografica o procedurale", "Forse", "Boh"]', 1, 'Fidarsi è bene, verificare è meglio.');


-- 7. BELLUNO (BL) - Sicurezza Fisica & Tailgating ("La Porta Aperta")

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    -- OLD INVALID: 456DEFGH-I7J8-4293-0123-456789012GHI (G, H, I, J.. are bad)
    '456DEFA1-B7C8-4293-0123-456789012C12', 'BL', 'Tienimi la Porta',
    'Essere gentili può costare caro all''azienda.',
    E'# Tailgating (o Piggybacking)\n\nArrivi al tornello aziendale, badge alla mano.\nQualcuno dietro di te, con le mani occupate da caffè e scatoloni, sorride: "Scusa, mi tieni la porta? Ho dimenticato il badge".\n\nTu, gentile, apri.\nComplimenti, hai appena fatto entrare un intruso senza controlli.',
    'semplice', '5 min', 100, 'level_1', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('456DEFA1-B7C8-4293-0123-456789012C12', 'Cos''è il Tailgating?', 'multiple_choice', '["Guidare attaccati all''auto davanti", "Accodarsi a una persona autorizzata per entrare in un''area riservata senza badge", "Una festa", "Aprire le porte"]', 1, 'Sfrutta la cortesia sociale per violare la sicurezza fisica.'),
('456DEFA1-B7C8-4293-0123-456789012C12', 'Cosa fare se qualcuno chiede di entrare senza badge?', 'multiple_choice', '["Farlo entrare se è ben vestito", "Indirizzarlo cortesemente alla Reception o alla Security per la procedura ospiti", "Insultarlo", "Correre via"]', 1, 'La sicurezza non ammette eccezioni per "gentilezza".'),
('456DEFA1-B7C8-4293-0123-456789012C12', 'Se è un collega che conosci ma senza badge?', 'multiple_choice', '["Entra pure", "Dovrebbe comunque passare dalla reception per farsi rilasciare un badge provvisorio (audit trail)", "Non importa", "Gli presto il mio"]', 1, 'Ogni ingresso deve essere registrato.'),
('456DEFA1-B7C8-4293-0123-456789012C12', 'I fattorini/corrieri sono esenti?', 'multiple_choice', '["Sì, hanno fretta", "No, spesso i truffatori si travestono da corrieri/tecnici proprio per sfruttare l''urgenza", "Solo se hanno la divisa", "Sempre"]', 1, 'L''abito non fa il monaco... e nemmeno il dipendente.'),
('456DEFA1-B7C8-4293-0123-456789012C12', 'Perché è grave?', 'multiple_choice', '["Non è grave", "Una volta dentro, l''intruso ha accesso fisico a server, documenti, PC sbloccati", "Si sporca il pavimento", "Fa freddo"]', 1, 'L''accesso fisico bypassa quasi tutti i firewall.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    -- OLD INVALID: 567EFGHI-J8K9-4304-1234-567890123HIJ (G, H, I, J.. are bad)
    '567EFAB1-C8D9-4304-1234-567890123D23', 'BL', 'Spione alle Spalle',
    'Non serve hackerare una password se puoi leggerla mentre la scrivono.',
    E'# Shoulder Surfing\n\nSei in treno, in aereo o al bar e lavori al PC.\nChi c''è dietro di te?\n\nBasta uno sguardo veloce o una foto col cellulare mentre digiti la password o leggi un documento riservato.\n\nUsa sempre un **Filtro Privacy** sullo schermo quando viaggi.',
    'medio', '10 min', 200, 'level_2', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('567EFAB1-C8D9-4304-1234-567890123D23', 'A cosa serve un "Privacy Screen Filter"?', 'multiple_choice', '["A proteggere dalla polvere", "A oscurare lo schermo per chi guarda dai lati, rendendolo leggibile solo frontalmente", "A fare ombra", "A nulla"]', 1, 'Accessorio fondamentale per chi viaggia.'),
('567EFAB1-C8D9-4304-1234-567890123D23', 'Dove avviene più spesso il Shoulder Surfing?', 'multiple_choice', '["In cantina", "Luoghi affollati: mezzi pubblici, bar, code agli sportelli bancomat", "Nel deserto", "A casa"]', 1, 'Dove c''è folla e distrazione.'),
('567EFAB1-C8D9-4304-1234-567890123D23', 'Basta guardare le dita sulla tastiera?', 'multiple_choice', '["No", "Sì, un osservatore esperto può ricostruire la password o il PIN solo osservando il movimento delle dita", "Impossibile", "Solo se sono lente"]', 1, 'Vale per tastiere fisiche e touchscreen.'),
('567EFAB1-C8D9-4304-1234-567890123D23', 'È sicuro fare call riservate in treno?', 'multiple_choice', '["Sì, parlando piano", "No. Chiunque vicino a te può ascoltare informazioni confidenziali (Eavesdropping)", "Solo in prima classe", "Con le cuffie sì"]', 1, 'Le cuffie proteggono quello che senti tu, non quello che dici!'),
('567EFAB1-C8D9-4304-1234-567890123D23', 'Bloccare lo schermo quando ci si alza?', 'multiple_choice', '["Solo se si sta via tanto", "Sempre (Win+L o Cmd+Ctrl+Q), anche per andare a prendere un caffè o in bagno", "Mai", "È maleducato"]', 1, 'Un PC sbloccato è un invito a nozze.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    -- OLD INVALID: 678FGHIJ-K9L0-4415-2345-678901234IJK (G, H, I, J.. are bad)
    '678FAB12-C9D0-4415-2345-6789012341AB', 'BL', 'Scrivanie Pulite',
    'Quel post-it giallo sul monitor è un regalo per gli hacker.',
    E'# Clean Desk Policy\n\nAlla fine della giornata, la tua scrivania deve essere vuota.\n\n*   Nessun documento cartaceo sensibile in vista.\n*   Nessun post-it con password ("Pippo123").\n*   Nessuna chiavetta USB incustodita.\n\nLe pulizie passano, i visitatori passano... i dati spariscono.',
    'difficile', '15 min', 500, 'level_3', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('678FAB12-C9D0-4415-2345-6789012341AB', 'Cosa significa "Clean Desk Policy"?', 'multiple_choice', '["Pulire con lo spray", "Politica aziendale che impone di rimuovere documenti sensibili e supporti dalla scrivania quando non si è al posto", "Avere scrivanie di vetro", "Non lavorare"]', 1, 'Riduce il rischio di furto di informazioni visivo.'),
('678FAB12-C9D0-4415-2345-6789012341AB', 'Dove buttare i documenti sensibili?', 'multiple_choice', '["Nel cestino normale", "Nel tritadocumenti (Shredder) o negli appositi contenitori di sicurezza", "Dalla finestra", "Farne aeroplanini"]', 1, 'Il "Dumpster Diving" (frugare nella spazzatura) è una tecnica reale.'),
('678FAB12-C9D0-4415-2345-6789012341AB', 'Perché le lavagne bianche sono pericolose?', 'multiple_choice', '["Puzzano di pennarello", "Spesso rimangono schemi di rete, password o progetti segreti disegnati sopra dopo le riunioni", "Sono brutte", "Cadono"]', 1, 'Cancella sempre la lavagna dopo la riunione.'),
('678FAB12-C9D0-4415-2345-6789012341AB', 'Scrivere la password sotto la tastiera è sicuro?', 'multiple_choice', '["Sì, nessuno guarda lì", "No. È il primo posto (insieme al post-it sul monitor) dove un attaccante guarda", "Geniale", "Solo a matita"]', 1, 'Usa un Password Manager, non i post-it.'),
('678FAB12-C9D0-4415-2345-6789012341AB', 'Le stampanti comuni sono a rischio?', 'multiple_choice', '["No", "Sì, se stampi e dimentichi il foglio lì, chiunque può leggerlo", "Stampano solo", "Non funzionano mai"]', 1, 'Ritira subito le tue stampe "Follow-me printing".');
