-- Mission Seed for Valle d'Aosta (Region: Valle d'Aosta, Province: AO)
-- Generated by Antigravity

-- 1. AOSTA (AO) - L'Equipaggiamento Digitale

-- Mission 1: Semplice (C0D30001-VDA1-0010-0000-000000000001)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '83B28DD2-0170-4015-A5BE-A41F7A188494', 'AO', 'Lo Zaino Sicuro',
    'Prima di partire, devi assicurarti che le tue cose siano al sicuro. I Backup.',
    E'# Mai partire senza zaino\n\nIn montagna, se perdi lo zaino, sei nei guai. Nel digitale è lo stesso.\n\nNon fidarti del tuo dispositivo: può rompersi, essere rubato o perso.\n\nLa regola d''oro è **3-2-1**:\n*   **3** copie dei dati\n*   **2** supporti diversi (es. Hard Disk + Cloud)\n*   **1** copia off-site (lontano da casa/ufficio)',
    'semplice', '5 min', 100, 'level_1', 'Valle d''Aosta', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('83B28DD2-0170-4015-A5BE-A41F7A188494', 'Cos''è un Backup?', 'multiple_choice', '["Un''app per camminare all''indietro", "Una copia di sicurezza dei dati salvata su un supporto diverso dall''originale", "Un antivirus", "Una password"]', 1, 'Se hai una sola copia del file (anche se sul cloud), non è un backup, è l''originale.'),
('83B28DD2-0170-4015-A5BE-A41F7A188494', 'La sincronizzazione (es. iCloud/Google Drive) è un backup?', 'multiple_choice', '["Sì, sempre", "No, perché se cancelli un file sul telefono si cancella anche sul cloud", "Solo se paghi", "Dipende dal meteo"]', 1, 'La sincronizzazione serve a lavorare ovunque, il backup serve a tornare indietro nel tempo se sbagli.'),
('83B28DD2-0170-4015-A5BE-A41F7A188494', 'Cos''è la regola 3-2-1?', 'multiple_choice', '["Un conto alla rovescia", "3 copie, 2 media diversi, 1 copia fuori sede", "3 password, 2 account, 1 computer", "Una tattica di calcio"]', 1, 'Lo standard dell''industria per non perdere mai nulla.'),
('83B28DD2-0170-4015-A5BE-A41F7A188494', 'Ogni quanto dovresti fare il backup?', 'multiple_choice', '["Mai", "Dipende da quanti dati sei disposto a perdere (RPO)", "Ogni anno bisestile", "Solo a Natale"]', 1, 'Se fai il backup una volta al mese, sei disposto a perdere un mese di lavoro/foto.'),
('83B28DD2-0170-4015-A5BE-A41F7A188494', 'Qual è il rischio di avere solo una copia dei dati?', 'multiple_choice', '["Nessuno", "Perdita totale in caso di furto, rottura o ransomware", "Il computer diventa lento", "Ti rubano la sedia"]', 1, 'I dati non esistono finché non sono in almeno due posti diversi.');


-- Mission 2: Medio (C0D30002-VDA2-0020-0000-000000000002)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '9E316BFA-7038-484C-A5A7-13AE9A794709', 'AO', 'Sentieri Tracciati',
    'Riconoscere i segnavia corretti ed evitare le scorciatoie pericolose (Phishing).',
    E'# Segui i segnavia\n\nIn internet, come nel trekking, uscire dal sentiero tracciato è pericoloso.\n\nIl **Phishing** è come un cartello falso che ti indica un burrone.\nDevi imparare a leggere la "mappa" (l''URL) per capire dove sei veramente.',
    'medio', '10 min', 200, 'level_2', 'Valle d''Aosta', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('9E316BFA-7038-484C-A5A7-13AE9A794709', 'Cosa indica il lucchetto vicino all''URL (HTTPS)?', 'multiple_choice', '["Che il sito è sicuro al 100%", "Che la connessione tra te e il sito è criptata (ma il sito potrebbe essere truffaldino)", "Che il sito è chiuso", "Che non puoi entrare"]', 1, 'HTTPS protegge il viaggio dei dati, ma non garantisce che la destinazione sia onesta.'),
('9E316BFA-7038-484C-A5A7-13AE9A794709', 'Cos''è il Typosquatting?', 'multiple_choice', '["Un esercizio ginnico", "Registrare domini simili a quelli famosi (es. gogle.com) sperando in errori di digitazione", "Un tipo di virus", "Occupare case abusive"]', 1, 'Basta una lettera sbagliata per finire su un sito clone.'),
('9E316BFA-7038-484C-A5A7-13AE9A794709', 'Cosa fare se ricevi una mail urgente dalla "banca"?', 'multiple_choice', '["Cliccare subito", "Controllare attentamente il mittente reale e non cliccare link, ma andare sul sito ufficiale", "Rispondere con i dati", "Piangere"]', 1, 'L''urgenza è la bandiera rossa numero uno del phishing.'),
('9E316BFA-7038-484C-A5A7-13AE9A794709', 'In "banca.supporto-sicurezza.com", qual è il vero dominio?', 'multiple_choice', '["banca.com", "supporto-sicurezza.com", "sicurezza.com", "com"]', 1, 'Si legge da destra a sinistra (prima del .com). Qui sei su "supporto-sicurezza", NON sulla banca.'),
('9E316BFA-7038-484C-A5A7-13AE9A794709', 'Perché gli URL accorciati (bit.ly) sono rischiosi?', 'multiple_choice', '["Sono brutti", "Nascondono la destinazione reale", "Non funzionano", "Sono a pagamento"]', 1, 'Se non vedi dove vai, non cliccare (o usa un tool per espanderli).');


-- Mission 3: Difficile (C0D30003-VDA3-0030-0000-000000000003)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'BA21DE82-8AE0-40EF-B2E5-33EFDA7E9857', 'AO', 'Kit di Sopravvivenza',
    'Gli strumenti vitali che ti salvano la vita: Password Manager & 2FA.',
    E'# Il tuo Kit da Ferrata\n\nNon scaleresti il Cervino in infradito.\n\nPer proteggere i tuoi account servono due moschettoni:\n1.  **Password Manager**: Per non usare mai la stessa password.\n2.  **2FA (Autenticazione a due fattori)**: La tua assicurazione sulla vita digitale.',
    'difficile', '15 min', 500, 'level_3', 'Valle d''Aosta', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('BA21DE82-8AE0-40EF-B2E5-33EFDA7E9857', 'Perché riutilizzare la stessa password è pericoloso?', 'multiple_choice', '["Ti confondi", "Credential Stuffing: se un sito viene bucato, gli hacker provano quella password su tutti gli altri tuoi account", "È illegale", "Porta sfortuna"]', 1, 'È la causa principale dei furti d''identità massivi.'),
('BA21DE82-8AE0-40EF-B2E5-33EFDA7E9857', 'Cos''è un Password Manager?', 'multiple_choice', '["Un segretario", "Una cassaforte cifrata che ricorda le password complesse al posto tuo", "Un foglio Excel", "Un post-it"]', 1, 'L''unico modo per avere password uniche e forti (es. "Xy9#mP2!qL") ovunque.'),
('BA21DE82-8AE0-40EF-B2E5-33EFDA7E9857', 'Qual è la forma migliore di 2FA (Autenticazione a due fattori)?', 'multiple_choice', '["SMS", "App Authenticator (o Chiave Hardware)", "Domanda segreta", "Nessuna"]', 1, 'Gli SMS sono vulnerabili al SIM Swapping (clonazione della SIM).'),
('BA21DE82-8AE0-40EF-B2E5-33EFDA7E9857', 'Cos''è il "Salt" in crittografia?', 'multiple_choice', '["Sale da cucina", "Dati casuali aggiunti alla password prima dell''hashing per proteggerla", "Un virus", "Un linguaggio"]', 1, 'Rende inutili le "Rainbow Tables" (tabelle pre-calcolate per decifrare password).'),
('BA21DE82-8AE0-40EF-B2E5-33EFDA7E9857', 'Se usi un Password Manager, quante password devi ricordare?', 'multiple_choice', '["Tutte", "Mille", "Una sola (Master Password), ma deve essere fortissima", "Zero"]', 2, 'Proteggi quella e proteggi tutto (e attiva la 2FA sul manager!).');
