-- Mission Seed for Lombardia Part 2b (CR, LO, MN)
-- Generated by Antigravity

-- 10. CREMONA (CR) - Vishing (Voice Phishing)

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '66E1BED5-5FA7-4639-A86A-D6BD1FCA9BA9', 'CR', 'L''Operatore Inquietante',
    'Ti chiamano dalla banca: "Tentativo di frode in corso". Che fai?',
    E'# "La sua carta è stata clonata"\n\nRicevi una chiamata. È l''ufficio sicurezza della banca.\nTi dicono che qualcuno sta spendendo i tuoi soldi a Dubai.\n\nPer bloccare tutto, devi comunicare subito il codice di sicurezza ricevuto via SMS.\n**Se glielo dai, hai appena autorizzato TU la truffa.**',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('66E1BED5-5FA7-4639-A86A-D6BD1FCA9BA9', 'La banca ti chiama mai chiedendo password o PIN?', 'multiple_choice', '["Sì, per sicurezza", "Mai. È la regola numero uno. Se ti chiamano chiedendo codici, è una truffa", "Solo se sono gentili", "Solo di domenica"]', 1, 'Hanno già accesso ai sistemi, non hanno bisogno dei tuoi codici.'),
('66E1BED5-5FA7-4639-A86A-D6BD1FCA9BA9', 'Cos''è il Vishing?', 'multiple_choice', '["Pescare", "Voice Phishing: truffe fatte tramite chiamate vocali per rubare dati", "Un pesce", "Cantare"]', 1, 'Usano la voce per creare urgenza e fiducia.'),
('66E1BED5-5FA7-4639-A86A-D6BD1FCA9BA9', 'Cosa fare se ricevi una chiamata allarmante dalla banca?', 'multiple_choice', '["Dare il codice", "Riagganciare subito e chiamare il numero verde ufficiale (sul retro della carta) per verificare", "Piangere", "Urlare"]', 1, 'Non fidarti mai della chiamata in entrata.'),
('66E1BED5-5FA7-4639-A86A-D6BD1FCA9BA9', 'Perché ti chiedono il codice SMS (OTP)?', 'multiple_choice', '["Per disattivare la carta", "Perché stanno provando a fare un bonifico dal tuo conto e serve quel codice per autorizzarlo", "Per gioco", "Per salutarti"]', 1, 'Tu pensi di bloccare, in realtà stai firmando il furto.'),
('66E1BED5-5FA7-4639-A86A-D6BD1FCA9BA9', 'Se l''operatore si arrabbia e minaccia di bloccare i conti?', 'multiple_choice', '["Obbedisco", "È un trucco psicologico per farti agire d''istinto senza ragionare", "Chiedo scusa", "Lo denuncio"]', 1, 'Un vero operatore bancario è un professionista calmo, non ti minaccia.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '3E6E4006-C8B7-4711-B839-C4D9F6C2C5C4', 'CR', 'Numero Spoofato',
    'Chiamata dal "Numero Verde Ufficiale". Posso fidarmi?',
    E'# Caller ID Spoofing\n\nGuardi il telefono: "Banca Intesa" o "Poste Italiane". Il numero è quello vero!\n\nPurtroppo, è facilissimo per gli hacker falsificare il numero che appare sul tuo display.\n**Il numero che vedi NON garantisce chi ti sta chiamando.**',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('3E6E4006-C8B7-4711-B839-C4D9F6C2C5C4', 'È possibile falsificare il numero di telefono del mittente?', 'multiple_choice', '["No, è impossibile", "Sì, si chiama Spoofing ed è molto comune", "Solo nei film", "Solo la polizia può"]', 1, 'La rete telefonica globale non autentica il mittente in modo sicuro.'),
('3E6E4006-C8B7-4711-B839-C4D9F6C2C5C4', 'Se il numero corrisponde a quello salvato in rubrica?', 'multiple_choice', '["È sicuro", "Potrebbe essere spoofato. Se la richiesta è strana (soldi/codici), riaggancia e richiama tu", "Rispondi", "Saluta"]', 1, 'Se richiami tu, la chiamata viene instradata verso il vero proprietario del numero.'),
('3E6E4006-C8B7-4711-B839-C4D9F6C2C5C4', 'Cosa dicono per tenerti al telefono?', 'multiple_choice', '["Niente", "Ti tengono occupato per non farti chiamare la vera banca o consultarti con qualcuno", "Barzellette", "Musica"]', 1, 'Vogliono monopolizzare la tua attenzione.'),
('3E6E4006-C8B7-4711-B839-C4D9F6C2C5C4', 'Se ti chiedono di installare un''app "Antivirus" o "Supporto"?', 'multiple_choice', '["La installo", "Mai. È un software di controllo remoto (RAT) per rubarti tutto", "Solo se è gratis", "Solo se è bella"]', 1, 'Ti fanno installare TeamViewer/AnyDesk per svuotare il conto mentre guardi.'),
('3E6E4006-C8B7-4711-B839-C4D9F6C2C5C4', 'Le chiamate mute sono pericolose?', 'multiple_choice', '["Sì", "No, sono solo fastidiose (spesso robocall per verificare se il numero è attivo)", "Esplode il telefono", "Ti rubano la voce"]', 1, 'Servono a creare liste di numeri "vivi" da vendere ai truffatori.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '9B022A94-32D1-4CD8-B25F-B144E9C534C1', 'CR', 'AI Voice Cloning',
    'La voce dall''altra parte è del tuo capo... o di un computer?',
    E'# Il futuro del Vishing\n\nCon 3 secondi di audio tuo (presi da Instagram), l''AI può clonare la tua voce.\n\nI truffatori usano queste voci per chiamare parenti ("Mamma, ho fatto un incidente, servono soldi") o dipendenti ("Fai il bonifico").\nLa voce non è più una prova d''identità.',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('9B022A94-32D1-4CD8-B25F-B144E9C534C1', 'Come difendersi dal Voice Cloning?', 'multiple_choice', '["Non parlare mai", "Stabilire una ''Parola d''ordine'' segreta con la famiglia/azienda per le emergenze", "Urlare", "Cantare"]', 1, 'Se ti chiedono soldi con la voce di un parente, chiedi la parola d''ordine.'),
('9B022A94-32D1-4CD8-B25F-B144E9C534C1', 'Quanto audio serve per clonare una voce?', 'multiple_choice', '["Ore", "Pochi secondi di audio pulito", "Anni", "Giorni"]', 1, 'La tecnologia VALL-E di Microsoft e altre simili sono spaventosamente efficienti.'),
('9B022A94-32D1-4CD8-B25F-B144E9C534C1', 'Chi è più a rischio?', 'multiple_choice', '["Nessuno", "Chi pubblica molti video parlati sui social (TikTok/Reels)", "I muti", "Gli eremiti"]', 1, 'Forniscono ai truffatori il "dataset" perfetto per l''addestramento AI.'),
('9B022A94-32D1-4CD8-B25F-B144E9C534C1', 'Se ricevi una chiamata di "rapimento virtuale"?', 'multiple_choice', '["Paga subito", "Mantieni la calma, prova a chiamare il presunto rapito su un altra linea o chiedi prove di vita impossibili da simulare", "Smetti di respirare", "Corri"]', 1, 'Spesso la persona "rapita" è al sicuro e non sa nulla.'),
('9B022A94-32D1-4CD8-B25F-B144E9C534C1', 'L''audio WhatsApp è sicuro?', 'multiple_choice', '["Sì", "No, anche i messaggi vocali possono essere generati o inoltrati", "Sempre", "Mai"]', 1, 'La voce non è più garanzia di presenza umana.');


-- 11. LODI (LO) - Smishing (SMS Phishing)

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '23E11A52-9BDC-46FB-9A06-316FF7065E08', 'LO', 'Il Pacco in Giacenza',
    'SMS: "Il tuo pacco è bloccato. Paga 2€ per sbloccarlo".',
    E'# Smishing delle Spedizioni\n\nTutti aspettiamo pacchi.\nArriva un SMS: "BRT/DHL: Pacco bloccato. Clicca qui".\n\nIl link porta a un sito finto che ti ruba i dati della carta per un pagamento irrisorio (2€), ma poi ti abbona a servizi costosi o svuota il conto.',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('23E11A52-9BDC-46FB-9A06-316FF7065E08', 'Cosa fare se arriva un SMS su un pacco inatteso?', 'multiple_choice', '["Cliccare", "Ignorare. Se non aspetti nulla, è una truffa al 100%", "Pagare", "Chiamare"]', 1, 'Sparano nel mucchio sperando che qualcuno stia aspettando Amazon.'),
('23E11A52-9BDC-46FB-9A06-316FF7065E08', 'Se aspetti Davvero un pacco?', 'multiple_choice', '["Clicchi sul link SMS", "Vai sull''app/sito ufficiale di Amazon/Corriere e controlli il tracking da lì", "Aspetti il postino", "Urli"]', 1, 'Mai usare il link nel messaggio. Usa il canale ufficiale.'),
('23E11A52-9BDC-46FB-9A06-316FF7065E08', 'I corrieri chiedono soldi via SMS?', 'multiple_choice', '["Sì, sempre", "No. Eventuali dazi doganali si pagano alla consegna o sul sito ufficiale, mai via link SMS anonimi", "Forse", "Boh"]', 1, 'Le micro-transazioni sono l''esca per avere i dati della carta.'),
('23E11A52-9BDC-46FB-9A06-316FF7065E08', 'Cos''è lo Smishing?', 'multiple_choice', '["Sorridere", "SMS Phishing", "Small Fishing", "Saltare"]', 1, 'Phishing via SMS.'),
('23E11A52-9BDC-46FB-9A06-316FF7065E08', 'Perché gli SMS sono pericolosi?', 'multiple_choice', '["Costano", "Perché ci fidiamo di più del telefono che della mail e i link sono spesso accorciati e illeggibili", "Sono brutti", "Sono corti"]', 1, 'Sullo smartphone è più difficile verificare l''URL.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'B9D6FD5E-68B7-4699-8D7D-E69883EFF27A', 'LO', 'SMS nel Thread Ufficiale',
    'Il messaggio truffa appare sotto quelli veri della banca. Come è possibile?',
    E'# Spoofing dell''ID Mittente (SMS)\n\nIl tuo telefono raggruppa gli SMS per "Nome".\nSe l''hacker invia un SMS falsificando il mittente in "PosteInfo", il telefono lo metterà **nella stessa conversazione** dei messaggi veri di Poste Italiane.\n\nÈ una tecnica subdola che crea fiducia immediata.',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('B9D6FD5E-68B7-4699-8D7D-E69883EFF27A', 'Se un SMS arriva nella chat "Banca Intesa" insieme ai codici veri, è sicuro?', 'multiple_choice', '["Sì, per forza", "No. Gli smartphone raggruppano per nome mittente, che può essere falsificato", "Forse", "Sì, il telefono non sbaglia"]', 1, 'È la trappola più pericolosa dello Smishing.'),
('B9D6FD5E-68B7-4699-8D7D-E69883EFF27A', 'Come distinguere quello falso?', 'multiple_choice', '["Dal colore", "Contiene Link. Le banche quasi non mettono mai link cliccabili per il login negli SMS di servizio", "Dall''odore", "Dal suono"]', 1, 'Le banche ti dicono "Accedi all''App", non "Clicca qui: bit.ly/banca".'),
('B9D6FD5E-68B7-4699-8D7D-E69883EFF27A', 'Cosa fare nel dubbio?', 'multiple_choice', '["Cliccare", "Cancellare la conversazione", "Non cliccare mai. Aprire l''App bancaria direttamente", "Rispondere"]', 2, 'L''App bancaria ha una sezione "Messaggi" sicura.'),
('B9D6FD5E-68B7-4699-8D7D-E69883EFF27A', 'Gli SMS possono contenere virus?', 'multiple_choice', '["No", "Sì (es. Flubot), specialmente su Android, tramite link che scaricano APK infetti", "Solo su iPhone", "Mai"]', 1, 'Attenzione a chi ti chiede di installare "aggiornamenti corriere".'),
('B9D6FD5E-68B7-4699-8D7D-E69883EFF27A', 'Cos''è un Alert SMS?', 'multiple_choice', '["Un''allarme aereo", "Un servizio (buono) che ti avvisa quando spendi soldi. Ma occhio a quelli falsi che chiedono password", "Una sveglia", "Un gioco"]', 1, 'Gli Alert veri ti informano. Quelli falsi ti chiedono di agire/cliccare.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '2E5303EB-FCA0-4A55-B5A4-8D4CDB2BBEFC', 'LO', 'La Truffa "Figlio"',
    '“Ciao mamma, mi è caduto il telefono. Questo è il mio nuovo numero”.',
    E'# "Ciao Mamma"\n\nUn classico moderno.\n1.  Ricevi un WhatsApp/SMS da un numero sconosciuto.\n2.  "Ho rotto il telefono, scrivimi qui su WhatsApp".\n3.  Dopo un po'': "Devo pagare una bolletta urgente ma non ho l''app della banca sul telefono nuovo. Mi fai un bonifico?"',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('2E5303EB-FCA0-4A55-B5A4-8D4CDB2BBEFC', 'Cosa fare se ricevi "Ciao mamma, numero nuovo"?', 'multiple_choice', '["Salvare il numero", "Provare a chiamare il VECCHIO numero del figlio per verificare se risponde", "Fare il bonifico", "Rispondere ''Ciao amore''"]', 1, 'Nel 99% dei casi, il vecchio numero funziona e tuo figlio sta benissimo.'),
('2E5303EB-FCA0-4A55-B5A4-8D4CDB2BBEFC', 'Perché funziona?', 'multiple_choice', '["Perché le mamme sono ansiose", "Sfrutta l''affetto e l''emergenza familiare", "Perché i telefoni si rompono", "Per caso"]', 1, 'Social Engineering puro.'),
('2E5303EB-FCA0-4A55-B5A4-8D4CDB2BBEFC', 'Se provi a chiamare il "nuovo" numero e non rispondono?', 'multiple_choice', '["È timido", "Segnale d''allarme. I truffatori preferiscono le chat testuali per non svelare la voce (spesso straniera o diversa)", "È rotto il microfono", "Dorme"]', 1, 'Vogliono scrivere, non parlare.'),
('2E5303EB-FCA0-4A55-B5A4-8D4CDB2BBEFC', 'Come chiedono i soldi?', 'multiple_choice', '["Di persona", "Bonifico istantaneo o ricarica Mooney/Tabaccaio", "Vaglia", "Contanti"]', 1, 'Metodi veloci: "Devo pagare entro stasera".'),
('2E5303EB-FCA0-4A55-B5A4-8D4CDB2BBEFC', 'Cosa fare se hai pagato?', 'multiple_choice', '["Niente", "Denuncia immediata alla Polizia Postale", "Chiedi scusa a tuo figlio", "Piangi"]', 1, 'Più informazioni dai, più aiuti a fermarli.');


-- 12. MANTOVA (MN) - Marketplace Scams

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '782178FC-F18C-42E9-9DFF-7ED37809FD2C', 'MN', 'Vendo Tutto Subito',
    'Vendi un divano su Subito. "Ti pago subito, ma..."',
    E'# La truffa del Bancomat\n\nTi contatta un compratore interessato.\n"Ti pago subito. Vai al bancomat, inserisci la tua carta e segui le mie istruzioni per ricevere l''accredito".\n\n**Follia**. Al bancomat si PAGA, non si riceve.',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('782178FC-F18C-42E9-9DFF-7ED37809FD2C', 'Si possono ricevere soldi inserendo la carta al Bancomat?', 'multiple_choice', '["Sì, con la magia", "No. Il Bancomat serve a PRELEVARE o VERSARE (su certe casse), non a ricevere bonifici da sconosciuti", "Sì, sempre", "Forse"]', 1, 'Ti stanno facendo fare una ricarica Postepay a LORO senza che tu te ne accorga.'),
('782178FC-F18C-42E9-9DFF-7ED37809FD2C', 'Cosa ti fanno fare in realtà?', 'multiple_choice', '["Un bonifico o una ricarica alla loro carta", "Un prelievo", "Un gioco", "Un selfie"]', 0, 'Ti guidano velocemente: "Digita importo, conferma..." e hai pagato tu loro.'),
('782178FC-F18C-42E9-9DFF-7ED37809FD2C', 'Che linguaggio usano?', 'multiple_choice', '["Professionale", "Frettoloso, spesso sgrammaticato, tecnico confuso ("codice operazione")", "Poetico", "Latino"]', 1, 'Cercano di confonderti.'),
('782178FC-F18C-42E9-9DFF-7ED37809FD2C', 'Un compratore onesto come paga?', 'multiple_choice', '["Bonifico, contanti a mano, o tramite la piattaforma (Subito/Vinted)", "Ricarica Postepay al buio", "Bancomat strano", "Buoni Amazon"]', 0, 'I metodi tracciabili sono gli unici seri.'),
('782178FC-F18C-42E9-9DFF-7ED37809FD2C', 'Se ti chiedono il numero della carta per farti un bonifico?', 'multiple_choice', '["Glielo do", "No, per il bonifico serve l''IBAN. Il numero della carta serve per spendere i tuoi soldi", "Sì", "Forse"]', 1, 'Mai dare PAN (numero lungo), scadenza e CVV.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'CD6D460F-A6CE-4944-A834-BE39F4B7B556', 'MN', 'Pagamento Ricevuto',
    'Hai venduto! Ecco la mail di conferma. Spedisci?',
    E'# La falsa ricevuta\n\nMetti in vendita un oggetto costoso.\nQualcuno lo compra e ti manda la mail: "Banca: Pagamento di 500€ effettuato. Accredito tra 3 giorni. Spedire subito per sbloccare i fondi".\n\nÈ una mail falsa. I soldi non esistono.',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('CD6D460F-A6CE-4944-A834-BE39F4B7B556', 'Spedisci la merce basandoti sullo screenshot del bonifico?', 'multiple_choice', '["Sì, mi fido", "No. Spedisci SOLO quando vedi i soldi contabilizzati sul TUO conto corrente", "Dipende", "Se è simpatico"]', 1, 'Uno screenshot si photoshoppa in 30 secondi.'),
('CD6D460F-A6CE-4944-A834-BE39F4B7B556', 'Esistono bonifici "bloccati" finché non invii il tracking Number?', 'multiple_choice', '["Sì, è normale", "No, le banche non fanno da garanti di spedizione. È una truffa nigeriana classica", "Forse", "Alcune"]', 1, 'La banca muove soldi, non controlla pacchi.'),
('CD6D460F-A6CE-4944-A834-BE39F4B7B556', 'Se il compratore aggiunge 50€ per "spese di spedizione urgente"?', 'multiple_choice', '["È gentile", "Lusinga per farti spedire in fretta senza controllare. Tanto non ha pagato nulla", "È ricco", "È pazzo"]', 1, 'Vogliono il pacco prima che tu scopra il trucco.'),
('CD6D460F-A6CE-4944-A834-BE39F4B7B556', 'Dove controlli se sei stato pagato?', 'multiple_choice', '["Dalla mail ricevuta", "Accedendo al tuo Home Banking in modo indipendente", "Chiedendo al compratore", "Su Facebook"]', 1, 'La tua banca è l''unica fonte affidabile.'),
('CD6D460F-A6CE-4944-A834-BE39F4B7B556', 'Chi sono spesso questi "compratori"?', 'multiple_choice', '["Persone locali", "Truffatori internazionali (spesso scrivono dall''estero, traduttori automatici, chiedono spedizione in Nigeria/Costa d''Avorio)", "Amici", "Parenti"]', 1, 'Se la destinazione è esotica, diffida.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'A5A2A280-9CF1-4947-83F6-6A021B95441E', 'MN', 'Il Corriere lo mando io',
    'Comodo, no? Viene lui a prendere il pacco e ti porta i contanti.',
    E'# Truffa del corriere FedEx/TNT/UPS\n\nSu Facebook Marketplace.\n"Non posso venire di persona. Mando un corriere FedEx a casa tua a portarti i contanti in busta e ritirare l''oggetto".\n\nPoi ricevi una mail (finta) da FedEx: "Per assicurare la busta coi soldi, devi pagare 50€ di assicurazione, che ti verranno rimborsati".',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('A5A2A280-9CF1-4947-83F6-6A021B95441E', 'I corrieri portano contanti in busta per comprare merce tra privati?', 'multiple_choice', '["Sì, servizio standard", "No. I corrieri trasportano merci, non fanno da portavalori per compravendite private in contanti", "Forse", "Sempre"]', 1, 'FedEx non è un furgone portavalori.'),
('A5A2A280-9CF1-4947-83F6-6A021B95441E', 'Qual è l''obiettivo della truffa?', 'multiple_choice', '["Rubare il divano", "Farti pagare le ''spese di assicurazione'' o ''sblocco'' (solitamente 50-100€) su una carta ricaricabile", "Farti un regalo", "Niente"]', 1, 'Non vogliono il tuo oggetto usato, vogliono i 50€ "di assicurazione".'),
('A5A2A280-9CF1-4947-83F6-6A021B95441E', 'Se ti mandano un link per pagare l''assicurazione?', 'multiple_choice', '["Pago", "È un sito di Phishing. Mi rubano anche i dati della carta", "Controllo se è bello", "Lo stampo"]', 1, 'Doppio danno: perdi i 50€ e ti clonano la carta.'),
('A5A2A280-9CF1-4947-83F6-6A021B95441E', 'Come rispondere a "Mando il corriere"?', 'multiple_choice', '["Ok grazie", "No. Scambio a mano (con soldi in mano) o spedisco IO dopo aver ricevuto il bonifico", "Sì, che bello", "Vieni pure"]', 1, 'Dettare le regole: chi vende decide come essere pagato.'),
('A5A2A280-9CF1-4947-83F6-6A021B95441E', 'Perché usano nomi di corrieri famosi?', 'multiple_choice', '["Perché sono bravi", "Per sfruttare la fiducia nel marchio (Brand Hijacking)", "Perché sono gialli", "Perché sono veloci"]', 1, 'Ci fidiamo del logo, non della logica.');
