-- Mission Seed for Veneto Part 1 (VE, VR, PD)
-- Generated by Antigravity
-- Theme: Social Engineering & Human Hacking

-- 1. VENEZIA (VE) - Phishing & Masquerading ("La Maschera Digitale")

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'A1B2C3D4-E5F6-4071-8901-234567890ABC', 'VE', 'Carnevale di Link',
    'Dietro ogni link si può nascondere una maschera.',
    E'# Typosquatting & Fake URL\n\nGli hacker mascherano i link cambiando una sola lettera.\n\nEsempi:\n*   `goggle.com` invece di `google.com`\n*   `paypaI.com` (con la i maiuscola al posto della L)\n\nPassa sempre il mouse sopra il link (senza cliccare) per vedere la vera destinazione sulla barra di stato.',
    'semplice', '5 min', 100, 'level_1', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('A1B2C3D4-E5F6-4071-8901-234567890ABC', 'Cos''è il Typosquatting?', 'multiple_choice', '["Uno sport", "Registrare domini simili a quelli famosi ma con errori di battitura per ingannare gli utenti", "Scrivere veloce", "Un virus"]', 1, 'Sfrutta la disattenzione o la velocità di lettura.'),
('A1B2C3D4-E5F6-4071-8901-234567890ABC', 'Se un link sembra "bit.ly/sconto", come sai dove porta?', 'multiple_choice', '["Clicchi e speri", "Usi un servizio di URL Expander o l''anteprima", "Non porta da nessuna parte", "È sicuro"]', 1, 'Gli short link sono maschere perfette per il malware.'),
('A1B2C3D4-E5F6-4071-8901-234567890ABC', 'L''icona del lucchetto (HTTPS) significa che il sito è legittimo?', 'multiple_choice', '["Sì, assolutamente", "No, significa solo che la connessione è cifrata. Anche i siti di phishing possono avere il lucchetto verde", "Significa che è chiuso", "Solo se è verde"]', 1, 'È un mito comune. Il lucchetto protegge il transito, non garantisce l''identità del sito.'),
('A1B2C3D4-E5F6-4071-8901-234567890ABC', 'Qual è l''estensione di dominio più sicura?', 'multiple_choice', '["Nessuna garantisce sicurezza assoluta, ma diffida di estensioni strane (.xyz, .top, .loan) se non conosciute", ".com", ".it", ".gov"]', 0, 'I domini economici sono spesso usati per spam.'),
('A1B2C3D4-E5F6-4071-8901-234567890ABC', 'Cosa fare se hai cliccato per sbaglio?', 'multiple_choice', '["Chiudere subito, disconnettersi da internet e fare scansione antivirus", "Niente", "Comprare qualcosa", "Spegnere il monitor"]', 0, 'La velocità di reazione è tutto.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'B2C3D4E5-F6A7-4182-9012-345678901BCD', 'VE', 'Acqua Alta',
    'L''urgenza sale, la razionalità scende.',
    E'# Phishing Emotivo\n\nI truffatori usano la PAURA o l''URGENZA per farti agire senza pensare.\n\n*   "Il tuo conto è bloccato!"\n*   "Pacco in giacenza, paga subito!"\n*   "Hai vinto un iPhone!"\n\nSe un messaggio ti mette ansia o euforia improvvisa, è una trappola. Fermati e respira.',
    'medio', '10 min', 200, 'level_2', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('B2C3D4E5-F6A7-4182-9012-345678901BCD', 'Quale emozione sfruttano di più i phisher?', 'multiple_choice', '["Noia", "Paura e Urgenza (Fear of Missing Out / Pericolo)", "Felicità", "Tristezza"]', 1, 'Quando sei agitato, il pensiero critico si spegne.'),
('B2C3D4E5-F6A7-4182-9012-345678901BCD', 'Cosa fare se ricevi un SMS "Pacco bloccato"?', 'multiple_choice', '["Cliccare il link", "Andare sul sito ufficiale del corriere digitando l''URL a mano e inserire il tracking code", "Rispondere insultando", "Pagare"]', 1, 'Non usare mai i link forniti nel messaggio sospetto.'),
('B2C3D4E5-F6A7-4182-9012-345678901BCD', 'Le banche chiedono la password via mail per "controlli sicurezza"?', 'multiple_choice', '["Sì, ogni mese", "Mai. Le banche non chiedono mai le credenziali via mail/SMS", "Solo se il conto è rosso", "A volte"]', 1, 'Regola aurea: la banca sa già i tuoi dati, non deve chiederteli.'),
('B2C3D4E5-F6A7-4182-9012-345678901BCD', 'Grammatica e Phishing: come sono collegati?', 'multiple_choice', '["I truffatori sono poeti", "Errori grammaticali o frasi strane (tradotte male) sono un forte segnale di phishing", "Non c''entra nulla", "Scrivono in latino"]', 1, 'Anche se con l''AI gli errori stanno diminuendo drasticamente.'),
('B2C3D4E5-F6A7-4182-9012-345678901BCD', 'Se il mittente sembra legittimo (es. "Apple Support")?', 'multiple_choice', '["Mi fido", "Controllo l''indirizzo email reale espandendo i dettagli del mittente", "Rispondo", "Lego"]', 1, 'Il nome visualizzato si può falsificare facilmente (Spoofing).');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'C3D4E5F6-A7B8-4293-0123-456789012CDE', 'VE', 'Il Doge Fake',
    'Quando l''amo è fatto su misura per te.',
    E'# Spear Phishing\n\nQui non sparano nel mucchio. Mirano a TE.\n\nHanno studiato i tuoi social, sanno che tifi quella squadra, che hai quel cane, che lavori lì.\nL''email sembra provenire da un collega o amico e cita dettagli personali veri.\n\nÈ l''attacco più pericoloso e difficile da individuare.',
    'difficile', '15 min', 500, 'level_3', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('C3D4E5F6-A7B8-4293-0123-456789012CDE', 'Cos''è lo "Spear Phishing"?', 'multiple_choice', '["Pesca con la lancia", "Phishing mirato verso una persona o organizzazione specifica, altamente personalizzato", "Uno sport olimpico", "Phishing veloce"]', 1, 'Richiede tempo di preparazione (Reconnaissance) ma ha altissimo tasso di successo.'),
('C3D4E5F6-A7B8-4293-0123-456789012CDE', 'Dove trovano le informazioni per personalizzare l''attacco?', 'multiple_choice', '["Nelle stelle", "Sui Social Media (LinkedIn, Facebook, Instagram) e nel Dark Web", "Al bar", "In biblioteca"]', 1, 'I social sono miniere d''oro per l''ingegneria sociale.'),
('C3D4E5F6-A7B8-4293-0123-456789012CDE', 'Se ricevi una mail dal tuo "capo" che chiede un favore strano?', 'multiple_choice', '["Eseguo subito", "Verifico con un altro canale (chiamata, chat interna, di persona)", "Ignoro", "Mi licenzio"]', 1, 'La verifica "Out-of-Band" (su un altro canale) smonta la truffa.'),
('C3D4E5F6-A7B8-4293-0123-456789012CDE', 'Cos''è il Whaling?', 'multiple_choice', '["Caccia alle balene", "Spear Phishing diretto ai \"pesci grossi\" (CEO, CFO, Dirigenti)", "Una crociera", "Un gioco"]', 1, 'Puntano al bersaglio di massimo valore.'),
('C3D4E5F6-A7B8-4293-0123-456789012CDE', 'Come difendersi dallo Spear Phishing?', 'multiple_choice', '["Non usare email", "Ridurre le informazioni personali pubbliche (Privacy Hygiene) e mantenere un sano scetticismo", "Rifiutare la posta", "Cambiare nome"]', 1, 'Meno sanno di te, meno appigli hanno.');


-- 2. VERONA (VR) - Romance Scams ("Amore Criminale")

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'D4E5F6A7-B8C9-4304-1234-567890123DEF', 'VR', 'Giulietta e il Bot',
    'Quel profilo perfetto... esiste davvero?',
    E'# Romance Scam - L''Inizio\n\nSulle app di incontri o social, qualcuno di molto attraente ti contatta.\nSembra interessato a te, fa tante domande, ma...\n\n*   Non può mai fare videochiamate (camera rotta, connessione lenta).\n*   Vive lontano o è "in missione" all''estero.\n*   L''amore scoppia troppo in fretta ("Love Bombing").',
    'semplice', '5 min', 100, 'level_1', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('D4E5F6A7-B8C9-4304-1234-567890123DEF', 'Cos''è il "Love Bombing"?', 'multiple_choice', '["Una bomba d''amore", "Tecnica manipolatoria: riempirti di complimenti e attenzioni eccessive subito per farti innamorare e abbassare le difese", "Un regalo", "Una canzone"]', 1, 'Se è troppo bello e troppo veloce, è sospetto.'),
('D4E5F6A7-B8C9-4304-1234-567890123DEF', 'Perché rifiutano le videochiamate?', 'multiple_choice', '["Sono timidi", "Perché non sono la persona delle foto rubate", "Risparmiano dati", "Non hanno la cam"]', 1, 'Oggi tutti hanno una cam. È un Red Flag enorme.'),
('D4E5F6A7-B8C9-4304-1234-567890123DEF', 'Cosa fare con la foto profilo del sospetto?', 'multiple_choice', '["La stampo", "Reverse Image Search (Google Lens) per vedere se è stata rubata a un modello/a o influencer", "La metto come sfondo", "Niente"]', 1, 'Spesso troverai che le foto appartengono a persone ignare.'),
('D4E5F6A7-B8C9-4304-1234-567890123DEF', 'Su quali piattaforme avvengono queste truffe?', 'multiple_choice', '["Solo Tinder", "Ovunque: Tinder, Instagram, Facebook, LinkedIn, giochi online (Wordfeud)", "Solo di notte", "In piazza"]', 1, 'Anche nei giochi di parole online si nascondono scammer.'),
('D4E5F6A7-B8C9-4304-1234-567890123DEF', 'Vogliono spostare subito la chat su WhatsApp/Telegram?', 'multiple_choice', '["Sì, per isolarti dai controlli di sicurezza della piattaforma di dating e creare intimità", "No", "Forse", "Per comodità"]', 1, 'Prima fase dell''isolamento della vittima.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'E5F6A7B8-C9D0-4415-2345-678901234EFA', 'VR', 'Principe al Verde',
    'Dalle parole dolci al portafoglio vuoto.',
    E'# La Richiesta di Denaro\n\nDopo settimane di "corteggiamento", succede un imprevisto:\n*   "Mi hanno bloccato la carta in aeroporto!"\n*   "Mio figlio sta male e serve un''operazione."\n*   "Ho un affare d''oro (Crypto) da proporti."\n\nTi chiedono **soldi** (bonifici, gift card, crypto) con la promessa di restituirli.',
    'medio', '10 min', 200, 'level_2', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('E5F6A7B8-C9D0-4415-2345-678901234EFA', 'Qual è il segnale definitivo di una Romance Scam?', 'multiple_choice', '["Ti manda fiori", "La richiesta di soldi (o investimenti) per un''emergenza improvvisa", "Ti scrive poesie", "Ti vuole incontrare"]', 1, 'L''obiettivo finale è sempre finanziario.'),
('E5F6A7B8-C9D0-4415-2345-678901234EFA', 'Perché chiedono Gift Card (Amazon, Apple)?', 'multiple_choice', '["Per fare regali", "Perché sono come contanti: una volta inviato il codice, i soldi sono spariti e non rintracciabili", "Costano meno", "Sono belle"]', 1, 'Nessun ente serio o persona normale chiede soldi via Gift Card.'),
('E5F6A7B8-C9D0-4415-2345-678901234EFA', 'Cosa sono i "Money Mule" inconsapevoli?', 'multiple_choice', '["Muli veri", "Vittime sentimentali usate per riciclare denaro sporco (ricevi soldi e li giri al truffatore)", "Banchieri", "Animali"]', 1, 'Rischiano il carcere per riciclaggio, pur essendo vittime della truffa amorosa.'),
('E5F6A7B8-C9D0-4415-2345-678901234EFA', 'Se il "fidanzato/a" virtuale ti propone di investire in Crypto?', 'multiple_choice', '["È un genio della finanza", "Pig Butchering Scam (Truffa della macellazione del maiale): ingrassano la vittima con l''amore per poi macellarla finanziariamente", "Investo tutto", "Mi fido"]', 1, 'Una fusione letale tra Romance Scam e Investment Scam.'),
('E5F6A7B8-C9D0-4415-2345-678901234EFA', 'Come uscirne?', 'multiple_choice', '["Pagare l''ultima volta", "Interrompere ogni contatto (No Contact), bloccare ovunque, non mandare soldi e denunciare", "Chiedere spiegazioni", "Piangere"]', 1, 'Non cercare di "smascherarli" o farti ridare i soldi parlandoci, sono manipolatori esperti.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'F6A7B8C9-D0E1-4526-3456-789012345FAB', 'VR', 'Catfishing Estremo',
    'Quando l''amore diventa un''arma di ricatto.',
    E'# Sextortion\n\nIl rapporto diventa intimo. Ti convincono a mandare foto o video nudi o a fare sesso in cam.\n\nAppena lo fai, la maschera cade.\n"Paga Xmila euro o mando questo video a tutti i tuoi amici di Facebook, alla tua famiglia e al tuo capo."\n\nNon cede al ricatto, non finisce mai.',
    'difficile', '15 min', 500, 'level_3', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('F6A7B8C9-D0E1-4526-3456-789012345FAB', 'Cos''è la "Sextortion"?', 'multiple_choice', '["Sesso sicuro", "Estorsione sessuale: minaccia di pubblicare materiale intimo se non si paga un riscatto", "Una legge", "Un film"]', 1, 'Un crimine odioso che porta le vittime a disperazione estrema.'),
('F6A7B8C9-D0E1-4526-3456-789012345FAB', 'Se paghi il riscatto, cancellano il video?', 'multiple_choice', '["Sì, sono onesti", "Quasi mai. Spesso continuano a chiedere altri soldi all''infinito perché sanno che paghi", "Forse", "Firmano un contratto"]', 1, 'Pagare conferma che sei una vittima pagante.'),
('F6A7B8C9-D0E1-4526-3456-789012345FAB', 'Cosa fare se sei vittima di Sextortion?', 'multiple_choice', '["Pagare subito", "NON pagare. Salvare le prove. Bloccare il ricattatore. Segnalare alle autorità/piattaforme. Parlarne (non isolarsi)", "Cancellare tutto", "Scappare"]', 1, 'Il silenzio è l''arma del ricattatore. Chiedi aiuto.'),
('F6A7B8C9-D0E1-4526-3456-789012345FAB', 'È sicuro fare videochiamate intime con sconosciuti?', 'multiple_choice', '["Sì", "Mai. Possono registrare lo schermo di nascosto anche se l''app dice di no o sembra effimero (tipo Snapchat)", "Solo se promettono", "Di notte sì"]', 1, 'Tutto ciò che passa su uno schermo può essere registrato.'),
('F6A7B8C9-D0E1-4526-3456-789012345FAB', 'Le liste amici sui social dovrebbero essere pubbliche?', 'multiple_choice', '["Sì, sono popolare", "No, nascondi la lista amici. Se il ricattatore non sa chi sono i tuoi amici/parenti, la minaccia è meno efficace", "Indifferente", "Solo per metà"]', 1, 'Rendi difficile per loro trovare i tuoi contatti.');


-- 3. PADOVA (PD) - OSINT & Digital Footprint ("L'Investigatore")

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '23CD5E6F-A7B8-4637-4567-890123456ABC', 'PD', 'Lo Stalker Digitale',
    'Cosa sanno di te solo guardando il tuo profilo?',
    E'# Digital Footprint\n\nOgni post, like, commento e foto lascia una traccia.\nL''Open Source Intelligence (OSINT) è l''arte di raccogliere questi dati pubblici per profilarti.\n\nData di nascita? Nome del cane? Scuola frequentata?\nSono tutte risposte alle tue "Domande di Sicurezza" per il reset password.',
    'semplice', '5 min', 100, 'level_1', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('23CD5E6F-A7B8-4637-4567-890123456ABC', 'Cosa significa OSINT?', 'multiple_choice', '["Open Source Intelligence (Intelligence su fonti aperte/pubbliche)", "Osso Buco", "Sistema Operativo", "Hacking illegale"]', 0, 'Non è illegale, usa dati che tu stesso hai reso pubblici.'),
('23CD5E6F-A7B8-4637-4567-890123456ABC', 'Se pubblichi foto del biglietto aereo sui social?', 'multiple_choice', '["Fai invidia", "Con il codice a barre/prenotazione, chiunque può accedere alla tua prenotazione, vedere il tuo indirizzo, o cancellare il volo", "Niente", "Ti fanno l''upgrade"]', 1, 'Mai pubblicare carte d''imbarco o biglietti di concerti con codici visibili.'),
('23CD5E6F-A7B8-4637-4567-890123456ABC', 'Perché è rischioso i quiz "Che personaggio sei?" su Facebook?', 'multiple_choice', '["Sono stupidi", "Spesso raccolgono dati personali e profilazione psicologica in cambio del risultato", "Ti dicono che sei cattivo", "Costano"]', 1, 'Cambridge Analytica insegnava questo.'),
('23CD5E6F-A7B8-4637-4567-890123456ABC', 'La data di nascita completa su Facebook?', 'multiple_choice', '["Serve per gli auguri", "È un dato chiave per il furto d''identità (spesso basta Nome + Data Nascita)", "È obbligatoria", "È falsa"]', 1, 'Lascia solo giorno e mese, nascondi l''anno, o toglila del tutto.'),
('23CD5E6F-A7B8-4637-4567-890123456ABC', 'Cos''è il "Doxing"?', 'multiple_choice', '["Un cane", "Cercare e diffondere pubblicamente dati privati (indirizzo, telefono) di qualcuno per vendetta o molestia", "Un documento", "Boxare"]', 1, 'Pratica nata negli ambienti hacker/gaming per intimidire.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '34DE6F7A-B8C9-4748-5678-901234567BCD', 'PD', 'Meta-Dati Nascosti',
    'Le tue foto parlano più di quanto credi.',
    E'# EXIF Data\n\nQuando scatti una foto, il telefono salva al suo interno dati invisibili (Metadati EXIF):\n*   Modello fotocamera\n*   Data e ora esatta\n*   **Coordinate GPS precise**\n\nSe invii la foto originale, stai inviando la mappa di dove eri.',
    'medio', '10 min', 200, 'level_2', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('34DE6F7A-B8C9-4748-5678-901234567BCD', 'Cosa sono i dati EXIF?', 'multiple_choice', '["Virus", "Metadati incorporati nelle immagini digitali (shutter speed, ISO, GPS, etc.)", "Filtri Instagram", "Cornici"]', 1, 'Exchangeable Image File Format.'),
('34DE6F7A-B8C9-4748-5678-901234567BCD', 'I social network (Facebook, Instagram, WhatsApp) rimuovono i metadati?', 'multiple_choice', '["Mai", "Solitamente sì, quando comprimono le immagini per la pubblicazione", "Solo se paghi", "Solo su iPhone"]', 1, 'Fortunatamente sì. Ma se invii il file "come documento" o via email, i dati restano.'),
('34DE6F7A-B8C9-4748-5678-901234567BCD', 'Perché è pericoloso inviare una foto scattata a casa a uno sconosciuto?', 'multiple_choice', '["Vede che è disordinata", "I metadati GPS potrebbero rivelare l''esatta posizione di casa tua", "La foto è brutta", "Niente"]', 1, 'Se l''opzione "Salva posizione" è attiva nella fotocamera.'),
('34DE6F7A-B8C9-4748-5678-901234567BCD', 'Come rimuovere i metadati?', 'multiple_choice', '["Cancellando la foto", "Usando strumenti di pulizia (Exif Remover) o screenshot della foto stessa", "Stampandola", "Chiudendo gli occhi"]', 1, 'Fare uno screenshot della foto crea un nuovo file senza i vecchi dati GPS.'),
('34DE6F7A-B8C9-4748-5678-901234567BCD', 'Anche i documenti Word/PDF hanno metadati?', 'multiple_choice', '["No", "Sì, spesso contengono l''Autore, data creazione e revisioni passate", "Solo se scritti in rosso", "Mai"]', 1, 'Molte aziende hanno fatto leak di informazioni tramite i metadati dei PDF pubblici.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '45EF7A8B-C9D0-4859-6789-012345678CDE', 'PD', 'Google Dorking',
    'Hacking usando solo la barra di ricerca.',
    E'# Google Hacking\n\nGoogle indicizza tutto, anche quello che non dovrebbe.\nUsando operatori speciali ("Dorks"), si possono trovare:\n\n*   `filetype:pdf "confidentiale"`\n*   `site:trentino.it password`\n*   Webcam aperte\n\nNon serve essere hacker, basta saper cercare.',
    'difficile', '15 min', 500, 'level_3', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('45EF7A8B-C9D0-4859-6789-012345678CDE', 'Cos''è una "Google Dork"?', 'multiple_choice', '["Un pesce", "Una query di ricerca avanzata che usa operatori specifici per trovare informazioni sensibili nascoste nel web", "Un errore di Google", "Un gioco"]', 1, 'Strumento potente (e pericoloso) nelle mani di chi fa OSINT.'),
('45EF7A8B-C9D0-4859-6789-012345678CDE', 'L''operatore `site:gov.it` cosa fa?', 'multiple_choice', '["Cerca siti governativi", "Limita i risultati della ricerca solo al dominio specificato (gov.it)", "Blocca il governo", "Cancella i siti"]', 1, 'Utile per restringere il campo.'),
('45EF7A8B-C9D0-4859-6789-012345678CDE', 'L''operatore `filetype:xls password` cosa potrebbe trovare?', 'multiple_choice', '["Immagini di password", "File Excel indicizzati che contengono la parola ''password'' nel testo", "Niente", "Virus"]', 1, 'Molta gente salva le password in Excel e le mette online per sbaglio.'),
('45EF7A8B-C9D0-4859-6789-012345678CDE', 'È illegale usare le Google Dorks?', 'multiple_choice', '["Sì, sempre", "No, usare Google non è illegale. È illegale scaricare/usare i dati sensibili trovati o accedere a sistemi protetti", "Solo di notte", "Dipende dal browser"]', 1, 'La ricerca è lecita, l''intrusione no.'),
('45EF7A8B-C9D0-4859-6789-012345678CDE', 'Come difendersi dal Google Dorking?', 'multiple_choice', '["Spegnere Google", "Configurare correttamente il file ''robots.txt'' e non esporre file sensibili in cartelle pubbliche del server web", "Usare Bing", "Pregare"]', 1, 'Esegui regolarmente dorks sul tuo stesso sito per vedere cosa esponi.');
