-- Mission Seed for Piemonte Region (Part 1: TO, VC, NO, CN, AT, AL, BI, VB)
-- Generated by Antigravity & Fixed for JSON Syntax

-- 1. TORINO (TO) - Introduzione agli Algoritmi
-- Mission 1: Semplice (C7234621-29BA-4F32-AB13-7A1D43130DE7)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'C7234621-29BA-4F32-AB13-7A1D43130DE7', 'TO', 'Il "Cervello" dei Social',
    'L''algoritmo non è magico, è matematica. Scopri come sceglie cosa mostrarti.',
    E'# Il "Cervello" dei Social\n\nTi sei mai chiesto perché il tuo feed è diverso da quello dei tuoi amici?\n\nNon è magia. È un algoritmo che ha un solo obiettivo: **massimizzare il tuo tempo sull''app**.\n\nOgni tuo like, commento e secondo di visione è un dato che istruisce il "cervello" digitale su cosa offrirti dopo.',
    'semplice', '5 min', 100, 'level_1', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('C7234621-29BA-4F32-AB13-7A1D43130DE7', 'Perché vedi certi post nel tuo feed?', 'multiple_choice', '["Perché sono importanti", "Perché generano engagement (reazioni)", "Perché sono veri", "Perché l''ha deciso il governo"]', 1, 'L''algoritmo privilegia i contenuti che, statisticamente, ti terranno incollato allo schermo (engagement).'),
('C7234621-29BA-4F32-AB13-7A1D43130DE7', 'Cos''è il "Feed"?', 'multiple_choice', '["Un giornale uguale per tutti", "Un flusso di contenuti personalizzato per te", "Una chat di gruppo", "Un sito di notizie"]', 1, 'Il Feed è una selezione unica e personale curata dall''algoritmo in base ai tuoi interessi.'),
('C7234621-29BA-4F32-AB13-7A1D43130DE7', 'L''algoritmo ti ascolta tramite il microfono?', 'multiple_choice', '["Sì, sempre", "No, usa i tuoi dati comportamentali per prevedere i tuoi gusti", "Solo di notte", "Dipende dalla marca del telefono"]', 1, 'È un mito comune. La capacità di previsione basata sui dati è così accurata da *sembrare* ascolto.'),
('C7234621-29BA-4F32-AB13-7A1D43130DE7', 'Qual è l''obiettivo primario di un social network?', 'multiple_choice', '["Informarti", "Farti felice", "Massimizzare il tempo che spendi sull''app per vendere pubblicità", "Aiutarti a studiare"]', 2, 'Sei il prodotto. Più tempo passi sull''app, più pubblicità vedi.'),
('C7234621-29BA-4F32-AB13-7A1D43130DE7', 'Chi decide in ultima analisi cosa vedi?', 'multiple_choice', '["Solo Zuckerberg", "Il caso", "Tu (col tuo comportamento) e la Piattaforma insieme", "I tuoi genitori"]', 2, 'È un ciclo: tu agisci, l''algoritmo impara e ti ripropone contenuti simili.');

-- Mission 2: Medio (462D2A80-CA34-4C61-912E-0975505CB415)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '462D2A80-CA34-4C61-912E-0975505CB415', 'TO', 'La Profilazione',
    'Tu sei un insieme di etichette per gli inserzionisti. Scopri il tuo "Digital Twin".',
    E'# Sei stato etichettato\n\nPer gli inserzionisti, non sei "Mario". Sei:\n* Maschio, 20-30 anni\n* Interesse: Calcio\n* Propensione all''acquisto: Alta\n\nQuesto si chiama **Profilazione**. Viene creato un gemello digitale ("Digital Twin") che viene usato per simulare quali annunci funzioneranno su di te.',
    'medio', '10 min', 200, 'level_2', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('462D2A80-CA34-4C61-912E-0975505CB415', 'Cos''è la profilazione?', 'multiple_choice', '["Fare una foto di profilo", "La raccolta e analisi dei dati per classificare gli utenti in gruppi", "Scrivere una biografia", "Un test psicologico"]', 1, 'Serve a capire chi sei per venderti le cose giuste al momento giusto.'),
('462D2A80-CA34-4C61-912E-0975505CB415', 'Qual è la differenza tra dati demografici e psicografici?', 'multiple_choice', '["Nessuna", "Demografici = Chi sei (Età); Psicografici = Cosa pensi/Senti (Interessi)", "I dati demografici sono illegali", "Psicografici sono solo per psicologi"]', 1, 'I dati psicografici (interessi, paure, valori) sono molto più potenti per la persuasione.'),
('462D2A80-CA34-4C61-912E-0975505CB415', 'Perché Facebook e Instagram sono gratis?', 'multiple_choice', '["Per beneficenza", "Tu sei il prodotto: i tuoi dati vengono venduti", "Pagano gli stati", "È una prova gratuita"]', 1, 'In economia digitale, "Se è gratis, il prodotto sei tu".'),
('462D2A80-CA34-4C61-912E-0975505CB415', 'Cos''è un "Digital Twin"?', 'multiple_choice', '["Un tuo gemello vero", "Una copia digitale del tuo profilo usata per simulazioni", "Un virus", "Un avatar di gioco"]', 1, 'È un modello matematico che ti rappresenta e permette di prevedere le tue reazioni.'),
('462D2A80-CA34-4C61-912E-0975505CB415', 'Come fa l''algoritmo a prevedere le tue azioni?', 'multiple_choice', '["Legge la mente", "Analizza i pattern del tuo comportamento passato", "Tira a indovinare", "Chiede ai tuoi amici"]', 1, 'Se ogni martedì ordini la pizza, l''algoritmo imparerà a mostrarti pizzerie il martedì pomeriggio.');

-- Mission 3: Difficile (CC3C3220-E40C-45B2-9925-6F6E39B2F386)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'CC3C3220-E40C-45B2-9925-6F6E39B2F386', 'TO', 'Il Loop della Dopamina',
    'Perché non riesci a smettere di scrollare? La chimica dietro la dipendenza.',
    E'# Dopamina: La Droga dei Social\n\nLo scroll infinito non è un errore di design. È fatto apposta.\n\nFunziona come una **Slot Machine**: tiri la leva (scrolli) e speri di vincere un premio (un post interessante). Questa incertezza rilascia **Dopamina**, il neurotrasmettitore del piacere e dell''anticipazione.',
    'difficile', '15 min', 500, 'level_3', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('CC3C3220-E40C-45B2-9925-6F6E39B2F386', 'Perché lo scroll è "infinito"?', 'multiple_choice', '["Perché finiscono i contenuti", "Per eliminare i \"punti di stop\" e tenerti nell''app", "Per risparmiare batteria", "È un bug"]', 1, 'Senza pagine da girare, non c''è un segnale naturale per smettere.'),
('CC3C3220-E40C-45B2-9925-6F6E39B2F386', 'A quale gioco d''azzardo assomiglia il feed dei social?', 'multiple_choice', '["Poker", "Slot Machine", "Roulette", "Blackjack"]', 1, 'Entrambi usano un "sistema di ricompensa variabile" intermittente.'),
('CC3C3220-E40C-45B2-9925-6F6E39B2F386', 'Perché le notifiche sono spesso rosse?', 'multiple_choice', '["È il colore preferito del creatore", "Per creare urgenza e allerta", "Perché è rilassante", "Casuale"]', 1, 'Il rosso è evolutivamente associato al pericolo o all''importanza, catturando subito l''attenzione.'),
('CC3C3220-E40C-45B2-9925-6F6E39B2F386', 'Cos''è la FOMO?', 'multiple_choice', '["Fear Of Missing Out (Paura di perdersi qualcosa)", "Una marca di vestiti", "Un tipo di formaggio", "Fear Of Meeting Others"]', 0, 'L''ansia sociale di essere esclusi da esperienze gratificanti che gli altri stanno vivendo.'),
('CC3C3220-E40C-45B2-9925-6F6E39B2F386', 'Qual è un buon modo per interrompere il loop?', 'multiple_choice', '["Scrollare più veloce", "Mettere il telefono in bianco e nero o impostare limiti di tempo", "Comprare un telefono più grande", "Lamentarsi"]', 1, 'Rendere il telefono meno stimolante visivamente aiuta a ridurre il rilascio di dopamina.');


-- 2. VERCELLI (VC) - Filter Bubbles
-- Mission 1: Semplice (434951E8-CB5E-467E-9F6A-14FE0E03A0EB)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '434951E8-CB5E-467E-9F6A-14FE0E03A0EB', 'VC', 'La Bolla Invisibile',
    'Viviamo in mondi separati senza saperlo. Scopri cos''è una Filter Bubble.',
    E'# La tua Bolla Personale\n\nImmagina di vivere in una casa con specchi al posto delle finestre. Vedi solo te stesso.\n\nQuesta è la **Filter Bubble**: l''algoritmo filtra via tutto ciò che non ti piace. Sembra comodo, ma ti isola dalla realtà completa.',
    'semplice', '5 min', 100, 'level_1', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('434951E8-CB5E-467E-9F6A-14FE0E03A0EB', 'Cos''è una "Filter Bubble"?', 'multiple_choice', '["Una bolla di sapone", "L''isolamento intellettuale causato dagli algoritmi che mostrano solo ciò che ci piace", "Un filtro di Instagram", "Una protezione antivirus"]', 1, 'È un universo di informazioni unico per te, che ti isola dai punti di vista opposti.'),
('434951E8-CB5E-467E-9F6A-14FE0E03A0EB', 'Perché è pericolosa?', 'multiple_choice', '["Perché scoppia", "Perché ci impedisce di conoscere idee diverse e capire il mondo", "Non è pericolosa", "Fa consumare giga"]', 1, 'Senza confronto, perdiamo la capacità di comprendere la complessità del mondo.'),
('434951E8-CB5E-467E-9F6A-14FE0E03A0EB', 'Chi ha coniato il termine "Filter Bubble"?', 'multiple_choice', '["Mark Zuckerberg", "Eli Pariser", "Steve Jobs", "Elon Musk"]', 1, 'L''attivista Eli Pariser nel suo famoso libro del 2011.'),
('434951E8-CB5E-467E-9F6A-14FE0E03A0EB', 'Google mostra a tutti gli stessi risultati per la stessa ricerca?', 'multiple_choice', '["Sì, sempre", "No, dipendono dalla tua cronologia e posizione", "Solo se paghi", "Dipende dal browser"]', 1, 'Due persone sedute vicine possono vedere risultati completamente diversi per la stessa parola chiave.'),
('434951E8-CB5E-467E-9F6A-14FE0E03A0EB', 'Come puoi accorgerti di essere in una bolla?', 'multiple_choice', '["Se vedi solo opinioni con cui sei d''accordo", "Se il telefono è caldo", "Se non hai amici", "Se usi TikTok"]', 0, 'L''assenza totale di dissenso o notizie contrastanti è il primo campanello d''allarme.');

-- Mission 2: Medio (79488B3B-E97D-43CD-ABA9-CF00B10352D1)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '79488B3B-E97D-43CD-ABA9-CF00B10352D1', 'VC', 'Conseguenze Reali',
    'Quando la bolla scoppia (o non scoppia). Effetti su politica e società.',
    E'# Dalla Bolla alla Realtà\n\nSe ognuno vede una "verità" diversa, come possiamo andare d''accordo?\n\nLa frammentazione della realtà porta a:\n1. Incomunicabilità\n2. Estremismo\n3. Sorpresa quando le elezioni vanno diversamente da come credevamo (perché nella nostra bolla "tutti" la pensavano come noi).',
    'medio', '10 min', 200, 'level_2', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('79488B3B-E97D-43CD-ABA9-CF00B10352D1', 'Qual è un effetto della bolla sulla democrazia?', 'multiple_choice', '["Migliora il voto", "Crea polarizzazione e rende difficile il dialogo tra parti", "Nessuno", "Aumenta l''affluenza"]', 1, 'Se non condividiamo una base comune di fatti, il dibattito democratico diventa impossibile.'),
('79488B3B-E97D-43CD-ABA9-CF00B10352D1', 'Perché ci sentiamo sempre nel giusto online?', 'multiple_choice', '["Perché siamo intelligenti", "Perché l''algoritmo ci circonda di persone che ci danno ragione", "Perché gli altri sbagliano", "Per fortuna"]', 1, 'È una validazione artificiale costante delle nostre opinioni.'),
('79488B3B-E97D-43CD-ABA9-CF00B10352D1', 'Qual è la differenza principale tra un giornale cartaceo e un feed?', 'multiple_choice', '["La carta", "Il giornale ha una gerarchia di notizie uguale per tutti (Editoriale)", "Il costo", "Le foto"]', 1, 'I media tradizionali offrono un''agenda comune; i social un''agenda personalizzata.'),
('79488B3B-E97D-43CD-ABA9-CF00B10352D1', 'Cosa rischia chi vive solo nella sua bolla?', 'multiple_choice', '["Di annoiarsi", "Di diventare più tollerante", "Di radicalizzarsi verso posizioni estreme", "Di perdere la password"]', 2, 'Senza contraddittorio, le idee tendono a diventare sempre più pure ed estreme.'),
('79488B3B-E97D-43CD-ABA9-CF00B10352D1', 'In politica, cosa causa la bolla?', 'multiple_choice', '["Pace nel mondo", "Sottovalutazione degli avversari perché non li vediamo mai nel feed", "Più voti", "Meno tasse"]', 1, 'Ci stupiamo quando "l''altra parte" vince perché nel nostro mondo digitale non esistevano.');


-- Mission 3: Difficile (F7D95609-CE9E-49C8-90C2-4C71AB7FCBA3)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'F7D95609-CE9E-49C8-90C2-4C71AB7FCBA3', 'VC', 'Scoppiare la Bolla',
    'Strategie di evasione per riprendere il controllo della tua dieta informativa.',
    E'# Hackera il tuo Feed\n\nVuoi uscire dalla prigione dorata?\n\nDevi confondere l''algoritmo.\n\n* **Like Tattici**: Metti like a cose che non sono "da te".\n* **Fonti diverse**: Iscriviti a canali di idee opposte.\n* **Incognito**: Usa la navigazione privata per le ricerche delicate.',
    'difficile', '15 min', 500, 'level_3', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('F7D95609-CE9E-49C8-90C2-4C71AB7FCBA3', 'Cosa sono i "Like Tattici"?', 'multiple_choice', '["Like a caso", "Like a contenuti opposti ai tuoi soliti per ingannare l''algoritmo", "Like agli amici", "Like a pagamento"]', 1, 'Segnalano all''algoritmo che sei interessato a un ventaglio più ampio di argomenti.'),
('F7D95609-CE9E-49C8-90C2-4C71AB7FCBA3', 'A cosa serve la navigazione in incognito in questo contesto?', 'multiple_choice', '["A nascondersi", "A fare ricerche senza che queste influenzino i suggerimenti futuri", "A navigare veloce", "A risparmiare dati"]', 1, 'Evita di "sporcare" il tuo profilo con interessi momentanei.'),
('F7D95609-CE9E-49C8-90C2-4C71AB7FCBA3', 'Perché dovresti seguire chi non ti piace?', 'multiple_choice', '["Per insultarli", "Per capire il loro punto di vista e rompere l''echo chamber", "Per spiarti", "Non dovresti"]', 1, 'Ti espone ad argomentazioni che altrimenti non vedresti mai.'),
('F7D95609-CE9E-49C8-90C2-4C71AB7FCBA3', 'Perché cancellare la cronologia e i cookie aiuta?', 'multiple_choice', '["Libera spazio", "Resetta parzialmente la \"memoria\" che l''algoritmo ha di te", "Cancella i virus", "Velocizza internet"]', 1, 'Rimuove i dati vecchi su cui si basano le previsioni attuali.'),
('F7D95609-CE9E-49C8-90C2-4C71AB7FCBA3', 'Il modo migliore per scoppiare la bolla è...', 'multiple_choice', '["Smettere di usare internet", "Diversificare attivamente le proprie fonti di informazione", "Comprare un iPhone", "Usare solo la TV"]', 1, 'L''azione attiva e consapevole è l''unica difesa contro l''automatismo passivo.');


-- 3. NOVARA (NO) - Echo Chambers
-- Mission 1: Semplice (BC8A4B42-1383-4F73-A95F-74C22D2B70A4)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'BC8A4B42-1383-4F73-A95F-74C22D2B70A4', 'NO', 'L''Eco delle Tue Idee',
    'Quando senti solo la tua voce riflessa. Cos''è una Echo Chamber.',
    E'# Camere dell''Eco\n\nHia presente quando urli in una valle e senti solo la tua voce?\n\nLe **Echo Chambers** (Camere dell''Eco) online sono gruppi o spazi dove le stesse idee vengono ripetute, amplificate e mai messe in discussione. Chi non è d''accordo viene bannato o escluso.',
    'semplice', '5 min', 100, 'level_1', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('BC8A4B42-1383-4F73-A95F-74C22D2B70A4', 'Cos''è una Echo Chamber?', 'multiple_choice', '["Una stanza vuota", "Un ambiente online dove le idee vengono rafforzate dalla ripetizione ed esclusione del dissenso", "Un effetto audio", "Un gruppo musicale"]', 1, 'Esattamente come l''eco, ti rimanda indietro solo ciò che hai emesso (le tue idee), facendole sembrare più forti.'),
('BC8A4B42-1383-4F73-A95F-74C22D2B70A4', 'Che differenza c''è con la Filter Bubble?', 'multiple_choice', '["Nessuna", "La Filter Bubble è algoritmica, l''Echo Chamber è spesso sociale/scelta dall''utente", "Una è rossa l''altra blu", "La dimensione"]', 1, 'Spesso scegliamo noi di entrare in una Echo Chamber (es. un gruppo Telegram), mentre la Filter Bubble ci viene costruita attorno.'),
('BC8A4B42-1383-4F73-A95F-74C22D2B70A4', 'Perché ci piace stare nelle Echo Chambers?', 'multiple_choice', '["Perché è scomodo", "Perché ci sentiamo al sicuro e validati (Comfort Zone)", "Perché ci piace l''eco", "Perché si paga"]', 1, 'Il nostro cervello ama la conferma; il dissenso crea stress cognitivo.'),
('BC8A4B42-1383-4F73-A95F-74C22D2B70A4', 'Cosa succede alle voci discordanti in una Echo Chamber?', 'multiple_choice', '["Vengono ascoltate", "Vengono attaccate, ridicolizzate o espulse", "Diventano admin", "Nulla"]', 1, 'Il dissenso è visto come un attacco al gruppo, non come uno spunto di riflessione.'),
('BC8A4B42-1383-4F73-A95F-74C22D2B70A4', 'Qual è il rischio sociale principale?', 'multiple_choice', '["Che la gente diventi sorda", "La frammentazione della società in tribù ostili", "Che internet finisca", "Nessuno"]', 1, 'Se le tribù non si parlano più, la società si spacca.');


-- Mission 2: Medio (2EA336A0-F402-40A6-9009-8AB6B9D7460D)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '2EA336A0-F402-40A6-9009-8AB6B9D7460D', 'NO', 'Polarizzazione',
    'Noi contro Loro. Come nasce l''odio online.',
    E'# Noi vs Loro\n\nNelle Echo Chambers, il mondo si divide in bianco e nero.\n\n"Noi" siamo i buoni, intelligenti e onesti.\n"Loro" sono i cattivi, stupidi e disonesti.\n\nQuesta demonizzazione giustifica l''odio e impedisce qualsiasi compromesso.',
    'medio', '10 min', 200, 'level_2', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('2EA336A0-F402-40A6-9009-8AB6B9D7460D', 'Come nasce la polarizzazione tra gruppi?', 'multiple_choice', '["Dal dialogo", "Dall''isolamento e rinforzo continuo delle proprie tesi contro un nemico comune", "Dalla pace", "Dalla condivisione di cibo"]', 1, 'Il nemico comune unisce il gruppo (l''Ingroup) contro l''esterno (l''Outgroup).'),
('2EA336A0-F402-40A6-9009-8AB6B9D7460D', 'Cos''è la demonizzazione dell''avversario?', 'multiple_choice', '["Un rito magico", "Rappresentare chi la pensa diversamente come malvagio o disumano", "Disegnare corna sulle foto", "Ignorarlo"]', 1, 'Serve a rimuovere l''empatia: se l''altro è "il male", allora tutto è permesso contro di lui.'),
('2EA336A0-F402-40A6-9009-8AB6B9D7460D', 'Quale ruolo hanno i gruppi chiusi (Facebook/Telegram)?', 'multiple_choice', '["Sono innocui", "Spesso agiscono come incubatori di radicalizzazione", "Servono solo per le ricette", "Aiutano la diversità"]', 1, 'L''assenza di moderazione esterna o sguardi critici accelera la deriva estremista.'),
('2EA336A0-F402-40A6-9009-8AB6B9D7460D', 'Cos''è il Bias Tribale?', 'multiple_choice', '["Tifare una squadra", "Difendere il proprio gruppo a prescindere dai fatti", "Un tatuaggio", "Una festa"]', 1, '"Il mio gruppo ha ragione anche quando ha torto".'),
('2EA336A0-F402-40A6-9009-8AB6B9D7460D', 'A cosa porta la radicalizzazione estrema?', 'multiple_choice', '["A nulla", "All''accettazione della violenza (verbale o fisica) come soluzione", "Alla felicità", "A più amici"]', 1, 'Quando l''altro non è più umano, la violenza diventa un''opzione accettabile.');


-- Mission 3: Difficile (FB8811B5-B5C7-480B-B938-D43FCF9CBBCD)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'FB8811B5-B5C7-480B-B938-D43FCF9CBBCD', 'NO', 'Uscire dalla Camera',
    'Costruire ponti invece di muri. Tecniche di disinnesco.',
    E'# Rompere i Muri\n\nUscire da una Camera dell''Eco è doloroso.\n\nRichiede:\n1. **Ascolto Attivo**: Ascoltare per capire, non per rispondere.\n2. **Carità Interpretativa**: Assumere che l''altro non sia in malafede.\n3. **Cercare i fatti**: Non le opinioni sulle persone.',
    'difficile', '15 min', 500, 'level_3', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('FB8811B5-B5C7-480B-B938-D43FCF9CBBCD', 'Cos''è l''Ascolto Attivo?', 'multiple_choice', '["Sentire rumori", "Ascoltare con l''intento genuino di comprendere il punto di vista altrui", "Fare finta di ascoltare", "Registrare l''audio"]', 1, 'Sospendere il giudizio mentre l''altro parla è fondamentale per il dialogo.'),
('FB8811B5-B5C7-480B-B938-D43FCF9CBBCD', 'Cosa significa cercare la "verità" dell''altro?', 'multiple_choice', '["Dargli ragione", "Capire quali esperienze o paure hanno portato l''altro a quella conclusione", "Mentire", "Rubare i suoi dati"]', 1, 'Spesso dietro un''opinione "sbagliata" c''è un bisogno o una paura reale.'),
('FB8811B5-B5C7-480B-B938-D43FCF9CBBCD', 'In una discussione sana, su cosa ci si concentra?', 'multiple_choice', '["Sugli insulti", "Sui fatti e le argomentazioni, non sulle persone", "Sull''aspetto fisico", "Sulla grammatica"]', 1, 'Attaccare l''idea, mai la persona (Argomento ad Hominem).'),
('FB8811B5-B5C7-480B-B938-D43FCF9CBBCD', 'Perché è difficile riconoscere i propri pregiudizi?', 'multiple_choice', '["Perché non ne abbiamo", "Perché operano a livello inconscio", "Perché siamo perfetti", "Perché si nascondono"]', 1, 'Richiede un grande sforzo di auto-analisi e umiltà.'),
('FB8811B5-B5C7-480B-B938-D43FCF9CBBCD', 'Qual è il valore della diversità intellettuale?', 'multiple_choice', '["Nessuno", "Rafforza le nostre idee perché le mette alla prova e le migliora", "Crea solo confusione", "Fa perdere tempo"]', 1, 'Come in biologia, la diversità rende un sistema (o un pensiero) più resiliente e forte.');


-- 4. CUNEO (CN) - Bias Cognitivi
-- Mission 1: Semplice (72DAC75F-905E-49A4-9095-C5F6E66C4272)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '72DAC75F-905E-49A4-9095-C5F6E66C4272', 'CN', 'Il Cervello Pigro',
    'Il nostro cervello usa scorciatoie. Scopri i Bias Cognitivi.',
    E'# Il Cervello Risparmia Energia\n\nIl cervello consuma il 20% della tua energia. Per risparmiare, usa scorciatoie chiamate **Bias Cognitivi**.\n\nSpesso funzionano, ma online ci fanno commettere errori sistematici di giudizio.',
    'semplice', '5 min', 100, 'level_1', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('72DAC75F-905E-49A4-9095-C5F6E66C4272', 'Cos''è un Bias Cognitivo?', 'multiple_choice', '["Un errore del computer", "Una distorsione sistematica del giudizio umano", "Un virus mentale", "Una malattia"]', 1, 'È una "scorciatoia" mentale che porta a errori prevedibili.'),
('72DAC75F-905E-49A4-9095-C5F6E66C4272', 'Qual è il "Bias di Conferma"?', 'multiple_choice', '["Cercare solo prove a favore delle proprie tesi", "Confermare l''amicizia", "Essere d''accordo con tutti", "Avere sempre ragione"]', 0, 'È la tendenza a ignorare tutto ciò che contraddice le nostre convinzioni preesistenti.'),
('72DAC75F-905E-49A4-9095-C5F6E66C4272', 'Perché crediamo alle bufale che ci piacciono?', 'multiple_choice', '["Perché sono vere", "Perché il Bias di Conferma ce le fa sembrare plausibili", "Perché siamo stupidi", "Per caso"]', 1, 'Se una bugia conferma ciò che speriamo sia vero, tendiamo ad accettarla senza verifiche.'),
('72DAC75F-905E-49A4-9095-C5F6E66C4272', 'Cos''è il "Bias dell''Autorità"?', 'multiple_choice', '["Odiare la polizia", "Credere ciecamente a chi sembra esperto o potente", "Voler comandare", "Essere ribelli"]', 1, 'Online, basta un camice o un titolo falso per attivare questo bias.'),
('72DAC75F-905E-49A4-9095-C5F6E66C4272', 'Cos''è il Bias di Negatività?', 'multiple_choice', '["Essere pessimisti", "Il fatto che notiamo e ricordiamo più le cose negative di quelle positive", "Essere tristi", "Dire sempre no"]', 1, 'Evolutivamente utile per sopravvivere ai predatori, online ci fa notare solo le cattive notizie.');


-- Mission 2: Medio (0944F769-F053-4F71-9B10-9AFEAAB435EF)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '0944F769-F053-4F71-9B10-9AFEAAB435EF', 'CN', 'Bias e Social',
    'Come la tecnologia usa i nostri difetti contro di noi.',
    E'# Amplificatori di Bias\n\nI social non creano i bias, li amplificano.\n\nSe tendiamo a guardare gli incidenti stradali (curiosità morbosa), l''algoritmo ci mostrerà solo incidenti, facendoci credere che le strade siano un inferno (Bias di Disponibilità).',
    'medio', '10 min', 200, 'level_2', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('0944F769-F053-4F71-9B10-9AFEAAB435EF', 'Come l''algoritmo sfrutta il Confirmation Bias?', 'multiple_choice', '["Ti corregge", "Ti mostra esattamente ciò che vuoi vedere, rafforzando le tue convinzioni", "Ti cancella l''account", "Ti fa domande"]', 1, 'Fornendoti conferme continue, ti tiene gratificato e incollato allo schermo.'),
('0944F769-F053-4F71-9B10-9AFEAAB435EF', 'Cos''è l''Effetto Dunning-Kruger?', 'multiple_choice', '["Un film horror", "Meno sai, più pensi di sapere (e viceversa)", "Essere geni", "Avere paura del buio"]', 1, 'L''illusione di competenza di chi ignora la complessità di un argomento.'),
('0944F769-F053-4F71-9B10-9AFEAAB435EF', 'Cos''è il Bias di Disponibilità?', 'multiple_choice', '["Essere sempre liberi", "Giudicare la probabilità di un evento in base a quanto facilmente ce lo ricordiamo", "Avere tanta memoria", "Disponibilità economica"]', 1, 'Se vedi tre notizie di squali di fila, penserai che gli attacchi di squali siano comunissimi (anche se sono rari).'),
('0944F769-F053-4F71-9B10-9AFEAAB435EF', 'Cos''è il "Bandwagon Effect" (Effetto Carrozzone)?', 'multiple_choice', '["Andare in gita", "Fare qualcosa solo perché \"tutti lo fanno\"", "Ascoltare musica country", "Guidare un carro"]', 1, 'Spiega la viralità: se un post ha tanti like, tendiamo a metterlo anche noi.'),
('0944F769-F053-4F71-9B10-9AFEAAB435EF', 'Cos''è l''Illusione di Verità?', 'multiple_choice', '["Un gioco di prestigio", "Una bugia ripetuta tante volte inizia a sembrare vera", "Essere onesti", "Vedere miracoli"]', 1, 'Il nostro cervello confonde la familiarità con la verità.');


-- Mission 3: Difficile (EA95E72A-8D7B-437E-BB59-2AFA11DF8E79)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'EA95E72A-8D7B-437E-BB59-2AFA11DF8E79', 'CN', 'Pensiero Critico',
    'L''unica difesa contro i bias: rallentare e dubitare.',
    E'# System 1 vs System 2\n\nLo psicologo Kahneman divide il pensiero in:\n* **Sistema 1**: Veloce, istintivo, emotivo (Dove vivono i bias).\n* **Sistema 2**: Lento, logico, faticoso.\n\nPer difendersi, bisogna attivare volontariamente il Sistema 2.',
    'difficile', '15 min', 500, 'level_3', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('EA95E72A-8D7B-437E-BB59-2AFA11DF8E79', 'Come si applica il metodo scientifico nella vita quotidiana?', 'multiple_choice', '["Indossando un camice", "Cercando prove che *smentiscano* la nostra idea, non che la confermino", "Facendo esplosioni", "Guardando documentari"]', 1, 'La vera scienza cerca di falsificare le teorie, non solo di provarle.'),
('EA95E72A-8D7B-437E-BB59-2AFA11DF8E79', 'Cosa significa "Falsificabilità"?', 'multiple_choice', '["Dire bugie", "Una teoria è scientifica solo se esiste un modo per dimostrare che è falsa", "Creare soldi falsi", "Essere falsi"]', 1, 'Se una teoria non può essere smentita (es. "gli alieni invisibili ci controllano"), non è scienza.'),
('EA95E72A-8D7B-437E-BB59-2AFA11DF8E79', 'Qual è la domanda più potente contro i bias?', 'multiple_choice', '["Chi ha vinto?", "Perché?", "E se avessi torto?", "Quanto costa?"]', 2, 'Costringe il cervello a considerare scenari alternativi.'),
('EA95E72A-8D7B-437E-BB59-2AFA11DF8E79', 'Chi è l''Avvocato del Diavolo?', 'multiple_choice', '["Un legale costoso", "Qualcuno che argomenta contro la tesi prevalente per testarne la solidità", "Un nemico", "Un film"]', 1, 'È un ruolo fondamentale per evitare il pensiero di gruppo (Groupthink).'),
('EA95E72A-8D7B-437E-BB59-2AFA11DF8E79', 'Cosa fa il "Sistema 2" di Kahneman?', 'multiple_choice', '["Dorme", "Pensa velocemente", "È responsabile del pensiero lento, logico e calcolato", "Gestisce le emozioni"]', 2, 'È la nostra parte razionale, ma è pigra e va attivata con sforzo.');

-- 5. ASTI (AT) - Economia dell'Attenzione
-- Mission 1: Semplice (5CA8BD11-06C3-4C71-83EC-55B904FF30E8)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '5CA8BD11-06C3-4C71-83EC-55B904FF30E8', 'AT', 'Caccia al Click',
    'Il titolo non è la notizia. Scopri il Clickbait.',
    E'# Esca per Clic\n\n"NON CREDERAI MAI A COSA È SUCCESSO!"\n\nQuesto è **Clickbait**. Lo scopo non è informarti, ma farti cliccare per vedere la pubblicità nel sito. Spesso il contenuto delude o contraddice il titolo.',
    'semplice', '5 min', 100, 'level_1', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('5CA8BD11-06C3-4C71-83EC-55B904FF30E8', 'Cos''è il Clickbait?', 'multiple_choice', '["Un pesce", "Un titolo sensazionalistico progettato per attirare clic, spesso ingannevole", "Un software", "Una password"]', 1, 'Bait = Esca. Sei tu il pesce.'),
('5CA8BD11-06C3-4C71-83EC-55B904FF30E8', 'Perché i siti usano il Clickbait?', 'multiple_choice', '["Perché amano scrivere", "Per generare traffico e quindi guadagnare con le pubblicità visualizzate", "Per divertimento", "Per educare"]', 1, 'Più persone entrano nel sito, più banner pubblicitari vengono mostrati.'),
('5CA8BD11-06C3-4C71-83EC-55B904FF30E8', 'Quale elemento visivo è tipico delle miniature clickbait su YouTube?', 'multiple_choice', '["Paesaggi rilassanti", "Facce scioccate, frecce rosse e cerchi inutili", "Testo piccolo", "Nero totale"]', 1, 'Sfruttano la nostra naturale attrazione per le emozioni forti e i segnali di pericolo.'),
('5CA8BD11-06C3-4C71-83EC-55B904FF30E8', 'Se un titolo finisce con un punto interrogativo ("Gli alieni esistono?"), la risposta è quasi sempre...', 'multiple_choice', '["Sì", "No", "Forse", "42"]', 1, 'Legge di Betteridge sui titoli: se avessero le prove, lo scriverebbero come affermazione.'),
('5CA8BD11-06C3-4C71-83EC-55B904FF30E8', 'Cosa fare prima di condividere una notizia shock?', 'multiple_choice', '["Condividerla subito", "Leggere l''articolo e non solo il titolo", "Urlarlo", "Niente"]', 1, 'Spesso il testo smentisce o ridimensiona drasticamente il titolo.');


-- Mission 2: Medio (261C6CA9-55CD-4D94-A1DD-564EC1CD5DE3)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '261C6CA9-55CD-4D94-A1DD-564EC1CD5DE3', 'AT', 'Viralità Emotiva',
    'La rabbia viaggia più veloce della verità.',
    E'# Rabbia Virale\n\nLe emozioni non viaggiano tutte alla stessa velocità.\n\nLa **Rabbia** è l''emozione più virale in assoluto. Un post che ti fa arrabbiare ha il 30% di probabilità in più di essere condiviso rispetto a uno che ti rende felice.',
    'medio', '10 min', 200, 'level_2', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('261C6CA9-55CD-4D94-A1DD-564EC1CD5DE3', 'Quale emozione rende un contenuto più virale?', 'multiple_choice', '["Tristezza", "Noia", "Rabbia/Indignazione", "Calma"]', 2, 'L''indignazione spinge all''azione (commentare, condividere), la contentezza spesso no.'),
('261C6CA9-55CD-4D94-A1DD-564EC1CD5DE3', 'Cos''è l''"Hate-clicking"?', 'multiple_choice', '["Cliccare col naso", "Cliccare su qualcosa solo perché ci fa arrabbiare o per criticarlo", "Cliccare veloci", "Rompere il mouse"]', 1, 'Ironia della sorte, questo regala visite e soldi proprio a chi odiamo.'),
('261C6CA9-55CD-4D94-A1DD-564EC1CD5DE3', 'Perché le buone notizie diventano raramente virali?', 'multiple_choice', '["La gente è cattiva", "Non attivano lo stesso livello di urgenza (\"Arousal\") fisiologica", "Sono noiose", "Non esistono"]', 1, 'Siamo programmati per reagire alle minacce (negative) più che alle opportunità.'),
('261C6CA9-55CD-4D94-A1DD-564EC1CD5DE3', 'Perché gli algoritmi premiano i litigi nei commenti?', 'multiple_choice', '["Perché amano il drama", "Perché ogni commento conta come \"Engagement\", segnalando che il post è interessante", "Per sbaglio", "Per punizione"]', 1, 'Per l''algoritmo, Amore e Odio sono uguali: entrambi sono "Tempo speso sull''app".'),
('261C6CA9-55CD-4D94-A1DD-564EC1CD5DE3', 'Cosa fanno spesso gli influencer per ottenere visibilità facile?', 'multiple_choice', '["Studiano", "Creano polemiche artificiali (Rage baiting)", "Dormono", "Leggono libri"]', 1, 'Dire cose appositamente stupide o offensive per generare una marea di commenti di correzione.');


-- Mission 3: Difficile (10C5C3EA-1EC7-4155-9A23-4EED0E13B642)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '10C5C3EA-1EC7-4155-9A23-4EED0E13B642', 'AT', 'Doomscrolling',
    'Affogare nelle cattive notizie. Come fermarsi.',
    E'# La fine del mondo (nel tuo telefono)\n\nTi è mai capitato di passare ore a leggere una notizia catastrofica dopo l''altra?\n\nSi chiama **Doomscrolling**. Ci illudiamo che "sapere tutto" ci dia controllo, ma in realtà ci paralizza solo nella paura.',
    'difficile', '15 min', 500, 'level_3', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('10C5C3EA-1EC7-4155-9A23-4EED0E13B642', 'Cos''è il Doomscrolling?', 'multiple_choice', '["Un ballo", "Scorrere compulsivamente cattive notizie", "Giocare a Doom", "Leggere fumetti"]', 1, 'Doom = Rovina. È una spirale di ansia autodistruttiva.'),
('10C5C3EA-1EC7-4155-9A23-4EED0E13B642', 'Che effetto ha sulla salute mentale?', 'multiple_choice', '["Rilassante", "Aumenta ansia, depressione e senso di impotenza", "Migliora il sonno", "Nessuno"]', 1, 'Il cervello non è fatto per elaborare tragedie globali 24 ore su 24.'),
('10C5C3EA-1EC7-4155-9A23-4EED0E13B642', 'Il mondo è davvero pericoloso come sembra online?', 'multiple_choice', '["Sì", "No, questa è la \"Sindrome del Mondo Cattivo (Mean World Syndrome)\"", "Peggio", "Non esiste il mondo"]', 1, 'I crimini violenti sono in calo da decenni, ma la loro visibilità mediatica è aumentata.'),
('10C5C3EA-1EC7-4155-9A23-4EED0E13B642', 'Cosa fare se ti accorgi di farlo?', 'multiple_choice', '["Continuare", "Interrompere fisicamente (alzarsi, bere acqua) e disconnettersi", "Piangere", "Condividere"]', 1, 'Bisogna rompere lo stato di trance ipnotica.'),
('10C5C3EA-1EC7-4155-9A23-4EED0E13B642', 'Come curare il proprio feed?', 'multiple_choice', '["Smettere di seguire account ansiogeni o catastrofisti", "Non seguire nessuno", "Seguire solo bot", "Guardare il muro"]', 0, 'Siamo ciò che mangiamo (digitalmente). Scegli una dieta sana.');


-- 6. ALESSANDRIA (AL) - I Tuoi Dati (Privacy)
-- Mission 1: Semplice (66BA90F1-DFA6-43A7-8F8C-AAF8128D4A22)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '66BA90F1-DFA6-43A7-8F8C-AAF8128D4A22', 'AL', 'Le Tracce che Lasci',
    'Pollicino digitale: ogni clic è una briciola che lasci dietro di te.',
    E'# Non sei invisibile\n\nAnche se non posti nulla, lasci tracce ovunque:\n* Cosa cerchi\n* Dove vai (GPS)\n* Quanto ti fermi su una foto\n\nQueste tracce formano la tua **Impronta Digitale**.',
    'semplice', '5 min', 100, 'level_1', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('66BA90F1-DFA6-43A7-8F8C-AAF8128D4A22', 'Cosa sono i Cookie web?', 'multiple_choice', '["Biscotti dolci", "Piccoli file che i siti salvano sul tuo dispositivo per ricordarsi di te", "Virus", "Immagini"]', 1, 'Servono a tenerti loggato, ma anche a tracciare cosa guardi per la pubblicità.'),
('66BA90F1-DFA6-43A7-8F8C-AAF8128D4A22', 'Chi sa dove ti trovi ora?', 'multiple_choice', '["Nessuno", "Probabilmente Google, il tuo operatore telefonico e molte app con accesso GPS", "Solo mia mamma", "Il papa"]', 1, 'La geolocalizzazione è uno dei dati più preziosi e venduti.'),
('66BA90F1-DFA6-43A7-8F8C-AAF8128D4A22', 'La cronologia in incognito impedisce al provider internet di vedere cosa fai?', 'multiple_choice', '["Sì", "No, nasconde i dati solo sul tuo computer locale, non alla rete", "Forse", "Dipende"]', 1, 'L''ISP (Gestore telefonico) vede comunque tutto il traffico non criptato.'),
('66BA90F1-DFA6-43A7-8F8C-AAF8128D4A22', 'Cosa contengono spesso i "Metadati" di una foto?', 'multiple_choice', '["Solo i colori", "Data, ora, modello del telefono e spesso COORDINATE GPS precise", "Il nome del soggetto", "Il futuro"]', 1, 'Postare una foto originale può rivelare l''indirizzo di casa tua.'),
('66BA90F1-DFA6-43A7-8F8C-AAF8128D4A22', 'Cosa succede quando fai "Accedi con Google" su un altro sito?', 'multiple_choice', '["Risparmi tempo e Google condivide alcuni tuoi dati con quel sito", "Non succede nulla", "Vinci un premio", "Il sito diventa di Google"]', 0, 'Comodo, ma centralizzi ancora di più la tua vita digitale in un''unica mano.');


-- Mission 2: Medio (B13F1480-7CCD-4120-B8BA-A268EC3892DE)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'B13F1480-7CCD-4120-B8BA-A268EC3892DE', 'AL', 'Big Data & Targeting',
    'Come predicono il futuro (e i tuoi acquisti).',
    E'# Sanno cosa vuoi prima di te\n\nIncrociando i dati (Data Brokers), le aziende possono predire:\n* Se sei incinta\n* Se stai per divorziare\n* Se hai una malattia\n\nTutto questo **prima** che tu lo dica a qualcuno.',
    'medio', '10 min', 200, 'level_2', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('B13F1480-7CCD-4120-B8BA-A268EC3892DE', 'Cos''è il Micro-Targeting?', 'multiple_choice', '["Sparare a bersagli piccoli", "Mostrare pubblicità specifiche a gruppi ristrettissimi di persone (es. Donne di novara che amano i gatti)", "Usare piccoli schermi", "Marketing per insetti"]', 1, 'Permette di manipolare l''opinione facendo leva sulle debolezze specifiche di ciascuno.'),
('B13F1480-7CCD-4120-B8BA-A268EC3892DE', 'Cosa fanno i Data Brokers?', 'multiple_choice', '["Vendono case", "Comprano, aggregano e rivendono i tuoi dati personali", "Rompano dati", "Organizzano feste"]', 1, 'Sono aziende miliardarie di cui nessuno conosce il nome, che commerciano la tua vita.'),
('B13F1480-7CCD-4120-B8BA-A268EC3892DE', 'Il caso Cambridge Analytica ha dimostrato che...', 'multiple_choice', '["I dati Facebook possono essere usati per influenzare le elezioni", "Facebook è sicuro", "Gli inglesi sono bravi", "Nulla"]', 0, 'Usarono i dati per creare profili psicologici e bombardare gli elettori indecisi con messaggi mirati.'),
('B13F1480-7CCD-4120-B8BA-A268EC3892DE', 'Cos''è il "Privacy Paradox"?', 'multiple_choice', '["Un film", "Tutti dicono di tenere alla privacy, ma poi regalano i dati per usare app gratis", "Un paradosso temporale", "Un errore"]', 1, 'Comportamento incoerente tra ciò che diciamo e ciò che facciamo.'),
('B13F1480-7CCD-4120-B8BA-A268EC3892DE', 'Quali dati sono più sensibili?', 'multiple_choice', '["Colore preferito", "Sanitari e Finanziari", "Musica ascoltata", "Nome del cane"]', 1, 'Possono determinare se otterrai un prestito o un''assicurazione sulla vita.');


-- Mission 3: Difficile (DCD0BF19-FC3C-49DD-98A3-660FA1F23FD8)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'DCD0BF19-FC3C-49DD-98A3-660FA1F23FD8', 'AL', 'Difesa della Privacy',
    'Minimizzare l''impronta digitale. Strumenti pratici.',
    E'# Diventa un Fantasma (o quasi)\n\nNon puoi sparire, ma puoi ridurre il danno.\n1.  **VPN**: Nasconde la tua origine.\n2.  **AdBlock**: Blocca chi ti spia.\n3.  **Consapevolezza**: Se non serve, non darlo.',
    'difficile', '15 min', 500, 'level_3', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('DCD0BF19-FC3C-49DD-98A3-660FA1F23FD8', 'Cosa fa realmente una VPN?', 'multiple_choice', '["Ti rende un hacker", "Cripta il traffico tra te e il server VPN, nascondendo il tuo IP ai siti visitati", "Velocizza il PC", "Ti regala internet"]', 1, 'Protegge la tua privacy dall''ISP e dai siti, ma la VPN stessa potrebbe vedere i tuoi dati (scegline una fidata!).'),
('DCD0BF19-FC3C-49DD-98A3-660FA1F23FD8', 'Quali browser sono noti per la privacy?', 'multiple_choice', '["Chrome", "Firefox e Brave", "Internet Explorer", "Nessuno"]', 1, 'Hanno blocchi anti-tracciamento integrati di default.'),
('DCD0BF19-FC3C-49DD-98A3-660FA1F23FD8', 'Perché bloccare i tracker?', 'multiple_choice', '["Perché sono noiosi", "Per impedire alle aziende di costruire un profilo su di te mentre navighi", "Per risparmiare batteria", "Per vedere meglio"]', 1, 'I tracker invisibili sono su quasi tutti i siti commerciali.'),
('DCD0BF19-FC3C-49DD-98A3-660FA1F23FD8', 'Perché dovresti (idealmente) leggere la Privacy Policy?', 'multiple_choice', '["È divertente", "Per sapere come useranno i tuoi dati (es. se li vendono a terzi)", "Per imparare l''inglese", "Non serve"]', 1, 'Spesso nascondono clausole inquietanti su proprietà dei contenuti e cessione dati.'),
('DCD0BF19-FC3C-49DD-98A3-660FA1F23FD8', 'Cos''è il "Diritto all''oblio"?', 'multiple_choice', '["Dimenticare le cose", "Il diritto di chiedere a Google di rimuovere risultati vecchi e non più rilevanti su di te", "Perdere la memoria", "Un film"]', 1, 'Fondamentale per non essere perseguitati a vita da un errore o evento del passato.');


-- 7. BIELLA (BI) - Dark Patterns
-- Mission 1: Semplice (D9341B6A-1408-4043-BB0B-37AA40EB07C6)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'D9341B6A-1408-4043-BB0B-37AA40EB07C6', 'BI', 'Trappole nel Design',
    'Non hai cliccato per sbaglio, era disegnato così. Scopri i Dark Patterns.',
    E'# Design Disobbediente\n\nHai mai provato a cancellarti da un servizio e non trovavi il tasto?\n\nNon sei stupido. È un **Dark Pattern**: un''interfaccia progettata apposta per ingannarti o renderti difficile fare ciò che vuoi (se va contro l''interesse dell''azienda).',
    'semplice', '5 min', 100, 'level_1', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('D9341B6A-1408-4043-BB0B-37AA40EB07C6', 'Cos''è un Dark Pattern?', 'multiple_choice', '["Un disegno scuro", "Un''interfaccia utente progettata per ingannare o manipolare l''utente", "Un tema notturno", "Un virus"]', 1, 'Usa la psicologia contro di te.'),
('D9341B6A-1408-4043-BB0B-37AA40EB07C6', 'Dove si trova spesso la "X" per chiudere una pubblicità nei giochi mobile?', 'multiple_choice', '["Grande al centro", "Minuscola, nascosta o ritardata in un angolo", "Non c''è", "Lampeggia"]', 1, 'Fatta apposta per farti sbagliare e cliccare sulla pubblicità.'),
('D9341B6A-1408-4043-BB0B-37AA40EB07C6', 'Come usano i colori per ingannarti?', 'multiple_choice', '["A caso", "Verde/Grande per l''opzione che vogliono loro (anche se a pagamento), Grigio/Piccolo per il rifiuto", "Tutto nero", "Arcobaleno"]', 1, 'Il cervello associa Grassetto/Colorato a "Giusto/Avanti".'),
('D9341B6A-1408-4043-BB0B-37AA40EB07C6', 'Cos''è una "domanda a doppia negazione"?', 'multiple_choice', '["Una bugia", "Formulare una frase in modo confuso (\"Non deselezionare se non vuoi...\") per farti accettare per sbaglio", "Parlare due lingue", "Fare domande difficili"]', 1, 'Sfruttano la fretta per farti dire sì quando volevi dire no.'),
('D9341B6A-1408-4043-BB0B-37AA40EB07C6', 'Cos''è il "Roach Motel" (Trappola per scarafaggi)?', 'multiple_choice', '["Un hotel sporco", "Entrare (iscriversi) è facilissimo, uscire (cancellarsi) è quasi impossibile", "Un gioco", "Una casa"]', 1, 'Iscrizione: 1 click. Cancellazione: Chiamare un numero verde in orario d''ufficio in Islanda.');


-- Mission 2: Medio (091FB79B-350D-4CBB-864C-4C323DBE4402)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '091FB79B-350D-4CBB-864C-4C323DBE4402', 'BI', 'Pressione Psicologica',
    '"Solo 2 stanze rimaste!". Come ti mettono fretta.',
    E'# Falsa Urgenza\n\nI siti di prenotazione sono i maestri della **Scarcity** (Scarsità).\n\n"Altri 10 utenti stanno guardando questa stanza!"\nSpesso è algoritmicamente generato per crearti ansia e farti comprare d''impulso senza pensare.',
    'medio', '10 min', 200, 'level_2', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('091FB79B-350D-4CBB-864C-4C323DBE4402', 'Cos''è il principio di Scarcity (Scarsità)?', 'multiple_choice', '["Essere poveri", "La paura che un''opportunità finisca ci spinge a prenderla subito", "Avere fame", "Pochi amici"]', 1, 'Se pensiamo che una cosa sia rara, il suo valore percepito aumenta.'),
('091FB79B-350D-4CBB-864C-4C323DBE4402', 'Cosa sono i Countdown nei siti e-commerce?', 'multiple_choice', '["Un orologio", "Spesso timer falsi che ricominciano da capo per creare urgenza artificiale (Urgency)", "Cronometri", "Bombe"]', 1, 'L''urgenza disattiva il pensiero critico e razionale.'),
('091FB79B-350D-4CBB-864C-4C323DBE4402', 'Cos''è la "Social Proof" (Riprova Sociale) usata male?', 'multiple_choice', '["Essere socievoli", "Dire \"100 persone hanno comprato\" per farti sentire sicuro a seguire il gregge", "Prove in tribunale", "Social network"]', 1, 'Ci fidiamo ciecamente della massa.'),
('091FB79B-350D-4CBB-864C-4C323DBE4402', 'Cos''è il "Confirmshaming"?', 'multiple_choice', '["Vergogna di confermare", "Usare testi manipolatori nei pulsanti di rifiuto (es. \"No, voglio rimanere ignorante\")", "Essere timidi", "Confermare tutto"]', 1, 'Cerca di farti sentire in colpa o stupido se non accetti l''offerta.'),
('091FB79B-350D-4CBB-864C-4C323DBE4402', 'Meglio Opt-in o Opt-out?', 'multiple_choice', '["Opt-in (Devo cliccare per accettare)", "Opt-out (È già accettato, devo cliccare per togliere)", "Uguale", "Non so"]', 0, 'L''Opt-out sfrutta la pigrizia: la gente tende a lasciare le impostazioni predefinite.');


-- Mission 3: Difficile (09D861CA-FF30-4CDD-928B-3D63713C8E9B)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '09D861CA-FF30-4CDD-928B-3D63713C8E9B', 'BI', 'Difendersi dai Pattern',
    'Riconoscere per non cascarci. Design etico vs ingannevole.',
    E'# Occhi Aperti\n\nOra che li conosci, li vedrai ovunque.\n\nLa difesa migliore è **leggere tutto**. Se un sito insiste troppo, mente.\nAttenzione anche ai costi nascosti che appaiono solo alla fine (Drip Pricing).',
    'difficile', '15 min', 500, 'level_3', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('09D861CA-FF30-4CDD-928B-3D63713C8E9B', 'Qual è la regola numero uno?', 'multiple_choice', '["Cliccare veloce", "Leggere sempre tutto prima di cliccare, specialmente le scritte piccole", "Fidarsi", "Chiudere gli occhi"]', 1, 'I Dark Patterns si nascondono nei dettagli.'),
('09D861CA-FF30-4CDD-928B-3D63713C8E9B', 'Cos''è il "Drip Pricing"?', 'multiple_choice', '["Prezzi gocciolanti", "Mostrare un prezzo basso all''inizio e aggiungere tasse/costi extra solo alla fine", "Prezzi liquidi", "Sconti"]', 1, 'Sfrutta il fatto che, arrivato al pagamento, hai già investito tempo e sei mentale "impegnato" all''acquisto.'),
('09D861CA-FF30-4CDD-928B-3D63713C8E9B', 'Come funzionano gli Abbonamenti Nascosti?', 'multiple_choice', '["Sono invisibili", "Ti offrono un prodotto  \"gratis\" pagando solo la spedizione, ma nelle condizioni c''è un abbonamento mensile", "Magia", "Regali"]', 1, 'Le truffe delle "creme gratis" o "iPhone a 1€" funzionano così.'),
('09D861CA-FF30-4CDD-928B-3D63713C8E9B', 'Cosa puoi fare se trovi un Dark Pattern grave?', 'multiple_choice', '["Niente", "Segnalarlo alle autorità o sui social (Name & Shame)", "Riderci su", "Comprarlo"]', 1, 'La cattiva pubblicità è l''unica cosa che le aziende temono davvero.'),
('09D861CA-FF30-4CDD-928B-3D63713C8E9B', 'Cos''è il "Design Etico"?', 'multiple_choice', '["Design costoso", "Progettare interfacce che rispettano l''utente e la sua volontà, senza inganni", "Design brutto", "Legge"]', 1, 'Il futuro della tecnologia deve essere trasparente.');


-- 8. VERBANO-CUSIO-OSSOLA (VB) - Digital Wellbeing
-- Mission 1: Semplice (C21C4634-17E7-43A9-ADB5-5D0E635AD338)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'C21C4634-17E7-43A9-ADB5-5D0E635AD338', 'VB', 'Sintomi di Overdose',
    'Quando è troppo? Ansia, insonnia e isolamento.',
    E'# Sei connesso o posseduto?\n\nLa tecnologia è uno strumento meraviglioso, ma l''abuso ha costi fisici e mentali:\n* Insonnia (Luce blu)\n* Ansia da notifica\n* Problemi di postura (Text Neck)\n\nRiconoscere i sintomi è il primo passo.',
    'semplice', '5 min', 100, 'level_1', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('C21C4634-17E7-43A9-ADB5-5D0E635AD338', 'Cos''è lo "Screen Time"?', 'multiple_choice', '["Un orologio", "Il tempo totale passato davanti a uno schermo", "Un film", "Tempo libero"]', 1, 'Monitorarlo nelle impostazioni ti dà la misura reale della tua dipendenza.'),
('C21C4634-17E7-43A9-ADB5-5D0E635AD338', 'Perché usare il cellulare a letto rovina il sonno?', 'multiple_choice', '["Fa rumore", "La luce blu degli schermi inibisce la melatonina, l''ormone del sonno", "Fa caldo", "Esplode"]', 1, 'Inganna il cervello facendogli credere che sia ancora giorno.'),
('C21C4634-17E7-43A9-ADB5-5D0E635AD338', 'Cos''è la "Phantom Vibration Syndrome"?', 'multiple_choice', '["Un fantasma", "Credere di aver sentito vibrare il telefono quando non è successo", "Un ballo", "Un superpotere"]', 1, 'Mostra quanto il nostro cervello sia iper-allerta e in attesa costante di notifiche.'),
('C21C4634-17E7-43A9-ADB5-5D0E635AD338', 'Cosa succede alla vista se guardi schermi vicini per ore?', 'multiple_choice', '["Diventa super", "Affaticamento oculare digitale e miopia transitoria", "Si colora di blu", "Niente"]', 1, 'Gli occhi non sono evoluti per fissare una luce artificiale a 20cm di distanza tutto il giorno.'),
('C21C4634-17E7-43A9-ADB5-5D0E635AD338', 'Cos''è il "Phubbing"?', 'multiple_choice', '["Un pub", "Snobbare la persona con cui sei per guardare il telefono (Phone + Snubbing)", "Un hobby", "Correre"]', 1, 'Danneggia le relazioni reali facendo sentire l''altro meno importante di una notifica.');


-- Mission 2: Medio (815C454C-3ACC-4B13-B718-7F27F0B63250)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '815C454C-3ACC-4B13-B718-7F27F0B63250', 'VB', 'JOMO vs FOMO',
    'La gioia di perdersi le cose. Essere presenti qui e ora.',
    E'# JOMO: Joy Of Missing Out\n\nL''antidoto alla FOMO è la **JOMO**: la gioia di disconnettersi.\n\nNon devi sapere tutto quello che fanno gli altri. Essere presenti nel momento, senza distrazioni, aumenta la qualità della vita e riduce l''ansia.',
    'medio', '10 min', 200, 'level_2', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('815C454C-3ACC-4B13-B718-7F27F0B63250', 'Cosa significa JOMO?', 'multiple_choice', '["Joy Of Missing Out (Gioia di perdersi le cose)", "Jump On My Owl", "Just One More", "Niente"]', 0, 'È il piacere di godersi il momento presente senza preoccuparsi di cosa succede online.'),
('815C454C-3ACC-4B13-B718-7F27F0B63250', 'Cos''è la Mindfulness digitale?', 'multiple_choice', '["Un''app", "Usare la tecnologia con intenzione e consapevolezza, non per automatismo", "Dormire", "Pregare"]', 1, 'Chiedersi: "Ho preso il telefono perché mi serve o perché mi annoiavo?".'),
('815C454C-3ACC-4B13-B718-7F27F0B63250', 'Il Multitasking (fare più cose insieme) funziona?', 'multiple_choice', '["Sì, benissimo", "No, il cervello fa solo \"Task Switching\" rapido, riducendo l''efficienza e aumentando lo stress", "Solo per le donne", "Solo per i giovani"]', 1, 'Siamo mono-tasking. Fare più cose insieme abbassa il QI momentaneo più della marijuana.'),
('815C454C-3ACC-4B13-B718-7F27F0B63250', 'A cosa serve la modalità "Non Disturbare"?', 'multiple_choice', '["A dormire", "A bloccare le notifiche per concentrarsi su ciò che conta", "A spegnere il telefono", "A nulla"]', 1, 'Riprendi il controllo della tua attenzione.'),
('815C454C-3ACC-4B13-B718-7F27F0B63250', 'Perché dovresti disattivare le notifiche non essenziali?', 'multiple_choice', '["Per risparmiare batteria", "Per non essere interrotto ogni 5 minuti da cose inutili", "Perché costano", "Perché sì"]', 1, 'Ogni "ding" rompe il flusso di concentrazione, che richiede 20 minuti per tornare.');


-- Mission 3: Difficile (1375D7DE-FE2D-46F6-9EB2-952A8024A834)
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '1375D7DE-FE2D-46F6-9EB2-952A8024A834', 'VB', 'Dieta Digitale',
    'Strategie di controllo per tornare padroni del proprio tempo.',
    E'# Riprenditi la vita\n\nNon devi buttare il telefono, devi domarlo.\n\nStrategie:\n1.  **Nudging**: Sposta le app social in cartelle scomode.\n2.  **Bianco e Nero**: Rende lo schermo meno attraente (meno dopamina).\n3.  **Zone Phone-free**: Mai a tavola, mai a letto.',
    'difficile', '15 min', 500, 'level_3', 'Piemonte', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('1375D7DE-FE2D-46F6-9EB2-952A8024A834', 'Cosa significa "Nudging" su se stessi?', 'multiple_choice', '["Darsi pizzicotti", "Modificare l''ambiente per rendere le cattive abitudini più difficili (es. nascondere l''icona di Instagram)", "Mangiare noci", "Correre nudi"]', 1, 'Se devi fare 5 clic per aprire TikTok, lo aprirai meno spesso.'),
('1375D7DE-FE2D-46F6-9EB2-952A8024A834', 'Perché impostare lo schermo in scala di grigi aiuta?', 'multiple_choice', '["Fa vintage", "Rende il telefono visivamente noioso, riducendo la stimolazione della dopamina", "Risparmia batteria", "È rotto"]', 1, 'Le app colorate sembrano caramelle per il cervello. In grigio sono solo strumenti.'),
('1375D7DE-FE2D-46F6-9EB2-952A8024A834', 'Cos''è una "Phone-free zone"?', 'multiple_choice', '["Un negozio", "Un''area della casa (es. camera da letto) dove il telefono è vietato", "Una zona senza campo", "Un carcere"]', 1, 'Crea santuari di pace dove la tecnologia non può entrare.'),
('1375D7DE-FE2D-46F6-9EB2-952A8024A834', 'Cos''è un "Digital Detox"?', 'multiple_choice', '["Una dieta liquida", "Un periodo di tempo (giorno/weekend) in cui ci si astiene completamente dalla tecnologia", "Pulire lo schermo", "Formattare il PC"]', 1, 'Serve a resettare il sistema nervoso e riscoprire la noia (che porta creatività).'),
('1375D7DE-FE2D-46F6-9EB2-952A8024A834', 'L''obiettivo finale è...', 'multiple_choice', '["Vivere nelle caverne", "Usare la tecnologia come un servo, non come un padrone", "Diventare un robot", "Distruggere internet"]', 1, 'La tecnologia è ottima se usata con intenzione per migliorare la vita, terribile se usata per automatismo.');