-- Mission Seed for Lombardia Part 1a (MI, BG, BS)
-- Generated by Antigravity

-- 1. MILANO (MI) - High Finance & Corporate (CEO Fraud & BEC)

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '57FBEAD6-8113-4D5E-94CA-ED3E2F987D49', 'MI', 'L''Urgenza del Capo',
    'Il CEO ha bisogno di un bonifico urgente. O forse no?',
    E'# Business Email Compromise (BEC)\n\nLa truffa preferita contro le aziende.\n\nRicevi una mail dal "CEO" o da un fornitore noto.\nChiede un **pagamento urgente** e **confidenziale** su un nuovo IBAN.\n\nSembra tutto vero (logo, firma), ma è una trappola da milioni di euro.',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('57FBEAD6-8113-4D5E-94CA-ED3E2F987D49', 'Qual è l''elemento chiave di una truffa BEC?', 'multiple_choice', '["Un virus", "L''urgenza e l''autorità (fingersi un capo)", "Un sito porno", "Un principe nigeriano"]', 1, 'Sfruttano la paura di dire di no a un superiore.'),
('57FBEAD6-8113-4D5E-94CA-ED3E2F987D49', 'Cosa fare se il CEO ti chiede un bonifico urgente via mail?', 'multiple_choice', '["Farlo subito", "Ignorarlo", "Verificare con un altro canale (chiamata, SMS, di persona)", "Chiedere un aumento"]', 2, 'Non rispondere alla mail. Chiama il numero che hai in rubrica (non quello nella mail!).'),
('57FBEAD6-8113-4D5E-94CA-ED3E2F987D49', 'Perché spesso queste mail arrivano il venerdì pomeriggio?', 'multiple_choice', '["Lavorano di più", "Per metterti fretta prima del weekend e impedirti di verificare", "Perché le banche sono chiuse", "Casuale"]', 1, 'Sanno che vuoi andare a casa e abbasserai la guardia.'),
('57FBEAD6-8113-4D5E-94CA-ED3E2F987D49', 'Come fanno ad avere il logo dell''azienda?', 'multiple_choice', '["Sono dipendenti", "Lo scaricano dal sito pubblico (Google Images)", "Lo disegnano", "Magia"]', 1, 'È facilissimo clonare l''aspetto visivo di una mail.'),
('57FBEAD6-8113-4D5E-94CA-ED3E2F987D49', 'L''indirizzo mail "ceo@conpany.com" è sospetto?', 'multiple_choice', '["No", "Sì, c''è un errore di battitura (Typosquatting: ''n'' invece di ''m'')", "Dipende", "Forse"]', 1, 'Guarda sempre attentamente il mittente.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '670AEF3B-213C-40E0-A0AF-981087218BFA', 'MI', 'Verifica l''IBAN',
    'Un fornitore ha cambiato banca all''improvviso. Ti fidi?',
    E'# Il "Man-in-the-Middle"\n\nGli hacker entrano nella casella mail di un tuo fornitore reale.\nAspettano che lui ti mandi una fattura vera.\nIntercettano la mail e **cambiano solo l''IBAN** sul PDF.\n\nTu paghi il fornitore, ma i soldi vanno alle Cayman.',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('670AEF3B-213C-40E0-A0AF-981087218BFA', 'Se un fornitore comunica un cambio IBAN via mail, cosa fai?', 'multiple_choice', '["Aggiorni l''anagrafica", "Fai il bonifico", "Chiami il fornitore al telefono per conferma vocale", "Mandi un fax"]', 2, 'È l''unica procedura sicura. Mai fidarsi solo della mail.'),
('670AEF3B-213C-40E0-A0AF-981087218BFA', 'Cos''è l''attacco Man-in-the-Middle?', 'multiple_choice', '["Un gioco", "Qualcuno che ascolta e modifica segretamente le comunicazioni tra due parti", "Un arbitro", "Un virus"]', 1, 'Come un postino che apre le lettere, cambia il contenuto e le richiude.'),
('670AEF3B-213C-40E0-A0AF-981087218BFA', 'Perché i filtri antispam non bloccano queste mail?', 'multiple_choice', '["Sono rotti", "Spesso partono da account mail reali che sono stati violati", "Costano troppo", "Sono pigri"]', 1, 'La mail è tecnicamente legittima, è il contenuto ad essere fraudolento.'),
('670AEF3B-213C-40E0-A0AF-981087218BFA', 'Qual è un segnale d''allarme nelle fatture?', 'multiple_choice', '["Importo corretto", "Font o formattazione leggermente diversi dal solito, o errori grammaticali", "Data giusta", "Logo giusto"]', 1, 'Spesso i criminali modificano i PDF in fretta e male.'),
('670AEF3B-213C-40E0-A0AF-981087218BFA', 'Cosa fare se hai già pagato?', 'multiple_choice', '["Niente", "Contattare subito la banca per tentare il recall del bonifico e denunciare", "Aspettare", "Chiedere scusa"]', 1, 'Il tempo è denaro. Dopo 24-48 ore i soldi sono spariti.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '38F60C02-9DD6-47FF-8BB4-A82A7E618D44', 'MI', 'La Grande Frode',
    'Analisi approfondita della "CEO Fraud". Come difendersi.',
    E'# La Psicologia della Truffa\n\nNon usano virus, usano la psicologia.\n\nLe 4 armi della BEC:\n1.  **Autorità** (È il capo)\n2.  **Urgenza** (Fallo ORA)\n3.  **Segretezza** (Non dirlo a nessuno, è un''acquisizione segreta)\n4.  **Lusinga** (Mi fido solo di te per questo compito)',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('38F60C02-9DD6-47FF-8BB4-A82A7E618D44', 'Cos''è il "Deepfake Audio" in questo contesto?', 'multiple_choice', '["Musica", "Usare l''AI per clonare la voce del CEO e chiamare il dipendente", "Un podcast", "Un errore"]', 1, 'Nuova frontiera: non solo mail, ora ti chiamano con la voce del capo.'),
('38F60C02-9DD6-47FF-8BB4-A82A7E618D44', 'Quale procedura aziendale blocca queste truffe?', 'multiple_choice', '["Doppia firma per bonifici sopra una certa soglia", "Fiducia cieca", "Bonifici veloci", "Nessuna"]', 0, 'Se servono due persone per autorizzare un pagamento, l''ingegneria sociale è molto più difficile.'),
('38F60C02-9DD6-47FF-8BB4-A82A7E618D44', 'Perché chiedono "Discrezione"?', 'multiple_choice', '["Sono timidi", "Per isolare la vittima e impedire che si confronti con i colleghi", "Per educazione", "Per legge"]', 1, 'L''isolamento favorisce la manipolazione.'),
('38F60C02-9DD6-47FF-8BB4-A82A7E618D44', 'Chi è il bersaglio ideale (Target)?', 'multiple_choice', '["Chiunque", "Dipartimento amministrativo/finanziario (CFO, contabili)", "Il portiere", "Lo stagista"]', 1, 'Cercano chi ha i "poteri di firma" o accesso ai conti.'),
('38F60C02-9DD6-47FF-8BB4-A82A7E618D44', 'L''autenticazione a due fattori (2FA) sulla mail aiuta?', 'multiple_choice', '["No", "Sì, rende molto più difficile per gli hacker violare la casella mail del CEO per lanciare l''attacco", "Forse", "Solo su Instagram"]', 1, 'Proteggere l''account sorgente è la prima difesa.');


-- 2. BERGAMO (BG) - Industrial Security (Ransomware)

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '23BA659E-DA4F-49E8-9C71-552FA69CE374', 'BG', 'Azienda in Ostaggio',
    'Tutti i file sono criptati. Pagare o non pagare?',
    E'# Ransomware: Il rapimento digitale\n\nUn virus cripta tutti i documenti dell''azienda.\nSullo schermo appare un conto alla rovescia: "Paga 50.000€ in Bitcoin o perderai tutto".\n\nBergamo, cuore produttivo, è un bersaglio primario.',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('23BA659E-DA4F-49E8-9C71-552FA69CE374', 'Cosa fa un Ransomware?', 'multiple_choice', '["Ruba il mouse", "Cifra i file rendendoli illeggibili e chiede un riscatto", "Spegne il PC", "Formatta il disco"]', 1, 'Prende i dati "in ostaggio".'),
('23BA659E-DA4F-49E8-9C71-552FA69CE374', 'Bisogna pagare il riscatto?', 'multiple_choice', '["Sì, subito", "No, mai", "Solo se poco", "Chiedi alla mamma"]', 1, 'Pagare finanzia il crimine e non garantisce che ti ridiano i dati (o che non tornino tra un mese).'),
('23BA659E-DA4F-49E8-9C71-552FA69CE374', 'Come entra di solito un Ransomware?', 'multiple_choice', '["Dalla finestra", "Allegato mail infetto o credenziali RDP deboli", "Dalla presa elettrica", "Dal WiFi pubblico"]', 1, 'Spesso basta un click sbagliato su una "Fattura.exe".'),
('23BA659E-DA4F-49E8-9C71-552FA69CE374', 'Qual è l''unica vera cura?', 'multiple_choice', '["Antivirus gratis", "Backup offline (o immutabile) recente", "Pregare", "Chiamare la polizia"]', 1, 'Se hai il backup, formatti tutto e ripristini senza pagare un euro.'),
('23BA659E-DA4F-49E8-9C71-552FA69CE374', 'In che valuta chiedono il pagamento?', 'multiple_choice', '["Euro", "Bitcoin o Monero (Criptovalute)", "Dollari", "Oro"]', 1, 'Perché sono difficili da tracciare.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '1296F2FD-1157-483B-9163-877CA4B4C1CC', 'BG', 'Doppia Estorsione',
    'Non basta decriptare. Ora minacciano di pubblicare i dati.',
    E'# Double Extortion\n\nI criminali non si limitano più a bloccare i dati.\nPrima di criptarli, **li copiano**.\n\nSe non paghi per la chiave di decrittazione, ti ricattano: "Pubblicheremo i brevetti e i dati dei clienti sul Dark Web".',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('1296F2FD-1157-483B-9163-877CA4B4C1CC', 'Cos''è la "Doppia Estorsione" (Double Extortion)?', 'multiple_choice', '["Pagare due volte", "Cifratura + Minaccia di pubblicazione dati (Data Breach)", "Due riscatti", "Due virus"]', 1, 'Aumenta la pressione: anche se hai il backup, rischi la reputazione.'),
('1296F2FD-1157-483B-9163-877CA4B4C1CC', 'Il GDPR c''entra qualcosa?', 'multiple_choice', '["No", "Sì, se vengono esfiltrati dati personali l''azienda rischia multe salate", "Solo in America", "Boh"]', 1, 'Oltre al danno del riscatto, arriva la beffa della multa.'),
('1296F2FD-1157-483B-9163-877CA4B4C1CC', 'Perché i backup online collegati alla rete non bastano?', 'multiple_choice', '["Sono lenti", "Il ransomware cerca e cripta anche quelli se sono accessibili", "Costano", "Sono brutti"]', 1, 'Il backup deve essere "Air-gapped" o scollegato fisicamente.'),
('1296F2FD-1157-483B-9163-877CA4B4C1CC', 'Cos''è un "Ransomware-as-a-Service" (RaaS)?', 'multiple_choice', '["Un software", "Modello di business dove i creatori del virus lo affittano ad altri criminali in cambio di una percentuale", "Un servizio di assistenza", "Un antivirus"]', 1, 'Ha industrializzato il crimine informatico.'),
('1296F2FD-1157-483B-9163-877CA4B4C1CC', 'Quanto tempo restano nella rete prima di attaccare?', 'multiple_choice', '["Un secondo", "Giorni o settimane (Dwell Time) per rubare dati e mappare la rete", "Anni", "Mai"]', 1, 'L''attacco finale è solo la punta dell''iceberg.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'A3CC34CF-E27B-45FC-AF49-2828148C086A', 'BG', 'Prevenzione Avanzata',
    'Come blindare la fabbrica digitale.',
    E'# Difesa in Profondità\n\nNon esiste una singola soluzione (Silver Bullet).\n\nServe:\n1.  **Formazione dipendenti** (il firewall umano).\n2.  **Segmentazione Rete** (non far parlare tutti con tutti).\n3.  **Patch Management** (aggiornare tutto subito).',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('A3CC34CF-E27B-45FC-AF49-2828148C086A', 'Cos''è la Segmentazione della Rete?', 'multiple_choice', '["Tagliare i cavi", "Dividere la rete in zone isolate in modo che se un PC è infetto, il virus non arrivi ai server critici", "Usare il Wi-Fi", "Spegnere internet"]', 1, 'Come le porte tagliafuoco in un edificio.'),
('A3CC34CF-E27B-45FC-AF49-2828148C086A', 'Perché gli aggiornamenti (Patch) sono critici?', 'multiple_choice', '["Aggiungono funzionalità", "Chiudono falle di sicurezza note che i ransomware sfruttano per entrare", "Rallentano il PC", "Cambiano i colori"]', 1, 'WannaCry ha colpito milioni di PC sfruttando una falla vecchia di mesi già corretta (ma non installata).'),
('A3CC34CF-E27B-45FC-AF49-2828148C086A', 'Cos''è il "Principio del Privilegio Minimo"?', 'multiple_choice', '["Essere poveri", "Dare a ogni utente solo gli accessi strettamente necessari per il suo lavoro, non di più", "Essere gentili", "Non avere password"]', 1, 'Se un account impiegato viene violato, l''hacker non deve poter accedere a tutto.'),
('A3CC34CF-E27B-45FC-AF49-2828148C086A', 'Cos''è l''EDR (Endpoint Detection and Response)?', 'multiple_choice', '["Un''auto", "Un antivirus evoluto che monitora i comportamenti sospetti e blocca gli attacchi in tempo reale", "Un medico", "Un drone"]', 1, 'L''antivirus classico basato su firme non basta più.'),
('A3CC34CF-E27B-45FC-AF49-2828148C086A', 'Cosa fare se sospetti un''infezione?', 'multiple_choice', '["Riavviare", "Scollegare immediatamente il dispositivo dalla rete (staccare cavo/WiFi) per isolarlo", "Aspettare", "Urlare"]', 1, 'La velocità di isolamento è fondamentale per salvare il resto dell''azienda.');


-- 3. BRESCIA (BS) - Business Invoice Fraud

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '7C8072D0-064B-4670-B108-352936C64F72', 'BS', 'Fatture e Trappole',
    'Arriva una fattura via mail. Sei sicuro sia vera?',
    E'# La truffa della fattura\n\nNelle aziende frenetiche, si paga spesso in automatico.\nI criminali inviano fatture identiche a quelle vere (luce, internet, fornitori) ma con:\n1.  IBAN diverso.\n2.  Importi piccoli (per non destare sospetti).',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('7C8072D0-064B-4670-B108-352936C64F72', 'Prima di pagare una fattura arrivata via mail, cosa controlli?', 'multiple_choice', '["L''importo", "Che l''IBAN corrisponda a quello storico registrato nel gestionale", "Il colore", "La carta"]', 1, 'L''IBAN è l''unica cosa che conta davvero.'),
('7C8072D0-064B-4670-B108-352936C64F72', 'Se l''IBAN è diverso dal solito?', 'multiple_choice', '["Paghi lo stesso", "Fermi tutto e chiami il fornitore per verifica", "Mandi una mail", "Fai un bonifico istantaneo"]', 1, 'Stop immediato.'),
('7C8072D0-064B-4670-B108-352936C64F72', 'Cos''è lo "Spoofing" del mittente?', 'multiple_choice', '["Uno sport", "Falsificare il nome che appare come mittente (es. scrivere ''Enel'' ma la mail è ''gino@gmail.com'')", "Un ballo", "Cucinare"]', 1, 'Non fidarti mai del "Nome visualizzato". Clicca per vedere l''indirizzo reale.'),
('7C8072D0-064B-4670-B108-352936C64F72', 'Perché usano importi piccoli?', 'multiple_choice', '["Sono poveri", "Per volare sotto i radar dei controlli (es. sotto i 1000€ non serve doppia autorizzazione)", "Per sbaglio", "Sono onesti"]', 1, 'Puntano sulla quantità, non sulla qualità.'),
('7C8072D0-064B-4670-B108-352936C64F72', 'Cosa fare con le fatture non attese?', 'multiple_choice', '["Pagare per sicurezza", "cestinare", "Verificare se il servizio è stato realmente richiesto", "Inoltrare a tutti"]', 2, 'Il 90% delle volte sono servizi mai ordinati.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '005F7E5B-F57A-4035-AC09-83212AE28412', 'BS', 'Il Dettaglio Invisibile',
    'Caratteri cirillici e domini simili. L''arte dell''inganno visivo.',
    E'# Homograph Attack\n\nGuarda questo dominio: `apple.com`\nE guarda questo: `appIe.com` (con la ''i'' maiuscola).\n\nO ancora peggio, usando caratteri cirillici che sembrano identici a quelli latini (es. ''a'').\n\nI criminali registrano questi domini per rendere le fatture indistinguibili.',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('005F7E5B-F57A-4035-AC09-83212AE28412', 'Cos''è un attacco omografico (Homograph Attack)?', 'multiple_choice', '["Scrivere male", "Usare caratteri visivamente identici (es. cirillico) per falsificare un dominio", "Disegnare", "Scrivere omofobo"]', 1, 'L''occhio umano non vede la differenza, il computer sì.'),
('005F7E5B-F57A-4035-AC09-83212AE28412', 'Come ti difendi dai domini simili?', 'multiple_choice', '["Occhiali nuovi", "Non cliccando link nelle fatture ma andando sul sito dai preferiti/digitando", "Lente d''ingrandimento", "Zoom"]', 1, 'Evita di usare i link forniti nella mail sospetta.'),
('005F7E5B-F57A-4035-AC09-83212AE28412', 'Il file "Fattura.pdf.exe" è sicuro?', 'multiple_choice', '["Sì, è un PDF", "No, è un programma eseguibile (virus) che si finge PDF grazie alla doppia estensione", "Dipende", "Sì"]', 1, 'Windows nasconde l''ultima estensione di default, traendo in inganno.'),
('005F7E5B-F57A-4035-AC09-83212AE28412', 'Se apri un PDF e ti chiede di "Abilitare le Macro/Contenuto", cosa fai?', 'multiple_choice', '["Abilito subito", "NON abilito mai. È quasi certamente un virus", "Chiedo al collega", "Spengo"]', 1, 'Le fatture non hanno bisogno di codice attivo per essere lette.'),
('005F7E5B-F57A-4035-AC09-83212AE28412', 'A cosa serve la "Firma Digitale" nelle fatture?', 'multiple_choice', '["A niente", "Garantisce autenticità e integrità del mittente", "Fa bello", "Costa"]', 1, 'Imparare a verificare la firma digitale è un ottimo scudo.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '3FDB09AE-E412-49D4-AF47-77D872C74467', 'BS', 'Verifica Out-of-Band',
    'La procedura che salva i milioni. Uscire dal canale compromesso.',
    E'# Out-of-Band Verification\n\nSe la richiesta arriva via Email... NON rispondere via Email.\nSe la richiesta arriva via Telefono... non fidarti della voce.\n\nDevi usare un **Canale Diverso** (Out-of-Band) per verificare.\nEsempio: Ricevo mail -> Chiamo al cellulare conosciuto.',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('3FDB09AE-E412-49D4-AF47-77D872C74467', 'Cosa significa "Out-of-Band"?', 'multiple_choice', '["Fuori dalla band", "Attraverso un canale di comunicazione diverso da quello dove è arrivata la richiesta", "Fuori legge", "Senza internet"]', 1, 'Se l''hacker controlla la mail, confermare via mail è inutile.'),
('3FDB09AE-E412-49D4-AF47-77D872C74467', 'Se il fornitore risponde alla mail dicendo che è tutto ok?', 'multiple_choice', '["Allora è ok", "Potrebbe essere ancora l''hacker che controlla la sua casella. Serve telefonare", "Mi fido", "Pago"]', 1, 'Mai chiedere all''oste se il vino è buono.'),
('3FDB09AE-E412-49D4-AF47-77D872C74467', 'Quale numero chiami per verificare?', 'multiple_choice', '["Quello nella firma della mail sospetta", "Quello che ho salvato in rubrica o sul sito ufficiale del fornitore", "Il 112", "A caso"]', 1, 'Se chiami il numero nella mail, risponderà il truffatore.'),
('3FDB09AE-E412-49D4-AF47-77D872C74467', 'Cosa fare se non rispondono al telefono?', 'multiple_choice', '["Pagare lo stesso", "Aspettare a pagare finché non si riesce a parlare con una persona reale", "Mandare un piccione", "Inviare soldi a caso"]', 1, 'Meglio un pagamento in ritardo che un pagamento rubato.'),
('3FDB09AE-E412-49D4-AF47-77D872C74467', 'Questa procedura rallenta il lavoro?', 'multiple_choice', '["Sì, ma è il prezzo della sicurezza", "No", "Poco", "Tanto"]', 0, 'La sicurezza è un attrito necessario. La velocità è nemica del controllo.');
