-- Mission Seed for Lombardia Part 1b (MB, SO, CO)
-- Generated by Antigravity

-- 4. MONZA E BRIANZA (MB) - Crypto & Investimenti

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '2831F999-30C8-4518-A16B-FAE20FD74E70', 'MB', 'Troppo Bello',
    'Guadagni del 10% al giorno? Sembra un affare imperdibile.',
    E'# "Get Rich Quick"\n\nNessun investimento legale garantisce rendimenti alti in poco tempo.\n\nSe vedi annunci con:\n*   "Guadagno garantito"\n*   "Rischio zero"\n*   Foto di auto di lusso e banconote\n\nÈ una truffa al 100%.',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('2831F999-30C8-4518-A16B-FAE20FD74E70', 'Qual è la regola d''oro degli investimenti?', 'multiple_choice', '["Se sembra troppo bello per essere vero, probabilmente è una truffa", "Puntare tutto sul rosso", "Credere agli influencer", "Investire a caso"]', 0, 'Il rischio e il rendimento sono sempre collegati. Rendimento alto = Rischio alto.'),
('2831F999-30C8-4518-A16B-FAE20FD74E70', 'Chi ti contatta di solito per queste truffe?', 'multiple_choice', '["La banca", "Sconosciuti su Telegram, WhatsApp o app di incontri (Pig Butchering)", "Il Papa", "La polizia"]', 1, 'Usano profili falsi attraenti o amichevoli per guadagnare fiducia.'),
('2831F999-30C8-4518-A16B-FAE20FD74E70', 'Cosa succede se provi a ritirare i soldi?', 'multiple_choice', '["Te li mandano subito", "Ti chiedono di pagare altre tasse/commissioni per sbloccarli (e poi spariscono)", "Ti regalano un''auto", "Raddoppiano"]', 1, 'È la fase finale della trappola: spillarti gli ultimi soldi.'),
('2831F999-30C8-4518-A16B-FAE20FD74E70', 'Perché usano le Criptovalute?', 'multiple_choice', '["Sono moderne", "Perché le transazioni sono irreversibili e difficili da tracciare per la polizia locale", "Sono ecologiche", "Piacciono a Elon Musk"]', 1, 'Una volta inviati, i Bitcoin non possono essere stornati dalla banca.'),
('2831F999-30C8-4518-A16B-FAE20FD74E70', 'I grafici che mostrano i tuoi guadagni sul loro sito sono veri?', 'multiple_choice', '["Sì, sempre", "No, sono solo numeri su uno schermo manipolabili dai truffatori per farti investire di più", "Forse", "Dipende"]', 1, 'È come un videogioco, i soldi reali sono già nel loro portafoglio.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '66A9BEF3-0951-4DF9-A0DE-758AC2BC43D1', 'MB', 'La Piramide',
    'Schemi Ponzi nell''era digitale. Come riconoscerli.',
    E'# Lo Schema Ponzi\n\nUn classico che non muore mai.\n\nTi promettono soldi non per vendere un prodotto, ma per **reclutare altre persone**.\nI soldi dei nuovi entrati pagano i vecchi... finché il sistema non crolla e tutti perdono tutto.',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('66A9BEF3-0951-4DF9-A0DE-758AC2BC43D1', 'Qual è la caratteristica principale di uno schema piramidale?', 'multiple_choice', '["Vende ottimi prodotti", "Il guadagno deriva principalmente dal reclutamento di nuovi membri, non dalla vendita di beni reali", "È triangolare", "È solido"]', 1, 'Se devi portare amici per guadagnare, scappa.'),
('66A9BEF3-0951-4DF9-A0DE-758AC2BC43D1', 'Perché crollano sempre?', 'multiple_choice', '["Per sfortuna", "Perché a un certo punto finiscono le persone sulla Terra da reclutare (saturazione)", "Per il meteo", "Per noia"]', 1, 'Matematicamente insostenibili.'),
('66A9BEF3-0951-4DF9-A0DE-758AC2BC43D1', 'I primi entrati guadagnano?', 'multiple_choice', '["Mai", "Sì, guadagnano rubando indirettamente i soldi agli ultimi arrivati", "Solo se onesti", "No"]', 1, 'Il fatto che tuo cugino abbia guadagnato non significa che sia legale o sicuro.'),
('66A9BEF3-0951-4DF9-A0DE-758AC2BC43D1', 'Cosa dicono spesso i promotori?', 'multiple_choice', '["È una truffa", "Sii il capo di te stesso! Vuoi restare povero? Non è una piramide, è un network!", "Non farlo", "È rischioso"]', 1, 'Usano tecniche di manipolazione psicologica e pressione sociale.'),
('66A9BEF3-0951-4DF9-A0DE-758AC2BC43D1', 'Le criptovalute sono sempre schemi Ponzi?', 'multiple_choice', '["Sì", "No, sono una tecnologia (Blockchain). Ma vengono spessissimo usate come esca per i Ponzi moderni", "Mai", "Solo Bitcoin"]', 1, 'Non confondere lo strumento (Crypto) con la truffa (Ponzi).');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '23BE9D50-02D6-44FD-A583-C1C2E7FC0C0B', 'MB', 'Chiavi in Mano',
    'Not your keys, not your coins. La sicurezza dei Wallet.',
    E'# Custodia delle Crypto\n\nSe lasci le tue criptovalute su un Exchange (sito web), non sono veramente tue.\nSe il sito chiude o scappa (Rug Pull), hai perso tutto.\n\nL''unica sicurezza è il **Cold Wallet** (chiavetta fisica) dove sei tu e solo tu a possedere la Seed Phrase.',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('23BE9D50-02D6-44FD-A583-C1C2E7FC0C0B', 'A chi devi dare la tua Seed Phrase (le 12/24 parole segrete)?', 'multiple_choice', '["Alla mamma", "A chi ti vuole aiutare", "A NESSUNO, MAI. Nemmeno al supporto tecnico", "Alla banca"]', 2, 'Chi ha quelle parole ha accesso totale ai tuoi fondi per sempre.'),
('23BE9D50-02D6-44FD-A583-C1C2E7FC0C0B', 'Dove conservare la Seed Phrase?', 'multiple_choice', '["Screenshot sul telefono", "Scritta su carta (o metallo) e nascosta in luogo sicuro offline", "Nelle note dell''iPhone", "Su Facebook"]', 1, 'Qualsiasi posto digitale è hackerabile. La carta non si hackera online.'),
('23BE9D50-02D6-44FD-A583-C1C2E7FC0C0B', 'Cos''è un "Rug Pull"?', 'multiple_choice', '["Tirare il tappeto", "Quando gli sviluppatori di un progetto crypto spariscono improvvisamente con i soldi degli investitori", "Un ballo", "Pulire casa"]', 1, 'Comunissimo nei progetti nuovi e poco seri (Shitcoins).'),
('23BE9D50-02D6-44FD-A583-C1C2E7FC0C0B', 'Cos''è l''Approal/Allowance Scam?', 'multiple_choice', '["Un premio", "Concedere a un sito malevolo il permesso di spendere i tuoi token firmando uno smart contract maligno", "Un regalo", "Un bug"]', 1, 'Spesso nascosto dietro promesse di "Airdrop gratuiti" o "NFT gratis".'),
('23BE9D50-02D6-44FD-A583-C1C2E7FC0C0B', 'Un Hardware Wallet (Ledger/Trezor) protegge se dai la Seed Phrase a qualcuno?', 'multiple_choice', '["Sì", "No. Se dai la Seed Phrase, la chiavetta fisica non serve a nulla", "Forse", "Dipende"]', 1, 'La chiavetta serve solo a non digitare la frase sul PC. La frase È il portafoglio.');


-- 5. SONDRIO (SO) - Banking Security (ATM Skimming)

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'FDF337F7-38B8-4BE1-83D3-99AEE717390B', 'SO', 'Mano a Coprire',
    'Un gesto antico ma sempre valido. Proteggere il PIN.',
    E'# ATM Security Basic\n\nQuando prelevi al Bancomat, il pericolo può essere fisico.\n\nLa regola numero uno è sempre la stessa: **copri la tastiera con l''altra mano** mentre digiti il PIN.\nLe microcamere nascoste non possono vedere attraverso la tua mano.',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('FDF337F7-38B8-4BE1-83D3-99AEE717390B', 'Perché coprire la mano mentre digiti il PIN è efficace?', 'multiple_choice', '["Per scaldarsi", "Blocca la visuale a telecamere nascoste (Skimmer) o persone alle spalle (Shoulder Surfing)", "È maleducato non farlo", "Per magia"]', 1, 'Un ostacolo fisico batte la tecnologia di spionaggio.'),
('FDF337F7-38B8-4BE1-83D3-99AEE717390B', 'Dove si nascondono le telecamere negli ATM?', 'multiple_choice', '["Sull''albero", "Spesso in una barra di plastica finta in alto sopra lo schermo o nel porta-opuscoli", "Sotto terra", "In banca"]', 1, 'Sono minuscole (pinhole cameras).'),
('FDF337F7-38B8-4BE1-83D3-99AEE717390B', 'Cos''è il "Shoulder Surfing"?', 'multiple_choice', '["Surf sulle spalle", "Qualcuno che sbircia da dietro le tue spalle mentre digiti password o PIN", "Uno sport", "Un ballo"]', 1, 'Attenzione a chi ti sta troppo vicino in coda.'),
('FDF337F7-38B8-4BE1-83D3-99AEE717390B', 'Se la fessura della carta sembra "ballerina" o sporgente?', 'multiple_choice', '["È vecchia", "Potrebbe esserci uno Skimmer (lettore falso) sovrapposto. Prova a muoverla", "Spingi forte", "Usa la colla"]', 1, 'Se si muove o si stacca, non inserire la carta.'),
('FDF337F7-38B8-4BE1-83D3-99AEE717390B', 'È sicuro scrivere il PIN sulla carta?', 'multiple_choice', '["Sì, così non lo scordo", "NO! Mai. È come lasciare le chiavi nella serratura", "Solo a matita", "Solo sul retro"]', 1, 'Se perdi la carta, perdi i soldi. Se hai il PIN scritto sopra, glieli regali.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    'AB7A06A3-7F61-467E-82B4-21C746D627FD', 'SO', 'Caccia allo Skimmer',
    'Dispositivi fantasma che clonano la tua carta in un secondo.',
    E'# Skimmer & Shimmer\n\n*   **Skimmer**: "Guscio" falso messo sopra la bocchetta dell''ATM. Legge la banda magnetica.\n*   **Shimmer**: Sottilissimo chip inserito DENTRO la fessura. Legge il chip della carta.\n\nSe qualcosa non ti convince nell''aspetto del Bancomat, cambia banca.',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('AB7A06A3-7F61-467E-82B4-21C746D627FD', 'Cos''è uno Skimmer?', 'multiple_choice', '["Uno sci", "Un dispositivo che legge e copia i dati della banda magnetica della carta", "Un ladro", "Un bancomat"]', 1, 'Crea un clone perfetto della tua carta.'),
('AB7A06A3-7F61-467E-82B4-21C746D627FD', 'Qual è l''ATM più sicuro?', 'multiple_choice', '["Quello isolato e buio", "Quello dentro la filiale della banca (spesso sorvegliato o chiuso di notte)", "Quello al benzinaio", "Quello rotto"]', 1, 'È più difficile installare skimmer all''interno delle filiali sorvegliate.'),
('AB7A06A3-7F61-467E-82B4-21C746D627FD', 'Se la carta rimane incastrata e nessuno ti aiuta?', 'multiple_choice', '["Vai a casa", "Chiami subito il numero verde per bloccarla restando lì davanti", "Prendi a calci l''ATM", "Piangi"]', 1, 'Potrebbe essere un "Cash Trapping" o "Card Trapping". Se te ne vai, il ladro la recupera.'),
('AB7A06A3-7F61-467E-82B4-21C746D627FD', 'La banda magnetica è sicura?', 'multiple_choice', '["Sì", "No, è tecnologia anni ''60 facilmente clonabile. Il Chip è molto più sicuro", "Boh", "Forse"]', 1, 'Per questo in Europa si usa il Chip & PIN, ma gli hacker cercano di forzare l''uso della banda (fallback).'),
('AB7A06A3-7F61-467E-82B4-21C746D627FD', 'Cosa fare se noti movimenti strani sul conto?', 'multiple_choice', '["Aspettare fine mese", "Bloccare la carta immediatamente dall''App e denunciare", "Chiedere agli amici", "Niente"]', 1, 'La tempestività limita i danni.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '897B0C4C-3371-46BE-811F-660FC722F99C', 'SO', 'RFID & Contactless',
    'Ti possono rubare i dati passandoti vicino? La verità.',
    E'# Furto Wireless?\n\nLe carte Contactless emettono un segnale radio.\nEsiste il mito dell''hacker che ti passa vicino con un POS e ti ruba i soldi.\n\nÈ tecnicamente possibile ma... molto raro e difficile da monetizzare realmente. Tuttavia, la prudenza non è mai troppa (RFID Blocking Wallet).',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('897B0C4C-3371-46BE-811F-660FC722F99C', 'A cosa serve un portafoglio "RFID Blocking"?', 'multiple_choice', '["A non far uscire le monete", "Schermare le carte contactless impedendo che vengano lette a distanza", "A renderle invisibili", "A nulla"]', 1, 'Crea una gabbia di Faraday attorno alle carte.'),
('897B0C4C-3371-46BE-811F-660FC722F99C', 'È facile rubare soldi passando con un POS vicino alla tasca?', 'multiple_choice', '["Facilissimo", "Possibile ma difficile: serve vicinanza estrema e il POS è registrato a nome di qualcuno (tracciabile)", "Impossibile", "Legale"]', 1, 'Il ladro lascerebbe una scia digitale che porta dritto a lui.'),
('897B0C4C-3371-46BE-811F-660FC722F99C', 'Qual è il limite del contactless senza PIN?', 'multiple_choice', '["Infinito", "Di solito 25€ o 50€ (dipende dalla banca)", "1 milione", "Zero"]', 1, 'Questo limita il danno massimo di un singolo furto.'),
('897B0C4C-3371-46BE-811F-660FC722F99C', 'Disattivare il contactless dall''app aiuta?', 'multiple_choice', '["Sì, se non lo usi è la sicurezza massima", "No", "Rompe la carta", "Cancella i soldi"]', 1, 'Riduci la superficie di attacco.'),
('897B0C4C-3371-46BE-811F-660FC722F99C', 'Le notifiche SMS/App per ogni spesa servono?', 'multiple_choice', '["No, sono noiose", "Sì, sono fondamentali per accorgersi subito di un furto", "Costano troppo", "Inutili"]', 1, 'Prima te ne accorgi, prima blocchi tutto.');


-- 6. COMO (CO) - Tourism & Rental Scams

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '8673D4DC-AB7A-4B14-919B-7231EFFE8D6F', 'CO', 'La Villa Fantasma',
    'Una villa sul lago a 50€ a notte? Troppo bello.',
    E'# Truffe Case Vacanza\n\nComo è piena di turisti, e di truffe.\nTrovi un annuncio: foto stupende, prezzo stracciato.\n\nIl proprietario dice: "Sono all''estero, non posso farti vedere la casa, ma fidati".\nSe invii la caparra, scoprirai che la casa non esiste (o è di un altro).',
    'semplice', '5 min', 100, 'level_1', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('8673D4DC-AB7A-4B14-919B-7231EFFE8D6F', 'Qual è il segnale d''allarme numero 1 negli affitti?', 'multiple_choice', '["Foto brutte", "Prezzo troppo basso rispetto alla media di mercato e "impossibilità" di visitare la casa", "Risposte lente", "Mancanza di Wi-Fi"]', 1, 'Nessuno regala ville sul lago di Como.'),
('8673D4DC-AB7A-4B14-919B-7231EFFE8D6F', 'Se il proprietario dice di essere all''estero?', 'multiple_choice', '["È normale", "Classica scusa per evitare l''incontro di persona", "È un diplomatico", "È in vacanza"]', 1, 'È la scusa più vecchia del mondo.'),
('8673D4DC-AB7A-4B14-919B-7231EFFE8D6F', 'Cosa fare con le foto dell''annuncio?', 'multiple_choice', '["Guardarle", "Fare una Ricerca Immagini Inversa (Reverse Image Search) su Google", "Stampare", "Mettere like"]', 1, 'Spesso scoprirai che sono foto rubate da un sito immobiliare di lusso o da un''altra città.'),
('8673D4DC-AB7A-4B14-919B-7231EFFE8D6F', 'Ti chiedono i documenti via mail prima di vedere la casa. Li mandi?', 'multiple_choice', '["Sì, per bloccarla", "No! Rischio furto d''identità", "Solo la patente", "Solo il codice fiscale"]', 1, 'Useranno i tuoi documenti per truffare altra gente a tuo nome.'),
('8673D4DC-AB7A-4B14-919B-7231EFFE8D6F', 'Meglio usare piattaforme note (Airbnb/Booking) o accordi privati?', 'multiple_choice', '["Accordi privati su WhatsApp (risparmio)", "Piattaforme note che offrono garanzie e rimborsi", "Il passaparola", "Facebook"]', 1, 'Le piattaforme trattengono i soldi fino al check-in, proteggendoti.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '06DDAE66-A92C-4638-BB32-9082970A2D84', 'CO', 'Fuori Piattaforma',
    'Risparmiare le commissioni o perdere tutto?',
    E'# "Parliamo su WhatsApp"\n\nSei su Airbnb/Booking.\nL''host ti scrive: "Ciao, se mi paghi con bonifico diretto ti faccio lo sconto del 20% così evitiamo le commissioni del sito".\n\nSe accetti, **perdi ogni protezione**.',
    'medio', '10 min', 200, 'level_2', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('06DDAE66-A92C-4638-BB32-9082970A2D84', 'Perché i truffatori vogliono portarti fuori dalla piattaforma (Off-platform)?', 'multiple_choice', '["Per fare amicizia", "Perché fuori dalla chat ufficiale non sono monitorati e non hai diritto a rimborsi", "Per risparmiare", "Per velocità"]', 1, 'Senza l''intermediario, sei solo contro il truffatore.'),
('06DDAE66-A92C-4638-BB32-9082970A2D84', 'Quali metodi di pagamento preferiscono i truffatori?', 'multiple_choice', '["Carta di credito", "Bonifico istantaneo, ricarica Postepay, MoneyTransfer (Western Union)", "PayPal Beni e Servizi", "Assegno"]', 1, 'Metodi veloci e non stornabili.'),
('06DDAE66-A92C-4638-BB32-9082970A2D84', 'Se ricevi una mail da "Airbnb" che chiede un bonifico?', 'multiple_choice', '["È normale", "Airbnb non chiede MAI bonifici diretti. È una mail di phishing", "Pago", "Stampo"]', 1, 'Si paga sempre e solo tramite il sito/app.'),
('06DDAE66-A92C-4638-BB32-9082970A2D84', 'Cosa succede se paghi fuori piattaforma e la casa non esiste?', 'multiple_choice', '["Airbnb ti rimborsa", "Hai perso i soldi e il sito non può aiutarti", "Polizia ti ridà i soldi", "L''assicurazione paga"]', 1, 'Hai violato i termini di servizio, auto-escludendoti dalla protezione.'),
('06DDAE66-A92C-4638-BB32-9082970A2D84', 'La recensione "Host fantastico" è garanzia assoluta?', 'multiple_choice', '["Sì", "No, gli account possono essere hackerati (Account Takeover) per sfruttare la reputazione passata", "Forse", "Sempre"]', 1, 'Anche gli account "Superhost" possono essere rubati. Guarda sempre se ci sono cambi repentini di comportamento.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '00EEB6DB-3A65-4E9B-B94D-5AA92A89284C', 'CO', 'Foto Rubate',
    'Investigazione digitale: smascherare l''annuncio falso.',
    E'# Sherlock Holmes Digitale\n\nPrima di prenotare, investiga.\n1.  **Reverse Image Search**: Quella foto della cucina appare anche su un sito di vendita ville a Miami?\n2.  **Street View**: L''indirizzo esiste? C''è davvero una casa lì o un magazzino?',
    'difficile', '15 min', 500, 'level_3', 'Lombardia', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('00EEB6DB-3A65-4E9B-B94D-5AA92A89284C', 'A cosa serve Google Street View nelle truffe immobiliari?', 'multiple_choice', '["A vedere il traffico", "A verificare se l''edificio all''indirizzo corrisponde alle foto dell''annuncio", "A viaggiare gratis", "A niente"]', 1, 'Se l''annuncio dice "Vista lago" e Street View mostra un''autostrada, è una truffa.'),
('00EEB6DB-3A65-4E9B-B94D-5AA92A89284C', 'Come si fa una ricerca inversa per immagini?', 'multiple_choice', '["Non si può", "Caricando la foto su Google Images o TinEye", "Chiedendo a un amico", "Usando la lente"]', 1, 'Strumento potentissimo per smascherare i falsi.'),
('00EEB6DB-3A65-4E9B-B94D-5AA92A89284C', 'Se trovi la stessa casa su un altro sito a prezzo doppio?', 'multiple_choice', '["L''altro è caro", "Quello economico è quasi certamente una truffa (Clone Listing)", "Prenoto quello basso", "Chiamo entrambi"]', 1, 'I truffatori copiano annunci veri ma dimezzano il prezzo per attirare le vittime.'),
('00EEB6DB-3A65-4E9B-B94D-5AA92A89284C', 'Cosa chiedere all''host per verifica?', 'multiple_choice', '["Niente", "Un video in diretta dalla casa o una foto specifica (es. con un foglio con la data odierna)", "Il meteo", "Il nome del cane"]', 1, 'Se non hanno accesso alla casa, non possono farlo.'),
('00EEB6DB-3A65-4E9B-B94D-5AA92A89284C', 'Chi è responsabile dei controlli?', 'multiple_choice', '["La piattaforma", "Tu. La piattaforma fa controlli base, ma la prudenza finale spetta a te", "Il Sindaco", "Nessuno"]', 1, 'Fidarsi è bene, non fidarsi è meglio.');
