-- Mission Seed for Veneto Part 2 (VI, TV)
-- Generated by Antigravity
-- Theme: Social Engineering & Human Hacking

-- 4. VICENZA (VI) - Baiting & Physical Security ("L'Oro degli Stolti")

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '56EF8A9B-C0D1-4960-7890-123456789DEF', 'VI', 'Chiavetta Smarrita',
    'Hai trovato una chiavetta USB nel parcheggio. Che fortuna?',
    E'# USB Baiting\n\nÈ una tecnica classica.\nL''hacker lascia una chiavetta USB infetta in un luogo strategico (parcheggio aziendale, bar), magari con etichetta "Stipendi" o "Foto Vacanze".\n\nLa curiosità uccide il gatto... e il PC.\nAppena la inserisci, un malware si installa automaticamente.',
    'semplice', '5 min', 100, 'level_1', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('56EF8A9B-C0D1-4960-7890-123456789DEF', 'Cosa fare se trovi una USB per terra?', 'multiple_choice', '["Inserirla per vedere di chi è e restituirla", "Non inserirla MAI nel tuo PC. Portarla alla sicurezza/IT o distruggerla", "Formattarla", "Regalarla"]', 1, 'La curiosità è il vettore di attacco.'),
('56EF8A9B-C0D1-4960-7890-123456789DEF', 'Cos''è una "Rubber Ducky"?', 'multiple_choice', '["Una papera di gomma", "Una finta chiavetta USB che in realtà è una tastiera automatizzata che digita comandi malevoli in millisecondi", "Un giocattolo", "Un antivirus"]', 1, 'Sembra una chiavetta, ma il PC la vede come tastiera e obbedisce a tutto.'),
('56EF8A9B-C0D1-4960-7890-123456789DEF', 'Gli antivirus rilevano sempre le USB malevole?', 'multiple_choice', '["Sì, sempre", "No, specialmente se emulano tastiere (HID attacks) perché non sono virus software ma hardware malevolo", "Dipende dalla marca", "Solo se costosi"]', 1, 'L''attacco hardware bypassa molte difese software.'),
('56EF8A9B-C0D1-4960-7890-123456789DEF', 'Il Baiting funziona solo con le USB?', 'multiple_choice', '["Sì", "No, anche con CD, QR Code, o download digitali promessi gratis", "Solo con floppy disk", "Solo con SD Card"]', 1, 'Qualsiasi "esca" che promette qualcosa gratis o suscita curiosità.'),
('56EF8A9B-C0D1-4960-7890-123456789DEF', 'Se vuoi proprio vedere cosa c''è dentro?', 'multiple_choice', '["Usi il PC del lavoro", "Usi un PC \"sacrificale\" (isolato, senza rete, air-gapped) che puoi formattare dopo", "Usi il telefono con adattatore", "Chiedi a un amico"]', 1, 'Mai usare un dispositivo contenente dati personali o aziendali.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '67F9AB0C-D1E2-4071-8901-234567890EFA', 'VI', 'Cavo del Vicino',
    'Ti prestano un cavo di ricarica. Ti fidi?',
    E'# O.MG Cable\n\nEsistono cavi Lightning o USB-C che sembrano identici agli originali Apple/Samsung.\nMa dentro il connettore c''è un microchip Wi-Fi.\n\nAppena lo colleghi per caricare il telefono, l''hacker (lì vicino) prende il controllo del tuo dispositivo o registra ciò che digiti.',
    'medio', '10 min', 200, 'level_2', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('67F9AB0C-D1E2-4071-8901-234567890EFA', 'Come si distingue un cavo O.MG da uno originale?', 'multiple_choice', '["È rosso", "È quasi impossibile a occhio nudo. Sembrano identici", "Ha un odore strano", "È più pesante"]', 1, 'La miniaturizzazione ha reso l''hardware hacking invisibile.'),
('67F9AB0C-D1E2-4071-8901-234567890EFA', 'Cosa può fare un cavo malevolo?', 'multiple_choice', '["Solo ricaricare", "Iniettare comandi (Keystroke Injection), rubare password, installare malware", "Rompere il telefono", "Scaldare"]', 1, 'È un computer microscopico dentro il cavo.'),
('67F9AB0C-D1E2-4071-8901-234567890EFA', 'Meglio usare cavi propri o prestati?', 'multiple_choice', '["Prestati, si risparmia", "Sempre usare i propri cavi e alimentatori di cui si ha fiducia", "Indifferente", "Quelli trovati per terra"]', 1, 'La tua "Supply Chain" personale è importante.'),
('67F9AB0C-D1E2-4071-8901-234567890EFA', 'I gadget promozionali (es. ventilatori USB) sono sicuri?', 'multiple_choice', '["Sì, sono regali", "Potrebbero contenere malware o danneggiare elettricamente la porta USB", "Sono fantastici", "Sempre sicuri"]', 1, 'Mai collegare gadget spazzatura al PC di lavoro.'),
('67F9AB0C-D1E2-4071-8901-234567890EFA', 'La ricarica Wireless (Qi) trasmette dati?', 'multiple_choice', '["Sì", "No, trasmette solo energia per induzione. È sicura dal punto di vista dati", "Forse", "Dipende"]', 1, 'La ricarica wireless è un''ottima alternativa sicura in pubblico.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    '78ABCDE1-E2F3-4182-9012-345678901FAB', 'VI', 'QR Code in Piazza',
    'Scansiona per vincere! O per perdere.',
    E'# Quishing (QR Phishing)\n\nI QR Code sono link mascherati.\nI truffatori incollano i loro QR Code GIGANTI sopra quelli legittimi (es. sui parchimetri, menù, poster).\n\nTu pensi di pagare il parcheggio, invece stai inserendo la carta di credito su un sito clone.',
    'difficile', '15 min', 500, 'level_3', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('78ABCDE1-E2F3-4182-9012-345678901FAB', 'Cos''è il "Quishing"?', 'multiple_choice', '["Pesca veloce", "Phishing tramite QR Code che reindirizza a siti malevoli", "Un piatto tipico", "Un test"]', 1, 'Il QR code aggira i filtri antispam delle email perché è un''immagine.'),
('78ABCDE1-E2F3-4182-9012-345678901FAB', 'Sui parchimetri/monopattini, cosa controllare?', 'multiple_choice', '["Se sono puliti", "Se c''è un adesivo posticcio incollato sopra il QR Code originale", "Se c''è il sole", "Niente"]', 1, 'Tattica fisica molto comune.'),
('78ABCDE1-E2F3-4182-9012-345678901FAB', 'È possibile verificare l''URL di un QR prima di aprirlo?', 'multiple_choice', '["No, si apre subito", "Sì, la maggior parte delle app fotocamera mostra un''anteprima del link. Leggilo attentamente!", "Solo pagando", "No"]', 1, 'Non cliccare "Apri" alla cieca.'),
('78ABCDE1-E2F3-4182-9012-345678901FAB', 'Un QR Code può scaricare un virus direttamente?', 'multiple_choice', '["Sì, magicamente", "No, ti porta a un sito web. Il pericolo è quello che fai sul sito (scaricare un''app, inserire dati)", "Forse", "Esplode il telefono"]', 1, 'Il QR è solo un link. L''azione umana successiva è il rischio.'),
('78ABCDE1-E2F3-4182-9012-345678901FAB', 'Se ricevi un QR code via email per "autenticazione"?', 'multiple_choice', '["Lo scansioni subito", "Sospetto. È un metodo per evadere i controlli antivirus della posta aziendale", "Normale", "Lo stampo"]', 1, 'Gli attaccanti usano i QR nelle mail perché i filtri di testo non riescono a leggerli.');


-- 5. TREVISO (TV) - Pretexting & Social Engineering ("Il Finto Tecnico")

-- Mission 1: Semplice
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    -- OLD INVALID: 89BCDEF2-F3G4-4293-0123-456789012ABC (G is bad)
    '89BCDEF2-F3F4-4293-0123-456789012ABC', 'TV', 'Pronto, Supporto',
    '"Salve, rileviamo virus sul suo computer."',
    E'# Tech Support Scam\n\nTi chiamano (spesso dall''estero) dicendo di essere Microsoft/Amazon/Supporto Tecnico.\n"Il tuo PC invia segnali di errore!"\n\nTi fanno installare un programma di "assistenza remota" (TeamViewer, AnyDesk) e... ti svuotano il conto mentre guardi.',
    'semplice', '5 min', 100, 'level_1', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('89BCDEF2-F3F4-4293-0123-456789012ABC', 'Microsoft ti chiamerà mai a casa per un virus?', 'multiple_choice', '["Sì, sono gentili", "MAI. Nessuna grande azienda monitora il tuo singolo PC per avvisarti telefonicamente", "A volte", "Solo se paghi"]', 1, 'È una truffa al 100%.'),
('89BCDEF2-F3F4-4293-0123-456789012ABC', 'Cosa fare se ti chiedono di scaricare AnyDesk/TeamViewer?', 'multiple_choice', '["Scaricare subito", "Riagganciare immediatamente. Sono software di controllo remoto: stai dando loro le chiavi di casa", "Chiedere aiuto", "Farli aspettare"]', 1, 'Una volta connessi, possono fare tutto col tuo mouse.'),
('89BCDEF2-F3F4-4293-0123-456789012ABC', 'Se appare un popup "PC BLOCCATO, CHIAMA NUMERO VERDE"?', 'multiple_choice', '["È vero, chiamo", "È un banner pubblicitario malevolo (Scareware). Non chiamare, chiudi il browser (o riavvia)", "Piango", "Compro un pc nuovo"]', 1, 'Non è un vero messaggio di sistema, è una pagina web a tutto schermo.'),
('89BCDEF2-F3F4-4293-0123-456789012ABC', 'Perché ti chiedono di accedere all''Home Banking?', 'multiple_choice', '["Per verificare i pagamenti", "Per farti vedere un finto rimborso... modificando l''HTML della pagina (\"F12 scam\") per farti credere di aver ricevuto soldi e chiedertene indietro", "Per sicurezza", "Per amicizia"]', 1, 'Manipolano ciò che vedi a schermo.'),
('89BCDEF2-F3F4-4293-0123-456789012ABC', 'Cosa fare se sei cascato nella trappola?', 'multiple_choice', '["Vergognarsi e tacere", "Staccare internet, spegnere PC, chiamare la banca da un altro telefono, denunciare", "Niente", "Aspettare"]', 1, 'Il tempo è denaro.');


-- Mission 2: Medio
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    -- OLD INVALID: 90CDEFG3-G4H5-4304-1234-567890123BCD (G, H are bad)
    '90CDEF13-F4A5-4304-1234-567890123BCD', 'TV', 'Sondaggi Pericolosi',
    'Rispondi a 3 domande e vinci un buono Amazon da 500€!',
    E'# Data Harvesting Scam\n\nNessuno regala soldi.\nQuesti sondaggi servono a raccogliere i tuoi dati (Nome, Email, Telefono, Indirizzo) per vendere liste "lead" agli spammer o per furti d''identità.\n\nIl premio finale... richiede di inserire la carta di credito per "spese di spedizione" (2€). E qui scatta l''abbonamento nascosto.',
    'medio', '10 min', 200, 'level_2', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('90CDEF13-F4A5-4304-1234-567890123BCD', 'Se per ricevere un premio gratuito devi pagare 2€ di spedizione?', 'multiple_choice', '["È un affare", "Stai dando i dati della carta di credito a un truffatore. Probabilmente attiveranno un abbonamento mensile costoso", "Pago", "Giusto"]', 1, 'È la trappola dell''affiliazione occulta.'),
('90CDEF13-F4A5-4304-1234-567890123BCD', 'Perché vogliono i tuoi dati personali?', 'multiple_choice', '["Per conoscerti", "Perché i dati (Big Data) hanno valore commerciale. O per usarli in attacchi di Spear Phishing successivi", "Per mandarti cartoline", "Per nulla"]', 1, 'Se il servizio è gratis, il prodotto sei tu.'),
('90CDEF13-F4A5-4304-1234-567890123BCD', 'I commenti sotto il post "Ho vinto davvero!" sono reali?', 'multiple_choice', '["Sì, vedi le foto", "No, sono Bot o profili falsi creati per generare ''Social Proof'' (riprova sociale)", "Forse", "Sempre"]', 1, 'Non fidarti delle testimonianze sui siti sospetti.'),
('90CDEF13-F4A5-4304-1234-567890123BCD', 'Cosa succede se metti il tuo numero di telefono?', 'multiple_choice', '["Ti chiamano amici", "Inizi a ricevere spam telefonico, SMS truffa o abbonamenti a servizi a sovrapprezzo (VAS)", "Migliora la linea", "Niente"]', 1, 'Non dare mai il numero se non strettamente necessario.'),
('90CDEF13-F4A5-4304-1234-567890123BCD', 'Come riconoscere un sondaggio falso?', 'multiple_choice', '["Grafica brutta, URL strano, promesse esagerate, timer che corre (Urgenza)", "È su Facebook", "Ha le domande giuste", "Usa colori blu"]', 0, 'Il timer e l''urgenza sono sempre presenti.');


-- Mission 3: Difficile
INSERT INTO public.missions (id, province_id, title, description, content, level, estimated_time, nc_reward, tier, region, created_at)
VALUES (
    -- OLD INVALID: 01DEFGH4-H5I6-4415-2345-678901234CDE (G, H, I are bad)
    '01DEF1A4-C5B6-4415-2345-678901234CDE', 'TV', 'L''Ispettore',
    'Aprite, controllo di sicurezza!',
    E'# Impersonation & Pretexting\n\nQualcuno si presenta in ufficio o chiama dicendo: "Sono dell''IT, dobbiamo fare un aggiornamento urgente".\n\nCon un "Pretesto" solido e un tono autoritario, cerca di bypassare le procedure.\n"Dammi la password, sennò ti blocco l''account!"\n\nL''autorità è la leva psicologica più forte.',
    'difficile', '15 min', 500, 'level_3', 'Veneto', NOW()
) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, nc_reward=EXCLUDED.nc_reward, level=EXCLUDED.level;

INSERT INTO public.mission_questions (mission_id, text, type, options, correct_answer, explanation) VALUES
('01DEF1A4-C5B6-4415-2345-678901234CDE', 'Cos''è il "Pretexting"?', 'multiple_choice', '["Scrivere un testo prima", "Creare uno scenario inventato (pretesto) credibile per manipolare la vittima e ottenere informazioni", "Recitare", "Mentire male"]', 1, 'Gli attori usano il Pretexting. Anche gli hacker.'),
('01DEF1A4-C5B6-4415-2345-678901234CDE', 'Perché l''attaccante usa un tono autoritario o arrabbiato?', 'multiple_choice', '["È nervoso", "Per metterti sotto pressione e farti ubbidire senza fare domande", "È pazzo", "Ha fretta"]', 1, 'Inibisce la tua volontà di verificare.'),
('01DEF1A4-C5B6-4415-2345-678901234CDE', 'Cosa fare se un "tecnico" chiede la password?', 'multiple_choice', '["Dargliela", "RIFIUTARE. Nessun tecnico vero ha bisogno della tua password (hanno permessi admin)", "Scriverla su un foglio", "Dirottarlo al collega"]', 1, 'La password è personale e non cedibile.'),
('01DEF1A4-C5B6-4415-2345-678901234CDE', 'Cos''è efficace contro il Pretexting?', 'multiple_choice', '["Essere maleducati", "Procedure chiare e verifica dell''identità (richiamare il numero interno ufficiale, chiedere il badge)", "Chiudere la porta", "Nascondersi"]', 1, 'Seguire la procedura batte la manipolazione sociale.'),
('01DEF1A4-C5B6-4415-2345-678901234CDE', 'L''attacco può venire da un numero interno dell''azienda?', 'multiple_choice', '["No, è sicuro", "Sì, se hanno compromesso il VoIP o stanno chiamando da un telefono nella hall/sala riunioni vuota", "Impossibile", "Solo dal capo"]', 1, 'Non fidarti ciecaemente del Caller ID interno.');
